/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.introductory;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: COOL.MDL
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: 2</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class Cool {

    public static void main(String[] args) {
        new Cool().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("COOL")
                .defaultSimulation("Minute", 100.0, "Minute", 0.25);

        // Stocks
        builder.stock(new StockDef("Coffee Temperature", "Coffee Temperature", 140.0, "Farenheit", null));

        // Constants
        builder.constant("TIME_STEP", 0.25, "Minute");
        builder.constant("INITIAL_TIME", 0.0, "Minute");
        builder.constant("FINAL_TIME", 100.0, "Minute");
        builder.constant("initial temperature", 140.0, "Farenheit");
        builder.constant("room temperature", 68.0, "Farenheit");
        builder.constant("time to cool", 20.0, "minute");

        // Variables
        builder.variable(new VariableDef("cooling", "cooling", "(Coffee_Temperature - room_temperature) / time_to_cool", "Farenheit/minute"));

        // Flows
        builder.flow(new FlowDef("Coffee Temperature net flow", "Net flow for Coffee Temperature", "-cooling", "Minute", null, "Coffee Temperature"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
