/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.introductory;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: POPGAME.MDL
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: 11</li>
 *   <li>View 'View 1' connector references non-existent element: 13</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 4</li>
 *   <li>View 'View 1' connector references non-existent element: 12</li>
 *   <li>View 'View 1' connector references non-existent element: 7</li>
 *   <li>View 'View 1' connector references non-existent element: 12</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class PopGame {

    public static void main(String[] args) {
        new PopGame().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("POPGAME")
                .defaultSimulation("Month", 100.0, "Month");

        // Stocks
        builder.stock(new StockDef("Population", "Population", 100.0, "Rabbit", null));

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");
        builder.constant("death rate", 0.01, "fraction/Month");
        builder.constant("birth rate", 0.03, "fraction/Month");

        // Variables
        builder.variable(new VariableDef("births", "births", "Population * birth_rate", "Rabbit/Month"));
        builder.variable(new VariableDef("deaths", "deaths", "Population* death_rate", "Rabbit/Month"));

        // Flows
        builder.flow(new FlowDef("Population inflow 1", null, "births", "Month", null, "Population"));
        builder.flow(new FlowDef("Population outflow 2", null, "deaths", "Month", "Population", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
