/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.introductory;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 1008_PULSEandPULSETRAIN.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: TIME STEP</li>
 *   <li>View 'View 1' places non-existent element: TIME STEP</li>
 *   <li>View 'View 1' connector references non-existent element: TIME STEP</li>
 *   <li>View 'View 1' connector references non-existent element: TIME STEP</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class PulseAndPulseTrain {

    public static void main(String[] args) {
        new PulseAndPulseTrain().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1008_PULSEandPULSETRAIN")
                .defaultSimulation("Month", 40.0, "Month", 0.125);

        // Stocks
        builder.stock(new StockDef("stock", "stock", 0.0, "", null));

        // Variables
        builder.variable(new VariableDef("inflow", "inflow", "2*PULSE_TRAIN(5, TIME_STEP , 2 , 35)/TIME_STEP", "units/Year"));
        builder.variable(new VariableDef("outflow", "outflow", "PULSE_TRAIN(6, 1, 2 , 40 ) * stock/TIME_STEP", "units/Year"));

        // Flows
        builder.flow(new FlowDef("stock inflow 1", null, "inflow", "Month", null, "stock"));
        builder.flow(new FlowDef("stock outflow 2", null, "outflow", "Month", "stock", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
