/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.introductory;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: SNOWBALL.MDL
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: 2</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class Snowball {

    public static void main(String[] args) {
        new Snowball().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("SNOWBALL")
                .defaultSimulation("Minute", 10.0, "Minute", 0.25);

        // Stocks
        builder.stock(new StockDef("Snowball Size", "Snowball Size", 0.25, "Kg", null));

        // Constants
        builder.constant("TIME_STEP", 0.25, "Minute");
        builder.constant("INITIAL_TIME", 0.0, "Minute");
        builder.constant("FINAL_TIME", 10.0, "Minute");
        builder.constant("initial snowball size", 0.25, "Kg");
        builder.constant("stickiness of snow", 1.0, "1/Minute");

        // Variables
        builder.variable(new VariableDef("snowball growth", "snowball growth", "Snowball_Size * stickiness_of_snow", "Kg/Minute"));

        // Flows
        builder.flow(new FlowDef("Snowball Size net flow", "Net flow for Snowball Size", "snowball_growth", "Minute", null, "Snowball Size"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
