/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.introductory;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: SPEED.MDL
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: 2</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class Speed {

    public static void main(String[] args) {
        new Speed().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("SPEED")
                .defaultSimulation("Second", 60.0, "Second", 0.5);

        // Stocks
        builder.stock(new StockDef("Speed", "Speed", 0.0, "Miles/Hour", null));

        // Constants
        builder.constant("TIME_STEP", 0.5, "Second");
        builder.constant("INITIAL_TIME", 0.0, "Second");
        builder.constant("FINAL_TIME", 60.0, "Second");
        builder.constant("initial speed", 0.0, "Miles/Hour");
        builder.constant("target speed", 55.0, "Miles/Hour");
        builder.constant("time to adjust speed", 10.0, "Second");

        // Variables
        builder.variable(new VariableDef("acceleration", "acceleration", "(target_speed-Speed)/time_to_adjust_speed", "Miles/Hour/Second"));

        // Flows
        builder.flow(new FlowDef("Speed net flow", "Net flow for Speed", "acceleration", "Second", null, "Speed"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
