/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.introductory;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: CAFFEINE.MDL
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class VensimCaffeine {

    public static void main(String[] args) {
        new VensimCaffeine().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("CAFFEINE")
                .defaultSimulation("Day", 50.0, "Day", 0.0625);

        // Stocks
        builder.stock(new StockDef("Bodys Expected Caffeine", "Body's Expected Caffeine", 0.0, "Caffeine_in_Body", "Mg", null, List.of()));
        builder.stock(new StockDef("Caffeine in Body", "Caffeine in Body", 0.0, "normal_caffeine_consumption*caffeine_disposal_time", "Mg", null, List.of()));

        // Constants
        builder.constant("caffeine disposal time", 0.25, "Day");
        builder.constant("caffeine tolerance time", 5.0, "Day");
        builder.constant("normal caffeine consumption", 100.0, "Mg/Day");
        builder.constant("normal amount of drowsiness", 1.0, "Yawn/Hour");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("effect of drowsiness on caffeine consumption lookup", "effect of drowsiness on caffeine consumption lookup", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 10.0}, new double[]{0.01, 1.0, 7.0, 9.2, 9.9, 10.0, 10.0033}, "LINEAR", "Dmnl"));

        // Variables
        builder.variable(new VariableDef("caffeine consumption", "caffeine consumption", "normal_caffeine_consumption * LOOKUP(effect_of_drowsiness_on_caffeine_consumption_lookup, drowsiness/ normal_amount_of_drowsiness)", "Mg/Day"));
        builder.variable(new VariableDef("caffeine disposal", "caffeine disposal", "Caffeine_in_Body/caffeine_disposal_time", "Mg/Day"));
        builder.variable(new VariableDef("drowsiness", "drowsiness", "normal_amount_of_drowsiness* IF((Caffeine_in_Body) == 0, 10, (Bodys_Expected_Caffeine) / (Caffeine_in_Body)) * effect_of_stress_on_drowsiness", "Yawn/Hour"));
        builder.variable(new VariableDef("effect of stress on drowsiness", "effect of stress on drowsiness", "1 + STEP(0.2,10)", "Dmnl"));

        // Flows
        builder.flow(new FlowDef("Bodys Expected Caffeine net flow", "Net flow for Body's Expected Caffeine", "(Caffeine_in_Body - Bodys_Expected_Caffeine) / caffeine_tolerance_time", "Day", null, "Bodys Expected Caffeine"));
        builder.flow(new FlowDef("Caffeine in Body inflow 1", null, "caffeine_consumption", "Day", null, "Caffeine in Body"));
        builder.flow(new FlowDef("Caffeine in Body outflow 2", null, "caffeine_disposal", "Day", "Caffeine in Body", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
