/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.introductory;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: 1010_whitepinknoise.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Lookup 'Table for Order Fulfillment': sorted non-monotonic x-values and removed 1 duplicate(s)</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'Customer Orders' places non-existent element: TIME STEP</li>
 *   <li>View 'Customer Orders' places non-existent element: Time</li>
 *   <li>View 'Customer Orders' places non-existent element: TIME STEP</li>
 *   <li>View 'Customer Orders' places non-existent element: _92</li>
 *   <li>View 'Customer Orders' connector references non-existent element: Time</li>
 *   <li>View 'Customer Orders' connector references non-existent element: TIME STEP</li>
 *   <li>View 'Customer Orders' connector references non-existent element: _92</li>
 *   <li>View 'Customer Orders' connector references non-existent element: TIME STEP</li>
 *   <li>View 'Customer Orders' flow route references non-existent flow: _92</li>
 *   <li>View 'Production and Inventory' places non-existent element: _48</li>
 *   <li>View 'Production and Inventory' places non-existent element: _48</li>
 *   <li>View 'Production and Inventory' places non-existent element: _48</li>
 *   <li>View 'Production and Inventory' places non-existent element: _1500</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _1500</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _1500</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Production and Inventory' connector references non-existent element: _1500</li>
 *   <li>View 'Production and Inventory' flow route references non-existent flow: _48</li>
 *   <li>View 'Production and Inventory' flow route references non-existent flow: _48</li>
 *   <li>View 'Production and Inventory' flow route references non-existent flow: _48</li>
 *   <li>View 'Production and Inventory' flow route references non-existent flow: _1500</li>
 *   <li>View 'Labor' places non-existent element: _48</li>
 *   <li>View 'Labor' places non-existent element: _48</li>
 *   <li>View 'Labor' places non-existent element: _48</li>
 *   <li>View 'Labor' places non-existent element: _48</li>
 *   <li>View 'Labor' places non-existent element: _48</li>
 *   <li>View 'Labor' places non-existent element: _48</li>
 *   <li>View 'Labor' connector references non-existent element: _48</li>
 *   <li>View 'Labor' connector references non-existent element: _48</li>
 *   <li>View 'Labor' connector references non-existent element: _48</li>
 *   <li>View 'Labor' flow route references non-existent flow: _48</li>
 *   <li>View 'Labor' flow route references non-existent flow: _48</li>
 *   <li>View 'Labor' flow route references non-existent flow: _48</li>
 *   <li>View 'Labor' flow route references non-existent flow: _48</li>
 *   <li>View 'Labor' flow route references non-existent flow: _48</li>
 *   <li>View 'Labor' flow route references non-existent flow: _48</li>
 *   <li>View 'Productivity' places non-existent element: TIME STEP</li>
 *   <li>View 'Productivity' places non-existent element: _92</li>
 *   <li>View 'Productivity' connector references non-existent element: _92</li>
 *   <li>View 'Productivity' connector references non-existent element: TIME STEP</li>
 *   <li>View 'Productivity' flow route references non-existent flow: _92</li>
 * </ul>
 */
public class WhitePinkNoise {

    public static void main(String[] args) {
        new WhitePinkNoise().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1010_whitepinknoise")
                .defaultSimulation("Week", 500.0, "Week", 0.125);

        // Stocks
        builder.stock(new StockDef("Labor", "The labor force of the firm.", 0.0, "Desired_Labor", "People", null, List.of()));
        builder.stock(new StockDef("Vacancies", "The number of open positions the firm seeks to fill.", 0.0, "Desired_Vacancies", "People", null, List.of()));
        builder.stock(new StockDef("Pink Noise in Prody", "Pink Noise is first-order autocorrelated noise.  Pink noise provides a realistic  noise input to\n\t\t        models in which the next random shock depends in part on the previous  shocks.  The user\n\t\t        can specify the correlation time.  The mean and standard deviation are  specified\n\t\t         by the user.", 1.0, "Dimensionless", null));
        builder.stock(new StockDef("Inventory", "The level of finished goods inventory in the plant.  Increased by production and  decreased by\n\t\t         shipments.  Initially set to the desired inventory level.", 0.0, "Desired_Inventory", "Widgets", null, List.of()));
        builder.stock(new StockDef("Expected Order Rate", "The demand forecast is formed by adaptive expectations, using exponential smoothing,  a common\n\t\t         forecasting technique.  The initial forecast is equal to the  initial customer order rate.", 0.0, "Customer_Order_Rate", "Widgets/Week", null, List.of()));
        builder.stock(new StockDef("Work in Process Inventory", "WIP inventory accumulates the difference between production starts and  completions.", 0.0, "Desired_WIP", "Widgets", null, List.of()));
        builder.stock(new StockDef("Pink Noise", "Pink Noise is first-order autocorrelated noise.  Pink noise provides a realistic  noise input to\n\t\t        models in which the next random shock depends in part on the previous  shocks.  The user\n\t\t        can specify the correlation time.  The mean is 0 and the standard deviation  is specified\n\t\t         by the user.", 0.0, "Dimensionless", null));

        // Constants
        builder.constant("Average Duration of Employment", 100.0, "Weeks");
        builder.constant("Average Layoff Time", 8.0, "Weeks");
        builder.constant("Average Time to Fill Vacancies", 8.0, "Weeks");
        builder.constant("Time to Form Expected Productivity", 13.0, "Weeks");
        builder.constant("Vacancy Adjustment Time", 4.0, "Weeks");
        builder.constant("Vacancy Cancellation Time", 2.0, "Weeks");
        builder.constant("Willingness to Lay Off", 1.0, "Dimensionless");
        builder.constant("Labor Adjustment Time", 13.0, "Weeks");
        builder.constant("Start Time for Noise in Productivity", 1.0, "Week");
        builder.constant("Average Productivity", 0.25, "Widgets/(Hour*Person)");
        builder.constant("Mean for Random Effects on Productivity", 1.0, "Dimensionless");
        builder.constant("Switch for Pink Noise in Productivity", 1.0, "Dimensionless");
        builder.constant("Random Seed for Productivity", 1.0, "Dimensionless");
        builder.constant("Standard Deviation in Random Effects on Productivity", 0.0, "Dimensionless");
        builder.constant("Noise Correlation Time for Productivity", 4.0, "Week");
        builder.constant("Switch for Labor in Production", 1.0, "Dimensionless");
        builder.constant("Standard Workweek", 40.0, "Hours/Week");
        builder.constant("Workweek", 40.0, "Hours/Week");
        builder.constant("Minimum Order Processing Time", 2.0, "Weeks");
        builder.constant("Safety Stock Coverage", 2.0, "Weeks");
        builder.constant("Time to Average Order Rate", 8.0, "Weeks");
        builder.constant("Manufacturing Cycle Time", 8.0, "Weeks");
        builder.constant("WIP Adjustment Time", 6.0, "Weeks");
        builder.constant("Inventory Adjustment Time", 12.0, "Weeks");
        builder.constant("Initial Customer Order Rate", 10000.0, "Widgets/Week");
        builder.constant("Step Height", 0.0, "Dimensionless");
        builder.constant("Step Time", 5.0, "Week");
        builder.constant("Pulse Quantity", 0.0, "Dimensionless*Week");
        builder.constant("Pulse Time", 5.0, "Week");
        builder.constant("Ramp Slope", 0.0, "1/Week");
        builder.constant("Ramp Start Time", 5.0, "Week");
        builder.constant("Ramp End Time", 1.0E9, "Week");
        builder.constant("Sine Amplitude", 0.0, "Dimensionless");
        builder.constant("Sine Period", 50.0, "Weeks");
        builder.constant("Noise Start Time", 5.0, "Week");
        builder.constant("Noise Correlation Time", 4.0, "Week");
        builder.constant("Noise Standard Deviation", 0.0, "Dimensionless");
        builder.constant("Noise Seed", 1.0, "Dimensionless");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("Table for Order Fulfillment", "The ability to ship is constrained by inventory availability.  As the inventory  level drops, the \n\t\t        fraction of customer orders that can be filled decreases.  When inventory is  zero, shipments\n\t\t         cease.  Unfilled customer orders are lost.\\!\\!\\!", new double[]{0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0}, new double[]{0.0, 0.2, 0.4, 0.58, 0.73, 0.85, 0.93, 0.97, 0.99, 1.0, 1.0}, "LINEAR", "Dimensionless"));

        // Variables
        builder.variable(new VariableDef("Adjustment for Labor", "Adjusts the desired hiring rate to bring labor in line with the desired  level.", "(Desired_Labor - Labor)/Labor_Adjustment_Time", "People/Week"));
        builder.variable(new VariableDef("Production Start Rate", "The production start rate is determined by the labor force,  productivity,  and the workweek.", "Switch_for_Labor_in_Production*Labor*Workweek*Productivity + (1-Switch_for_Labor_in_Production )*Desired_Production_Start_Rate", "Widgets/Week"));
        builder.variable(new VariableDef("Adjustment for Vacancies", "Adjusts vacancy creation so the firm has the desired number of vacancies.", "(Desired_Vacancies - Vacancies)/Vacancy_Adjustment_Time", "People/Week"));
        builder.variable(new VariableDef("Layoff Rate", "The layoff rate is the lesser of the desired or maximum rate.", "MIN(Desired_Lay_Off_Rate, Maximum_Layoff_Rate)", "People/Week"));
        builder.variable(new VariableDef("Hiring Rate", "Hiring depends on the number of open vacancies and the average time  required to fill a vacancy.", "Vacancies/Average_Time_to_Fill_Vacancies", "People/Week"));
        builder.variable(new VariableDef("Quit Rate", "The rate at which employees voluntarily leave the firm.  Determined by the  average duration of employment.", "Labor/Average_Duration_of_Employment", "People/Week"));
        builder.variable(new VariableDef("Desired Vacancy Cancellation Rate", "The desired rate of vacancy cancellation, given by the desired vacancy  creation rate whenever that rate is negative.", "MAX(0, -Desired_Vacancy_Creation_Rate)", "People/Week"));
        builder.variable(new VariableDef("Desired Hiring Rate", "The firm seeks to hire enough people to replace expected attrition and  adjust the labor force to the desired level.", "Expected_Attrition_Rate + Adjustment_for_Labor", "People/Week"));
        builder.variable(new VariableDef("Maximum Vacancy Cancellation Rate", "The maximum vacancy cancellation rate is determined by the numer of  vacancies outstanding and the minimum cancellation time.", "Vacancies/Vacancy_Cancellation_Time", "People/Week"));
        builder.variable(new VariableDef("Desired Labor", "Desired labor is given by the desired production start rate, expected  productivity per hour, and the planned workweek.", "Desired_Production_Start_Rate/(Standard_Workweek*Expected_Productivity)", "People"));
        builder.variable(new VariableDef("Desired Lay Off Rate", "The firm desires to lay people off whenever the desired hiring rate is  negative, modified by their willingness to lay off.  Willingness to Lay  Off = 0 implies a no layoff policy.", "Willingness_to_Lay_Off * MAX(0, -Desired_Hiring_Rate)", "People/Week"));
        builder.variable(new VariableDef("Vacancy Creation Rate", "The rate at which the firm authorizes new positions and begins to recruit  for them.", "MAX(0,Desired_Vacancy_Creation_Rate)", "People/Week"));
        builder.variable(new VariableDef("Expected Attrition Rate", "In this simple model expected attrition is set to the actual voluntary  quit rate.", "Quit_Rate", "People/Week"));
        builder.variable(new VariableDef("Desired Vacancies", "The number of vacancies needed to generate the desired hiring rate, given  the expected time required to fill a vacancy.", "MAX(0,Expected_Time_to_Fill_Vacancies*Desired_Hiring_Rate)", "People"));
        builder.variable(new VariableDef("Desired Vacancy Creation Rate", "The firm seeks to create enough vacancies to yield the desired hiring  rate, adjusted to bring the stock of vacancies in line with the desired  stock.", "Desired_Hiring_Rate + Adjustment_for_Vacancies", "People/Week"));
        builder.variable(new VariableDef("Vacancy Closure Rate", "Hiring a new employee fills a vacancy.", "Hiring_Rate", "People/Week"));
        builder.variable(new VariableDef("Maximum Layoff Rate", "The maximum layoff rate is determined by the number of workers and the  layoff time.", "Labor/Average_Layoff_Time", "People/Week"));
        builder.variable(new VariableDef("Expected Time to Fill Vacancies", "The expected time required to fill vacancies.  In this simple model, set  to the actual time.  A better formulation would use an information delay  to represent the delay in gathering information about hiring delays and  changing procedures.", "Average_Time_to_Fill_Vacancies", "Weeks"));
        builder.variable(new VariableDef("Vacancy Cancellation Rate", "The rate at which the firm cancels existing vacancies prior to filling  them.", "MIN(Desired_Vacancy_Cancellation_Rate, Maximum_Vacancy_Cancellation_Rate)", "People/Week"));
        builder.variable(new VariableDef("Normally Distributed Noise", "A white noise signal, distributed normally, with a mean and standard  deviation set by the modeler.  The distribution is truncated 0²Noise²4;  the lower limit maintains nonnegativity of productivity; the upper limit  is high relative to plausible standard deviations.  The noise seen can  also be varied.", "1+STEP(1,Start_Time_for_Noise_in_Productivity)*(RANDOM_NORMAL(0, 4 , Mean_for_Random_Effects_on_Productivity , Standard_Deviation_in_Random_Effects_on_Productivity , Random_Seed_for_Productivity )-1)", "Dimensionless"));
        builder.variable(new VariableDef("Expected Productivity", "Expected productivity is the firm's belief about the productivity of the  labor force, and adjusts to actual productivity with a delay.  First order  smoothing is assumed.", "SMOOTH(Productivity,Time_to_Form_Expected_Productivity)", "Widgets/(Hour*Person)"));
        builder.variable(new VariableDef("Change in Pink Noise in Prody", "Change in the pink noise value; Pink noise is a first order exponential smoothing  delay of the white\n\t\t         noise input.", "(White_Noise_in_Prody - Pink_Noise_in_Prody)/Noise_Correlation_Time_for_Productivity", "1/Week"));
        builder.variable(new VariableDef("Productivity", "Productivity is average productivity perturbed by a random variable  representing unmodeled sources of variation in output per person.", "Average_Productivity*Random_Effects_on_Productivity", "Widgets/Hour/Person"));
        builder.variable(new VariableDef("Random Effects on Productivity", "The random effects on productivity can be set either to normally  distributed white noise or pink noise.  Noise begins at the noise start  time.", "1+STEP(1,Start_Time_for_Noise_in_Productivity)*(Switch_for_Pink_Noise_in_Productivity *Pink_Noise_in_Prody + (1-Switch_for_Pink_Noise_in_Productivity)*Normally_Distributed_Noise -1)", "Dimensionless"));
        builder.variable(new VariableDef("White Noise in Prody", "White noise input to the pink noise process.", "Mean_for_Random_Effects_on_Productivity+ Standard_Deviation_in_Random_Effects_on_Productivity *((24*Noise_Correlation_Time_for_Productivity /TIME_STEP)**0.5*(RANDOM_UNIFORM(-0.5, 0.5 , Random_Seed_for_Productivity) ))", "Dimensionless"));
        builder.variable(new VariableDef("Desired Production Start Rate", "The desired rate of production starts, equal to the desired production rate adjusted  by the adequacy\n\t\t         of the WIP inventory.", "Desired_Production + Adjustment_for_WIP", "Widgets/Week"));
        builder.variable(new VariableDef("Ratio of Maximum to Desired Shipments", "The ratio of the maximum to desired shipment rate.  Ratios less than one  indicate shipments are constrained below the desired level.", "Maximum_Shipment_Rate/Desired_Shipment_Rate", "Dimensionless"));
        builder.variable(new VariableDef("Order Fulfillment Ratio", "The Fraction of customer orders filled is determined by the ratio of the  normal shipment rate to the desired rate.  The normal rate is the rate  current inventory permits under normal circumstances.  Low inventory  availability reduces shipments below customer orders.  Unfilled customer  orders are lost.", "LOOKUP(Table_for_Order_Fulfillment, Maximum_Shipment_Rate/Desired_Shipment_Rate)", "Dimensionless"));
        builder.variable(new VariableDef("Shipment Rate", "The shipment rate is the desired shipment rate multiplied by the fraction  of orders filled (the order fulfillment ratio.   Shipments fall below  desired shipments when the feasible shipment rate falls below the desired  rate, indicating that some products are unavailable.", "Desired_Shipment_Rate*Order_Fulfillment_Ratio", "Widgets/Week"));
        builder.variable(new VariableDef("Desired Shipment Rate", "The desired shipment rate equals the customer order rate.  In this model  there is no backlog of unfilled orders:  unfilled orders are lost as  customers seek alternate sources of supply.", "Customer_Order_Rate", "Widgets/Week"));
        builder.variable(new VariableDef("Inventory Coverage", "Inventory coverage is given by the ratio of inventory to shipments.", "Inventory/Shipment_Rate", "Weeks"));
        builder.variable(new VariableDef("Desired Inventory Coverage", "Desired inventory coverage is the number of weeks of the demand forecast the plant  seeks to maintain\n\t\t        in inventory.  This inventory coverage is required to maintain delivery  reliability by\n\t\t         buffering the plant against unforeseen variations in demand or  production.  It consists of the normal order processing time plus an  additional term representing the coverage desired to maintain safety  stocks.", "Minimum_Order_Processing_Time + Safety_Stock_Coverage", "Weeks"));
        builder.variable(new VariableDef("Maximum Shipment Rate", "The maximum rate of shipments the firm can achieve given their current  inventory level and the minimum order processing time.", "Inventory/Minimum_Order_Processing_Time", "Widgets/Week"));
        builder.variable(new VariableDef("Desired Inventory", "The desired inventory level sought by the plant.  Experience suggests that to  maintain customer\n\t\t        service by providing full and reliable deliveries, the plant must maintain a  certain\n\t\t         coverage of throughput (demand), estimated by the demand forecast.", "Desired_Inventory_Coverage*Expected_Order_Rate", "Widgets"));
        builder.variable(new VariableDef("Change in Exp Orders", "The demand forecast adjusts to the actual order rate over a time period determined  by the Time to\n\t\t        Average Order Rate.  The demand forecast is formed by first-order  exponential smoothing,\n\t\t         a widely used forecasting technique.", "(Customer_Order_Rate-Expected_Order_Rate)/ Time_to_Average_Order_Rate", "(Widgets/Week)/Week"));
        builder.variable(new VariableDef("Production Rate", "Production is a third order delay of the production start rate, with the delay time  determined by\n\t\t         the manufacturing cycle time.", "DELAY3(Production_Start_Rate,Manufacturing_Cycle_Time)", "Widgets/Week"));
        builder.variable(new VariableDef("Adjustment for WIP", "The adjustment to the production start rate from the adequacy of WIP  inventory.", "(Desired_WIP - Work_in_Process_Inventory)/WIP_Adjustment_Time", "Widgets/Week"));
        builder.variable(new VariableDef("Desired WIP", "The desired quantity of work in process inventory.  Proportional to the  manufacturing cycle time and\n\t\t         the desired rate of production.", "Manufacturing_Cycle_Time*Desired_Production", "Widgets"));
        builder.variable(new VariableDef("Desired Production", "Desired Production is the demand forecast (Expected Order Rate) adjusted to bring  the inventory\n\t\t         position in line with the target inventory level.", "MAX(0,Expected_Order_Rate+Production_Adjustment_from_Inventory)", "Widgets/Week"));
        builder.variable(new VariableDef("Production Adjustment from Inventory", "The desired production rate is adjusted above or below the forecast based on the  inventory position\n\t\t        of the plant.  When desired inventory > inventory, desired production is  increased (and\n\t\t         vice-versa).  Inventory gaps are corrected over the inv. adj.  time.", "(Desired_Inventory - Inventory)/ Inventory_Adjustment_Time", "Widgets/Week"));
        builder.variable(new VariableDef("Customer Order Rate", "Customer order rate is exogenous.  A variety of test inputs allow users to try  different patterns,\n\t\t         including a step, pulse, sine wave, and random noise.", "Initial_Customer_Order_Rate*Input", "Widgets/Week"));
        builder.variable(new VariableDef("Input", "Input is a dimensionless variable which provides a variety of test input patterns,  including a step,\n\t\t         pulse, sine wave, and random noise.", "1+STEP(Step_Height,Step_Time)+ (Pulse_Quantity/TIME_STEP)*PULSE(Pulse_Time,TIME_STEP)+ RAMP(Ramp_Slope,Ramp_Start_Time,Ramp_End_Time)+ Sine_Amplitude*SIN(2*3.14159*TIME/Sine_Period)+ STEP(1,Noise_Start_Time)*Pink_Noise", "Dimensionless"));
        builder.variable(new VariableDef("Change in Pink Noise", "Change in the pink noise value; Pink noise is a first order exponential smoothing  delay of the white\n\t\t         noise input.", "(White_Noise - Pink_Noise)/Noise_Correlation_Time", "1/Week"));
        builder.variable(new VariableDef("White Noise", "White noise input to the pink noise process.", "Noise_Standard_Deviation*((24*Noise_Correlation_Time/TIME_STEP)**0.5*(RANDOM_UNIFORM(0, 1, 0) - 0.5 ))", "Dimensionless"));

        // Flows
        builder.flow(new FlowDef("Labor inflow 1", null, "Hiring_Rate", "Week", null, "Labor"));
        builder.flow(new FlowDef("Labor outflow 2", null, "Quit_Rate", "Week", "Labor", null));
        builder.flow(new FlowDef("Labor outflow 3", null, "Layoff_Rate", "Week", "Labor", null));
        builder.flow(new FlowDef("Vacancies inflow 1", null, "Vacancy_Creation_Rate", "Week", null, "Vacancies"));
        builder.flow(new FlowDef("Vacancies outflow 2", null, "Vacancy_Closure_Rate", "Week", "Vacancies", null));
        builder.flow(new FlowDef("Vacancies outflow 3", null, "Vacancy_Cancellation_Rate", "Week", "Vacancies", null));
        builder.flow(new FlowDef("Pink Noise in Prody net flow", "Net flow for Pink Noise in Prody", "Change_in_Pink_Noise_in_Prody", "Week", null, "Pink Noise in Prody"));
        builder.flow(new FlowDef("Inventory inflow 1", null, "Production_Rate", "Week", null, "Inventory"));
        builder.flow(new FlowDef("Inventory outflow 2", null, "Shipment_Rate", "Week", "Inventory", null));
        builder.flow(new FlowDef("Expected Order Rate net flow", "Net flow for Expected Order Rate", "Change_in_Exp_Orders", "Week", null, "Expected Order Rate"));
        builder.flow(new FlowDef("Work in Process Inventory inflow 1", null, "Production_Start_Rate", "Week", null, "Work in Process Inventory"));
        builder.flow(new FlowDef("Work in Process Inventory outflow 2", null, "Production_Rate", "Week", "Work in Process Inventory", null));
        builder.flow(new FlowDef("Pink Noise net flow", "Net flow for Pink Noise", "Change_in_Pink_Noise", "Week", null, "Pink Noise"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
