/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.physics;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: GRAVITY.MDL
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class VensimGravity {

    public static void main(String[] args) {
        new VensimGravity().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("GRAVITY")
                .defaultSimulation("Second", 1000.0, "Second", 5.0);

        // Stocks
        builder.stock(new StockDef("Position 1", "Position 1", 0.0, "Meter", null));
        builder.stock(new StockDef("Position 2", "Position 2", 1.0, "Meter", null));
        builder.stock(new StockDef("speed 1", "speed 1", 0.0, "Meter/Second", null));
        builder.stock(new StockDef("speed 2", "speed 2", 0.0, "Meter/Second", null));

        // Constants
        builder.constant("g", 6.67E-11, "Meter*Meter*Meter/Second/Second/Kg");
        builder.constant("initial distance", 1.0, "Meter");
        builder.constant("mass 1", 10000.0, "Kg");
        builder.constant("mass 2", 1000.0, "Kg");

        // Variables
        builder.variable(new VariableDef("acceleration 1", "acceleration 1", "attraction_force/mass_1", "Meter/Second/Second"));
        builder.variable(new VariableDef("acceleration 2", "acceleration 2", "-attraction_force/mass_2", "Meter/(Second*Second)"));
        builder.variable(new VariableDef("attraction force", "attraction force", "g * mass_1 * mass_2 /(distance * distance)", "Kg*Meter/Second/Second"));
        builder.variable(new VariableDef("distance", "distance", "Position_2 - Position_1", "Meter"));

        // Flows
        builder.flow(new FlowDef("Position 1 net flow", "Net flow for Position 1", "speed_1", "Second", null, "Position 1"));
        builder.flow(new FlowDef("Position 2 net flow", "Net flow for Position 2", "speed_2", "Second", null, "Position 2"));
        builder.flow(new FlowDef("speed 1 net flow", "Net flow for speed 1", "acceleration_1", "Second", null, "speed 1"));
        builder.flow(new FlowDef("speed 2 net flow", "Net flow for speed 2", "acceleration_2", "Second", null, "speed 2"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
