/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.environment;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 1404_EnvManagementInMiniworldWOcorrectunits.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class EnvironmentalManagement {

    public static void main(String[] args) {
        new EnvironmentalManagement().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1404_EnvManagementInMiniworldWOcorrectunits")
                .defaultSimulation("Year", 500.0, "Year", 0.2);

        // Stocks
        builder.stock(new StockDef("population", "population", 1.0, "Dmnl", null));
        builder.stock(new StockDef("environmental pollution", "environmental pollution", 1.0, "Dmnl", null));
        builder.stock(new StockDef("production capacity", "production capacity", 1.0, "Dmnl", null));

        // Constants
        builder.constant("INITAL POPULATION", 1.0, "Dmnl");
        builder.constant("INITIAL CAPACITY", 1.0, "Dmnl");
        builder.constant("INITIAL POLLUTION", 1.0, "Dmnl");
        builder.constant("normal regeneration rate", 0.02, "1/Year");
        builder.constant("birth rate", 0.03, "1/Year");
        builder.constant("normal growth rate", 0.04, "1/Year");
        builder.constant("consumption goal", 4.0, "Dmnl");
        builder.constant("DAMAGE THRESHOLD", 2.0, "Dmnl");
        builder.constant("death rate", 0.015, "1/Year");
        builder.constant("normal degradation rate", 0.02, "1/Year");

        // Variables
        builder.variable(new VariableDef("births", "births", "birth_rate*population*environmental_quality*consumption_level", "1/Year"));
        builder.variable(new VariableDef("capacity increase", "(GROWTH RATE*consumption level*environmental  pollution*population*(1-(consumption level*environmental  pollution/CONSUMPTION GOAL)))", "(normal_growth_rate*consumption_level*environmental_quality*population*(1-(consumption_level *population*environmental_quality/consumption_goal)))", "1/Year"));
        builder.variable(new VariableDef("regeneration", "environmental pollution^(1/2)*REGENERATION RATE^(environmental pollution)                                               +  REGENERATION RATE^(environmental pollution)", "normal_regeneration_rate*environmental_pollution", "1/Year"));
        builder.variable(new VariableDef("consumption level", "consumption level", "production_capacity", "Dmnl"));
        builder.variable(new VariableDef("degradation", "degradation", "normal_degradation_rate*population*consumption_level", "1/Year"));
        builder.variable(new VariableDef("deaths", "deaths", "death_rate*population*DELAY3(environmental_pollution,10)", "1/Year"));
        builder.variable(new VariableDef("environmental quality", "environmental quality", "DELAY3(MIN(DAMAGE_THRESHOLD/environmental_pollution,1),20)", "Dmnl"));

        // Flows
        builder.flow(new FlowDef("population inflow 1", null, "births", "Year", null, "population"));
        builder.flow(new FlowDef("population outflow 2", null, "deaths", "Year", "population", null));
        builder.flow(new FlowDef("environmental pollution inflow 1", null, "degradation", "Year", null, "environmental pollution"));
        builder.flow(new FlowDef("environmental pollution outflow 2", null, "regeneration", "Year", "environmental pollution", null));
        builder.flow(new FlowDef("production capacity net flow", "Net flow for production capacity", "capacity_increase", "Year", null, "production capacity"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
