/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.control;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: repair02.mdl
 * Source: Vensim User's Guide
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Variable 'total maintenance workforce' has no equation; imported as constant 0</li>
 * </ul>
 */
public class Repair02 {

    public static void main(String[] args) {
        new Repair02().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("repair02")
                .defaultSimulation("Month", 24.0, "Month");

        // Stocks
        builder.stock(new StockDef("total time since service", "total time since service", 0.0, "total_machines * machine_wear_time", "Machine*Month", null, List.of()));

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 24.0, "Month");
        builder.constant("total maintenance workforce", 0.0, "Person");
        builder.constant("machine wear time", 2.0, "Month");
        builder.constant("maintenance productivity", 120.0, "Machine/Person/Month");
        builder.constant("maintained machine failure rate", 0.1, "1/Month");
        builder.constant("repair productivity", 30.0, "Machine/Person/Month");
        builder.constant("total machines", 1000.0, "Machine");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("effect_machine_wear_reliability_lookup", null, new double[]{0.0, 1.0, 1.5, 2.0, 3.0, 4.0}, new double[]{0.9, 1.0, 1.1, 1.5, 3.0, 6.0}, "LINEAR"));

        // Variables
        builder.variable(new VariableDef("routine maintenance work done", "routine maintenance work done", "MIN(total_machines/machine_wear_time,workers_available_for_routine_maintenance * maintenance_productivity )", "Machine/Month"));
        builder.variable(new VariableDef("repair completions", "repair completions", "workers_performing_repairs * repair_productivity", "Machine/Month"));
        builder.variable(new VariableDef("effect machine wear reliability", "effect machine wear reliability", "LOOKUP(effect_machine_wear_reliability_lookup, average_time_since_service/machine_wear_time)", "Dmnl"));
        builder.variable(new VariableDef("workers performing repairs", "workers performing repairs", "MIN(number_of_repairs_required/repair_productivity,total_maintenance_workforce)", "Person"));
        builder.variable(new VariableDef("workers available for routine maintenance", "workers available for routine maintenance", "total_maintenance_workforce - workers_performing_repairs", "Person"));
        builder.variable(new VariableDef("average machine failure rate", "average machine failure rate", "maintained_machine_failure_rate * effect_machine_wear_reliability", "1/Month"));
        builder.variable(new VariableDef("average time since service", "average time since service", "total_time_since_service/total_machines", "Month"));
        builder.variable(new VariableDef("number of repairs required", "number of repairs required", "average_machine_failure_rate * total_machines", "Machine/Month"));

        // Flows
        builder.flow(new FlowDef("total time since service inflow 1", null, "total_machines", "Month", null, "total time since service"));
        builder.flow(new FlowDef("total time since service outflow 2", null, "(repair_completions + routine_maintenance_work_done) * average_time_since_service", "Month", "total time since service", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim User's Guide")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
