/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.control;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: WFKAL.MDL
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Variable 'sales' has no equation; imported as constant 0</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: 4</li>
 *   <li>View '1' connector references non-existent element: 61</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: 18</li>
 *   <li>View '1' connector references non-existent element: 60</li>
 *   <li>View '1' connector references non-existent element: 20</li>
 *   <li>View '1' connector references non-existent element: 60</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class WfKal {

    public static void main(String[] args) {
        new WfKal().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("WFKAL")
                .defaultSimulation("Month", 100.0, "Month");

        // Stocks
        builder.stock(new StockDef("Workforce", "The number of working people.", 0.0, "initial_workforce", "person", null, List.of()));
        builder.stock(new StockDef("Exp Sales", "The expected amount of sales.", 0.0, "sales", "widget/month", null, List.of()));
        builder.stock(new StockDef("Inventory", "The amount of inventory on hand.", 0.0, "des_inventory", "widget", null, List.of()));

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");
        builder.constant("net hire noise", 0.0, "person/month");
        builder.constant("time adjust workforce", 12.0, "month");
        builder.constant("norm productivity", 1.0, "widget/person/month");
        builder.constant("productivity noise", 0.0, "widget/(person*month)");
        builder.constant("time avg sales", 6.0, "month");
        builder.constant("time correct inventory", 4.0, "month");
        builder.constant("inventory coverage", 3.0, "month");
        builder.constant("inventory meas noise", 0.0, "dmnl");
        builder.constant("workforce meas noise", 0.0, "dmnl");
        builder.constant("sales", 0.0, "widget/month");
        builder.constant("meas workforce variance", 0.5, "dmnl");
        builder.constant("meas inventory variance", 1200.0, "dmnl");
        builder.constant("inventory drive variance", 33.0, "dmnl");
        builder.constant("workforce drive variance", 1.3, "dmnl");

        // Variables
        builder.variable(new VariableDef("initial workforce", "The number of people working initially.", "INITIAL( des_workforce)", "person"));
        builder.variable(new VariableDef("net hire", "The net hire rate.", "(des_workforce - Workforce)/time_adjust_workforce + net_hire_noise*RANDOM_UNIFORM(-0.5,0.5,0)", "person/month"));
        builder.variable(new VariableDef("des workforce", "The desired number of people working.", "des_production / norm_productivity", "person"));
        builder.variable(new VariableDef("productivity", "The average productivity of workers.", "(norm_productivity+RANDOM_UNIFORM(-0.5,0.5,0)*productivity_noise)", "widget/person/month"));
        builder.variable(new VariableDef("des production", "The desired production level.", "Exp_Sales + inv_correction", "widget/month"));
        builder.variable(new VariableDef("inv correction", "The desired correction to the level of inventory held.", "(des_inventory - Inventory)/ time_correct_inventory", "widget/month"));
        builder.variable(new VariableDef("des inventory", "The desired amunt of stock to keep in inventory.", "Exp_Sales * inventory_coverage", "widget"));
        builder.variable(new VariableDef("production", "The rate of production.", "Workforce * productivity", "widget/month"));
        builder.variable(new VariableDef("meas inventory", "The error prone measured sales.", "Inventory * (1+RANDOM_UNIFORM(-0.5,0.5,0)*inventory_meas_noise)", "widget"));
        builder.variable(new VariableDef("meas workforce", "The error prone measured sales.", "Workforce * (1+RANDOM_UNIFORM(-0.5,0.5,0)*workforce_meas_noise)", "person"));

        // Flows
        builder.flow(new FlowDef("Workforce net flow", "Net flow for Workforce", "net_hire", "Month", null, "Workforce"));
        builder.flow(new FlowDef("Exp Sales net flow", "Net flow for Exp Sales", "(sales - Exp_Sales)/time_avg_sales", "Month", null, "Exp Sales"));
        builder.flow(new FlowDef("Inventory inflow 1", null, "production", "Month", null, "Inventory"));
        builder.flow(new FlowDef("Inventory outflow 2", null, "sales", "Month", "Inventory", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
