/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.samplesubmodel;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: advertising.mdl
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 */
public class VensimAdvertising {

    public static void main(String[] args) {
        new VensimAdvertising().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("advertising")
                .defaultSimulation("Month", 60.0, "Month");

        // Stocks
        builder.stock(new StockDef("Adv Budget Effective", "Adv Budget Effective", 0.0, "adv_budget", "$/ Month", null, List.of()));

        // Constants
        builder.constant("adv impact delay", 12.0, "Months");
        builder.constant("cash revenue", 70000.0, "$/ Month");
        builder.constant("normal lead gen effic", 7.0, "Orders / Products / Month");
        builder.constant("percent budget adv", 4.0, "Dimensionless");
        builder.constant("Products", 10.0, "Product");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("table for effect of adv", "table for effect of adv", new double[]{0.0, 40.0, 80.0, 120.0, 160.0, 200.0, 240.0, 280.0, 320.0, 360.0, 400.0}, new double[]{0.01, 0.2, 0.5, 0.7, 0.8, 1.0, 1.03, 1.06, 1.08, 1.09, 1.1}, "LINEAR", "Dimensionless"));

        // Variables
        builder.variable(new VariableDef("adv budget", "adv budget", "percent_budget_adv/100 * cash_revenue", "$/ Month"));
        builder.variable(new VariableDef("effect of advertising", "effect of advertising", "LOOKUP(table_for_effect_of_adv, Adv_Budget_Effective / Products)", "Dimensionless"));
        builder.variable(new VariableDef("pot order creation", "pot order creation", "normal_lead_gen_effic * Products * effect_of_advertising", "Orders / Month"));

        // Flows
        builder.flow(new FlowDef("Adv Budget Effective net flow", "Net flow for Adv Budget Effective", "( adv_budget - Adv_Budget_Effective ) / adv_impact_delay", "Month", null, "Adv Budget Effective"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
