/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.samplebpr;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: BPR2.mdl
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: TIME STEP</li>
 *   <li>View '1' places non-existent element: TIME STEP</li>
 *   <li>View '1' places non-existent element: TIME STEP</li>
 *   <li>View '1' places non-existent element: TIME STEP</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: TIME STEP</li>
 *   <li>View '1' connector references non-existent element: TIME STEP</li>
 *   <li>View '1' connector references non-existent element: TIME STEP</li>
 *   <li>View '1' connector references non-existent element: TIME STEP</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class VensimBpr2 {

    public static void main(String[] args) {
        new VensimBpr2().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("BPR2")
                .defaultSimulation("Day", 100.0, "Day", 0.5);

        // Stocks
        builder.stock(new StockDef("New Customers", "New Customers", 0.0, "Line", null));
        builder.stock(new StockDef("Awaiting Activation", "Awaiting Activation", 0.0, "(dispatching+testing*fraction_facilities_good)* target_activation_delay", "Line", null, List.of()));
        builder.stock(new StockDef("Orders in Process", "Orders in Process", 0.0, "orders*target_process_delay", "Line", null, List.of()));
        builder.stock(new StockDef("Orders Requiring Service", "Orders Requiring Service", 0.0, "(processing*(1-fraction_facilities_ready)+ testing*(1-fraction_facilities_good))* target_service_delay", "Line", null, List.of()));
        builder.stock(new StockDef("Orders Requiring Testing", "Orders Requiring Testing", 0.0, "(processing*fraction_facilities_ready)* target_test_delay", "Line", null, List.of()));

        // Constants
        builder.constant("activating capacity", 100.0, "Line/Day");
        builder.constant("target activation delay", 1.0, "Day");
        builder.constant("dispatching capacity", 44.0, "Line/Day");
        builder.constant("fraction facilities good", 0.8, "Dmnl");
        builder.constant("fraction facilities ready", 0.7, "Dmnl");
        builder.constant("start orders", 100.0, "Line/Day");
        builder.constant("target process delay", 1.0, "Day");
        builder.constant("target service delay", 3.0, "Day");
        builder.constant("target test delay", 1.0, "Day");
        builder.constant("processing capacity", 100.0, "Line/Day");
        builder.constant("testing capacity", 70.0, "Line/Day");

        // Variables
        builder.variable(new VariableDef("activating", "activating", "MIN(Awaiting_Activation/TIME_STEP,activating_capacity)", "Line/Day"));
        builder.variable(new VariableDef("dispatching", "dispatching", "MIN(dispatching_capacity,Orders_Requiring_Service/TIME_STEP)", "Line/Day"));
        builder.variable(new VariableDef("orders", "orders", "start_orders *(1+STEP(0.1,10))", "Line/Day"));
        builder.variable(new VariableDef("processing", "processing", "MIN(Orders_in_Process/TIME_STEP,processing_capacity)", "Line/Day"));
        builder.variable(new VariableDef("testing", "testing", "MIN(Orders_Requiring_Testing/TIME_STEP,testing_capacity)", "Line/Day"));

        // Flows
        builder.flow(new FlowDef("New Customers net flow", "Net flow for New Customers", "activating", "Day", null, "New Customers"));
        builder.flow(new FlowDef("Awaiting Activation inflow 1", null, "dispatching", "Day", null, "Awaiting Activation"));
        builder.flow(new FlowDef("Awaiting Activation inflow 2", null, "testing*fraction_facilities_good", "Day", null, "Awaiting Activation"));
        builder.flow(new FlowDef("Awaiting Activation outflow 3", null, "activating", "Day", "Awaiting Activation", null));
        builder.flow(new FlowDef("Orders in Process inflow 1", null, "orders", "Day", null, "Orders in Process"));
        builder.flow(new FlowDef("Orders in Process outflow 2", null, "processing", "Day", "Orders in Process", null));
        builder.flow(new FlowDef("Orders Requiring Service inflow 1", null, "processing*(1-fraction_facilities_ready)", "Day", null, "Orders Requiring Service"));
        builder.flow(new FlowDef("Orders Requiring Service inflow 2", null, "testing*(1-fraction_facilities_good)", "Day", null, "Orders Requiring Service"));
        builder.flow(new FlowDef("Orders Requiring Service outflow 3", null, "dispatching", "Day", "Orders Requiring Service", null));
        builder.flow(new FlowDef("Orders Requiring Testing inflow 1", null, "processing*fraction_facilities_ready", "Day", null, "Orders Requiring Testing"));
        builder.flow(new FlowDef("Orders Requiring Testing outflow 2", null, "testing", "Day", "Orders Requiring Testing", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
