/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.supplychain;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: CUST3.MDL
 * Source: Vensim User's Guide
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'Customers' places non-existent element: _524</li>
 *   <li>View 'Customers' connector references non-existent element: _524</li>
 *   <li>View 'Customers' connector references non-existent element: _524</li>
 *   <li>View 'Customers' connector references non-existent element: _524</li>
 *   <li>View 'Customers' flow route references non-existent flow: _524</li>
 *   <li>View 'Capacity' places non-existent element: _48</li>
 *   <li>View 'Capacity' places non-existent element: _48</li>
 *   <li>View 'Capacity' connector references non-existent element: _48</li>
 *   <li>View 'Capacity' connector references non-existent element: _48</li>
 *   <li>View 'Capacity' connector references non-existent element: _48</li>
 *   <li>View 'Capacity' connector references non-existent element: _48</li>
 *   <li>View 'Capacity' connector references non-existent element: 11</li>
 *   <li>View 'Capacity' connector references non-existent element: _48</li>
 *   <li>View 'Capacity' connector references non-existent element: 8</li>
 *   <li>View 'Capacity' connector references non-existent element: _48</li>
 *   <li>View 'Capacity' flow route references non-existent flow: _48</li>
 *   <li>View 'Capacity' flow route references non-existent flow: _48</li>
 *   <li>View 'Sales Revenue' places non-existent element: _48</li>
 *   <li>View 'Sales Revenue' connector references non-existent element: 13</li>
 *   <li>View 'Sales Revenue' connector references non-existent element: 19</li>
 *   <li>View 'Sales Revenue' connector references non-existent element: 19</li>
 *   <li>View 'Sales Revenue' connector references non-existent element: 18</li>
 *   <li>View 'Sales Revenue' connector references non-existent element: 18</li>
 *   <li>View 'Sales Revenue' connector references non-existent element: 15</li>
 *   <li>View 'Sales Revenue' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class Cust3 {

    public static void main(String[] args) {
        new Cust3().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("CUST3")
                .defaultSimulation("Month", 100.0, "Month");

        // Stocks
        builder.stock(new StockDef("Capacity", "Capacity", 0.0, "target_capacity", "Gadget/Month", null, List.of()));
        builder.stock(new StockDef("Cumulative Revenue", "Cumulative Revenue", 0.0, "dollar", null));
        builder.stock(new StockDef("Customers", "Customers", 1000.0, "person", null));
        builder.stock(new StockDef("Potential Customers", "Potential Customers", 1000000.0, "person", null));

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");
        builder.constant("capacity life", 20.0, "Month");
        builder.constant("price", 50.0, "dollar/Widget");
        builder.constant("fruitfulness", 0.01, "person/contact");
        builder.constant("sociability", 20.0, "contact/person/Month");
        builder.constant("time to adjust capacity", 12.0, "Month");
        builder.constant("widgets per person", 1.0, "Widget/person");

        // Variables
        builder.variable(new VariableDef("capacity adjustment", "capacity adjustment", "(target_capacity - Capacity)/time_to_adjust_capacity", "Gadget/Month/Month"));
        builder.variable(new VariableDef("production", "production", "MIN(desired_production,potential_production)", "Gadget/Month"));
        builder.variable(new VariableDef("reductions", "reductions", "Capacity/capacity_life", "Gadget/(Month*Month)"));
        builder.variable(new VariableDef("investment", "investment", "capacity_adjustment", "Gadget/Month/Month"));
        builder.variable(new VariableDef("desired production", "desired production", "target_capacity", "Gadget/Month"));
        builder.variable(new VariableDef("potential production", "potential production", "Capacity", "Gadget/Month"));
        builder.variable(new VariableDef("sales", "sales", "new_customers * widgets_per_person", "Widget/Month"));
        builder.variable(new VariableDef("sales revenue", "sales revenue", "sales * price", "dollar/Month"));
        builder.variable(new VariableDef("new customers", "new customers", "MIN(word_of_mouth_demand, Capacity/widgets_per_person)", "person/Month"));
        builder.variable(new VariableDef("contacts of noncustomers with customers", "contacts of noncustomers with customers", "contacts_with_customers*potential_customer_concentration", "contact/Month"));
        builder.variable(new VariableDef("contacts with customers", "contacts with customers", "Customers*sociability", "contact/Month"));
        builder.variable(new VariableDef("potential customer concentration", "potential customer concentration", "Potential_Customers/total_market", "dmnl"));
        builder.variable(new VariableDef("target capacity", "target capacity", "word_of_mouth_demand*widgets_per_person", "Widget/Month"));
        builder.variable(new VariableDef("total market", "total market", "Customers+Potential_Customers", "person"));
        builder.variable(new VariableDef("word of mouth demand", "word of mouth demand", "contacts_of_noncustomers_with_customers*fruitfulness", "person/Month"));

        // Flows
        builder.flow(new FlowDef("Capacity inflow 1", null, "investment", "Month", null, "Capacity"));
        builder.flow(new FlowDef("Capacity outflow 2", null, "reductions", "Month", "Capacity", null));
        builder.flow(new FlowDef("Cumulative Revenue net flow", "Net flow for Cumulative Revenue", "sales_revenue", "Month", null, "Cumulative Revenue"));
        builder.flow(new FlowDef("Customers net flow", "Net flow for Customers", "new_customers", "Month", null, "Customers"));
        builder.flow(new FlowDef("Potential Customers net flow", "Net flow for Potential Customers", "- new_customers", "Month", null, "Potential Customers"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim User's Guide")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
