/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.supplychain;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: 1402_SCM.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' places non-existent element: _460</li>
 *   <li>View '1' places non-existent element: _444</li>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' places non-existent element: _188</li>
 *   <li>View '1' places non-existent element: _172</li>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' places non-existent element: _140</li>
 *   <li>View '1' places non-existent element: _396</li>
 *   <li>View '1' places non-existent element: WithWithoutProductionPolicy</li>
 *   <li>View '1' connector references non-existent element: _460</li>
 *   <li>View '1' connector references non-existent element: _460</li>
 *   <li>View '1' connector references non-existent element: 4</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: 6</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _444</li>
 *   <li>View '1' connector references non-existent element: 2</li>
 *   <li>View '1' connector references non-existent element: _444</li>
 *   <li>View '1' connector references non-existent element: _188</li>
 *   <li>View '1' connector references non-existent element: _188</li>
 *   <li>View '1' connector references non-existent element: 44</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: 46</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _172</li>
 *   <li>View '1' connector references non-existent element: 42</li>
 *   <li>View '1' connector references non-existent element: _172</li>
 *   <li>View '1' connector references non-existent element: _140</li>
 *   <li>View '1' connector references non-existent element: _140</li>
 *   <li>View '1' connector references non-existent element: 84</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: 86</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _396</li>
 *   <li>View '1' connector references non-existent element: 82</li>
 *   <li>View '1' connector references non-existent element: _396</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _460</li>
 *   <li>View '1' connector references non-existent element: WithWithoutProductionPolicy</li>
 *   <li>View '1' connector references non-existent element: WithWithoutProductionPolicy</li>
 *   <li>View '1' connector references non-existent element: WithWithoutProductionPolicy</li>
 *   <li>View '1' connector references non-existent element: _140</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View '1' flow route references non-existent flow: _460</li>
 *   <li>View '1' flow route references non-existent flow: _444</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View '1' flow route references non-existent flow: _188</li>
 *   <li>View '1' flow route references non-existent flow: _172</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View '1' flow route references non-existent flow: _140</li>
 *   <li>View '1' flow route references non-existent flow: _396</li>
 * </ul>
 */
public class SupplyChainManagement {

    public static void main(String[] args) {
        new SupplyChainManagement().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1402_SCM")
                .defaultSimulation("Month", 100.0, "Month", 0.125);

        // Stocks
        builder.stock(new StockDef("Inventory Supplier T2", "\"Inventory Supplier (T2)\"", 300.0, "Sofa", null));
        builder.stock(new StockDef("Workforce Supplier T2", "\"Workforce Supplier (T2)\"", 0.0, "target_workforce_Supplier_T2", "Person", null, List.of()));
        builder.stock(new StockDef("Inventory Supplier T1", "\"Inventory Supplier (T1)\"", 300.0, "Sofa", null));
        builder.stock(new StockDef("Workforce Supplier T1", "\"Workforce Supplier (T1)\"", 0.0, "target_workforce_Supplier_T1", "Person", null, List.of()));
        builder.stock(new StockDef("Inventory", "Inventory", 300.0, "Sofa", null));
        builder.stock(new StockDef("Workforce", "Workforce", 0.0, "target_workforce", "Person", null, List.of()));

        // Constants
        builder.constant("TIME_STEP", 0.125, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");
        builder.constant("time to correct inventory Supplier T2", 2.0, "Month");
        builder.constant("time to adjust workforce Supplier T2", 10.0, "Month");
        builder.constant("inventory coverage Supplier T2", 3.0, "Month");
        builder.constant("productivity Supplier T2", 1.0, "Sofa/Month/Person");
        builder.constant("WithWithoutSCMPolicy", 0.0, "Dmnl");
        builder.constant("productivity Supplier T1", 1.0, "Sofa/Month/Person");
        builder.constant("inventory coverage Supplier T1", 3.0, "Month");
        builder.constant("time to correct inventory Supplier T1", 2.0, "Month");
        builder.constant("time to adjust workforce Supplier T1", 10.0, "Month");
        builder.constant("inventory coverage", 3.0, "Month");
        builder.constant("time to correct inventory", 2.0, "Month");
        builder.constant("productivity", 1.0, "Sofa/Month/Person");
        builder.constant("time to adjust workforce", 10.0, "Month");

        // Variables
        builder.variable(new VariableDef("production Supplier T2", "\"production Supplier (T2)\"", "Workforce_Supplier_T2*productivity_Supplier_T2", "Sofa/Month"));
        builder.variable(new VariableDef("production", "production", "Workforce*productivity", "Sofa/Month"));
        builder.variable(new VariableDef("production Supplier T1", "\"production Supplier (T1)\"", "Workforce_Supplier_T1*productivity_Supplier_T1", "Sofa/Month"));
        builder.variable(new VariableDef("sales Supplier T2", "\"sales Supplier (T2)\"", "(1-WithWithoutSCMPolicy) * production_Supplier_T1 + WithWithoutSCMPolicy * sales_Supplier_T1", "Sofa/Month"));
        builder.variable(new VariableDef("net hire rate Supplier T2", "\"net hire rate Supplier (T2)\"", "(target_workforce_Supplier_T2-Workforce_Supplier_T2 )/time_to_adjust_workforce_Supplier_T2", "Person/Month"));
        builder.variable(new VariableDef("target inventory Supplier T2", "\"target inventory Supplier (T2)\"", "sales_Supplier_T2 * inventory_coverage_Supplier_T2", "Sofa"));
        builder.variable(new VariableDef("inventory correction Supplier T2", "\"inventory correction Supplier (T2)\"", "(target_inventory_Supplier_T2 - Inventory_Supplier_T2 )/ time_to_correct_inventory_Supplier_T2", "Sofa/Month"));
        builder.variable(new VariableDef("target production Supplier T2", "\"target production Supplier (T2)\"", "sales_Supplier_T2 + inventory_correction_Supplier_T2", "Sofa/Month"));
        builder.variable(new VariableDef("sales Supplier T1", "\"sales Supplier (T1)\"", "(1-WithWithoutSCMPolicy) * production + WithWithoutSCMPolicy * sales", "Sofa/Month"));
        builder.variable(new VariableDef("target workforce Supplier T2", "\"target workforce Supplier (T2)\"", "target_production_Supplier_T2/productivity_Supplier_T2", "Person"));
        builder.variable(new VariableDef("target workforce Supplier T1", "\"target workforce Supplier (T1)\"", "target_production_Supplier_T1/productivity_Supplier_T1", "Person"));
        builder.variable(new VariableDef("net hire rate Supplier T1", "\"net hire rate Supplier (T1)\"", "(target_workforce_Supplier_T1-Workforce_Supplier_T1 )/time_to_adjust_workforce_Supplier_T1", "Person/Month"));
        builder.variable(new VariableDef("inventory correction Supplier T1", "\"inventory correction Supplier (T1)\"", "(target_inventory_Supplier_T1 - Inventory_Supplier_T1 )/ time_to_correct_inventory_Supplier_T1", "Sofa/Month"));
        builder.variable(new VariableDef("target inventory Supplier T1", "\"target inventory Supplier (T1)\"", "sales_Supplier_T1 * inventory_coverage_Supplier_T1", "Sofa"));
        builder.variable(new VariableDef("target production Supplier T1", "\"target production Supplier (T1)\"", "sales_Supplier_T1 + inventory_correction_Supplier_T1", "Sofa/Month"));
        builder.variable(new VariableDef("target inventory", "target inventory", "sales * inventory_coverage", "Sofa"));
        builder.variable(new VariableDef("target production", "target production", "sales + inventory_correction", "Sofa/Month"));
        builder.variable(new VariableDef("inventory correction", "inventory correction", "(target_inventory - Inventory)/ time_to_correct_inventory", "Sofa/Month"));
        builder.variable(new VariableDef("net hire rate", "net hire rate", "(target_workforce-Workforce)/time_to_adjust_workforce", "Person/Month"));
        builder.variable(new VariableDef("sales", "sales", "100+STEP(50,20)", "Sofa/Month"));
        builder.variable(new VariableDef("target workforce", "target workforce", "target_production/productivity", "Person"));

        // Flows
        builder.flow(new FlowDef("Inventory Supplier T2 inflow 1", null, "production_Supplier_T2", "Month", null, "Inventory Supplier T2"));
        builder.flow(new FlowDef("Inventory Supplier T2 outflow 2", null, "sales_Supplier_T2", "Month", "Inventory Supplier T2", null));
        builder.flow(new FlowDef("Workforce Supplier T2 net flow", "Net flow for \"Workforce Supplier (T2)\"", "net_hire_rate_Supplier_T2", "Month", null, "Workforce Supplier T2"));
        builder.flow(new FlowDef("Inventory Supplier T1 inflow 1", null, "production_Supplier_T1", "Month", null, "Inventory Supplier T1"));
        builder.flow(new FlowDef("Inventory Supplier T1 outflow 2", null, "sales_Supplier_T1", "Month", "Inventory Supplier T1", null));
        builder.flow(new FlowDef("Workforce Supplier T1 net flow", "Net flow for \"Workforce Supplier (T1)\"", "net_hire_rate_Supplier_T1", "Month", null, "Workforce Supplier T1"));
        builder.flow(new FlowDef("Inventory inflow 1", null, "production", "Month", null, "Inventory"));
        builder.flow(new FlowDef("Inventory outflow 2", null, "sales", "Month", "Inventory", null));
        builder.flow(new FlowDef("Workforce net flow", "Net flow for Workforce", "net_hire_rate", "Month", null, "Workforce"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
