/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.demographics;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 0607UnintendedFamilyPlanningBenefits.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _444</li>
 *   <li>View 'View 1' places non-existent element: _684</li>
 *   <li>View 'View 1' places non-existent element: _620</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _300</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 7</li>
 *   <li>View 'View 1' connector references non-existent element: 7</li>
 *   <li>View 'View 1' connector references non-existent element: 11</li>
 *   <li>View 'View 1' connector references non-existent element: 11</li>
 *   <li>View 'View 1' connector references non-existent element: 15</li>
 *   <li>View 'View 1' connector references non-existent element: 15</li>
 *   <li>View 'View 1' connector references non-existent element: _444</li>
 *   <li>View 'View 1' connector references non-existent element: _684</li>
 *   <li>View 'View 1' connector references non-existent element: _620</li>
 *   <li>View 'View 1' connector references non-existent element: 26</li>
 *   <li>View 'View 1' connector references non-existent element: 23</li>
 *   <li>View 'View 1' connector references non-existent element: 26</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 37</li>
 *   <li>View 'View 1' connector references non-existent element: 37</li>
 *   <li>View 'View 1' connector references non-existent element: 42</li>
 *   <li>View 'View 1' connector references non-existent element: 42</li>
 *   <li>View 'View 1' connector references non-existent element: 39</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 64</li>
 *   <li>View 'View 1' connector references non-existent element: 61</li>
 *   <li>View 'View 1' connector references non-existent element: 64</li>
 *   <li>View 'View 1' flow route references non-existent flow: _444</li>
 *   <li>View 'View 1' flow route references non-existent flow: _684</li>
 *   <li>View 'View 1' flow route references non-existent flow: _620</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _300</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class FamilyPlanning {

    public static void main(String[] args) {
        new FamilyPlanning().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0607UnintendedFamilyPlanningBenefits")
                .defaultSimulation("Year", 50.0, "Year", 0.125);

        // Stocks
        builder.stock(new StockDef("adults", "adults", 3000000.0, "", null));
        builder.stock(new StockDef("kids", "kids", 1000000.0, "", null));
        builder.stock(new StockDef("unborns", "unborns", 68000.0, "", null));
        builder.stock(new StockDef("retirees", "retirees", 750000.0, "", null));
        builder.stock(new StockDef("youngsters", "youngsters", 1000000.0, "", null));

        // Constants
        builder.constant("TIME_STEP", 0.125, "Year");
        builder.constant("INITIAL_TIME", 0.0, "Year");
        builder.constant("FINAL_TIME", 50.0, "Year");
        builder.constant("percentage of youngsters with criminal behavior", 0.5, "");
        builder.constant("crimes by others", 2.6E7, "");
        builder.constant("ciminal acts per criminal kid", 2.0, "");
        builder.constant("ciminal acts per criminal youngster", 4.0, "");
        builder.constant("annual fertility rate adults", 0.03, "");
        builder.constant("annual fertility rate youngsters", 0.001, "");
        builder.constant("average time as adult", 40.0, "");
        builder.constant("average time as kid", 12.0, "");
        builder.constant("average time as retirees", 15.0, "");
        builder.constant("average time as youngster", 12.0, "");
        builder.constant("average time pregnancy", 0.75, "");
        builder.constant("percentage early ended pregnancies", 0.75, "");
        builder.constant("criminal acts per criminal adult", 12.0, "");
        builder.constant("criminal acts per criminal retiree", 4.0, "");
        builder.constant("ini youngsters", 1000000.0, "");
        builder.constant("ini adults", 3000000.0, "");
        builder.constant("ini kids", 1000000.0, "");
        builder.constant("percentage of adults with criminal behavior", 0.6, "");
        builder.constant("percentage of retirees with criminal behavior", 0.1, "");
        builder.constant("percentage of kids and youngsters with criminal behavior", 0.05, "");
        builder.constant("ini unborns", 68000.0, "");
        builder.constant("ini retirees", 750000.0, "");

        // Variables
        builder.variable(new VariableDef("crimes", "crimes", "criminal_kids*ciminal_acts_per_criminal_kid + ciminal_acts_per_criminal_youngster*criminal_youngsters + criminal_acts_per_criminal_adult *criminal_adults + criminal_acts_per_criminal_retiree *criminal_retirees + crimes_by_others", ""));
        builder.variable(new VariableDef("criminal kids", "criminal kids", "kids*percentage_of_kids_and_youngsters_with_criminal_behavior", ""));
        builder.variable(new VariableDef("criminal youngsters", "criminal youngsters", "youngsters*percentage_of_youngsters_with_criminal_behavior", ""));
        builder.variable(new VariableDef("births", "births", "(1-percentage_early_ended_pregnancies) * unborns/average_time_pregnancy", ""));
        builder.variable(new VariableDef("criminal adults", "criminal adults", "adults*percentage_of_adults_with_criminal_behavior", ""));
        builder.variable(new VariableDef("criminal retirees", "criminal retirees", "retirees*percentage_of_retirees_with_criminal_behavior", ""));
        builder.variable(new VariableDef("total multiproblem family population", "\"total multi-problem family population\"", "adults+kids+retirees+youngsters", ""));
        builder.variable(new VariableDef("deaths", "deaths", "retirees/average_time_as_retirees", ""));
        builder.variable(new VariableDef("early ended pregnancies", "early ended pregnancies", "percentage_early_ended_pregnancies*unborns/average_time_pregnancy", ""));
        builder.variable(new VariableDef("from adults to retirees", "from adults to retirees", "adults/average_time_as_adult", ""));
        builder.variable(new VariableDef("from young adults to adults", "from young adults to adults", "youngsters/average_time_as_youngster", ""));
        builder.variable(new VariableDef("growing up", "growing up", "kids/average_time_as_kid", ""));
        builder.variable(new VariableDef("conceptions", "conceptions", "adults*annual_fertility_rate_adults + youngsters*annual_fertility_rate_youngsters", ""));

        // Flows
        builder.flow(new FlowDef("adults inflow 1", null, "from_young_adults_to_adults", "Year", null, "adults"));
        builder.flow(new FlowDef("adults outflow 2", null, "from_adults_to_retirees", "Year", "adults", null));
        builder.flow(new FlowDef("kids inflow 1", null, "births", "Year", null, "kids"));
        builder.flow(new FlowDef("kids outflow 2", null, "growing_up", "Year", "kids", null));
        builder.flow(new FlowDef("unborns inflow 1", null, "conceptions", "Year", null, "unborns"));
        builder.flow(new FlowDef("unborns outflow 2", null, "births", "Year", "unborns", null));
        builder.flow(new FlowDef("unborns outflow 3", null, "early_ended_pregnancies", "Year", "unborns", null));
        builder.flow(new FlowDef("retirees inflow 1", null, "from_adults_to_retirees", "Year", null, "retirees"));
        builder.flow(new FlowDef("retirees outflow 2", null, "deaths", "Year", "retirees", null));
        builder.flow(new FlowDef("youngsters inflow 1", null, "growing_up", "Year", null, "youngsters"));
        builder.flow(new FlowDef("youngsters outflow 2", null, "from_young_adults_to_adults", "Year", "youngsters", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
