/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.userguidechap17;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: PROJ1.MDL
 * License: MIT
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _236</li>
 *   <li>View 'View 1' connector references non-existent element: _236</li>
 *   <li>View 'View 1' connector references non-existent element: _236</li>
 *   <li>View 'View 1' connector references non-existent element: _236</li>
 *   <li>View 'View 1' flow route references non-existent flow: _236</li>
 * </ul>
 */
public class VensimProj1 {

    public static void main(String[] args) {
        new VensimProj1().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("PROJ1")
                .defaultSimulation("Month", 100.0, "Month", 0.125);

        // Stocks
        builder.stock(new StockDef("Work Done", "Work Done", 0.0, "Drawing", null));
        builder.stock(new StockDef("Work To Do", "Work To Do", 180.0, "Drawing", null));

        // Constants
        builder.constant("max work accomplishment", 8.0, "Drawing/Month");
        builder.constant("task size", 180.0, "Drawing");

        // Variables
        builder.variable(new VariableDef("work accomplishment", "work accomplishment", "max_work_accomplishment * task_is_active", "Drawing/Month"));
        builder.variable(new VariableDef("task is active", "task is active", "IF( Work_Done < task_size, 1, 0)", "Dmnl"));

        // Flows
        builder.flow(new FlowDef("Work Done net flow", "Net flow for Work Done", "work_accomplishment", "Month", null, "Work Done"));
        builder.flow(new FlowDef("Work To Do net flow", "Net flow for Work To Do", "- work_accomplishment", "Month", null, "Work To Do"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
