/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.sampleextra;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: EPIDEMIC.MDL
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class VensimEpidemic {

    public static void main(String[] args) {
        new VensimEpidemic().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("EPIDEMIC")
                .defaultSimulation("Day", 50.0, "Day");

        // Stocks
        builder.stock(new StockDef("Infected Population", "Infected Population", 10.0, "Person", null));
        builder.stock(new StockDef("Susceptible Population", "Susceptible Population", 1000000.0, "Person", null));

        // Constants
        builder.constant("rate that people contact other people", 5.0, "1/day");
        builder.constant("fraction infected from contact", 0.1, "Dmnl");
        builder.constant("initial infected", 10.0, "Person");
        builder.constant("initial susceptible", 1000000.0, "Person");

        // Variables
        builder.variable(new VariableDef("contacts between infected and unaffected", "contacts between infected and unaffected", "rate_of_potential_infectious_contacts  * fraction_of_population_infected", "Person/day"));
        builder.variable(new VariableDef("total population", "total population", "Susceptible_Population + Infected_Population", "Person"));
        builder.variable(new VariableDef("fraction of population infected", "fraction of population infected", "Infected_Population / total_population", "Dmnl"));
        builder.variable(new VariableDef("infections", "infections", "contacts_between_infected_and_unaffected  * fraction_infected_from_contact", "Person/day"));
        builder.variable(new VariableDef("rate of potential infectious contacts", "rate of potential infectious contacts", "Susceptible_Population  * rate_that_people_contact_other_people", "Person/day"));

        // Flows
        builder.flow(new FlowDef("Infected Population net flow", "Net flow for Infected Population", "infections", "Day", null, "Infected Population"));
        builder.flow(new FlowDef("Susceptible Population net flow", "Net flow for Susceptible Population", "- infections", "Day", null, "Susceptible Population"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
