/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.sampleextra;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: BALL.MDL
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Non-numeric TIME STEP value: 'IF THEN ELSE(could be position &lt;= ball diameter , little time step,big time step)', defaulting to 1.0</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: TIME STEP</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: TIME STEP</li>
 *   <li>View 'View 1' connector references non-existent element: TIME STEP</li>
 *   <li>View 'View 1' connector references non-existent element: TIME STEP</li>
 *   <li>View 'View 1' connector references non-existent element: TIME STEP</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class VensimBall {

    public static void main(String[] args) {
        new VensimBall().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("BALL")
                .defaultSimulation("Second", 20.0, "Second");

        // Stocks
        builder.stock(new StockDef("Position", "Position", 30.0, "Feet", null));
        builder.stock(new StockDef("Velocity", "Velocity", 0.0, "Feet/Second", null));

        // Constants
        builder.constant("ball diameter", 0.25, "Feet");
        builder.constant("big time step", 0.0625, "Second");
        builder.constant("g", -32.0, "Feet/(Second*Second)");
        builder.constant("little time step", 4.88281E-4, "Second");
        builder.constant("stiffness constant", 200000.0, "1/Second/Second");

        // Variables
        builder.variable(new VariableDef("acceleration", "acceleration", "g + compression_acceleration", "Feet/Second/Second"));
        builder.variable(new VariableDef("compression acceleration", "compression acceleration", "IF(Position <= ball_diameter, (ball_diameter-Position)*stiffness_constant,0)", "Feet/Second/Second"));
        builder.variable(new VariableDef("could be position", "could be position", "IF(Velocity>0,Position, Position+Velocity*big_time_step)", "Feet"));

        // Flows
        builder.flow(new FlowDef("Position net flow", "Net flow for Position", "Velocity", "Second", null, "Position"));
        builder.flow(new FlowDef("Velocity net flow", "Net flow for Velocity", "acceleration", "Second", null, "Velocity"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
