/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.marketing;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: Products.mdl
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'Products' places non-existent element: _0</li>
 *   <li>View 'Products' places non-existent element: _0</li>
 *   <li>View 'Products' connector references non-existent element: _0</li>
 *   <li>View 'Products' connector references non-existent element: _0</li>
 *   <li>View 'Products' connector references non-existent element: _0</li>
 *   <li>View 'Products' connector references non-existent element: 8</li>
 *   <li>View 'Products' connector references non-existent element: _0</li>
 *   <li>View 'Products' connector references non-existent element: 9</li>
 *   <li>View 'Products' connector references non-existent element: _0</li>
 *   <li>View 'Products' flow route references non-existent flow: _0</li>
 *   <li>View 'Products' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class Products {

    public static void main(String[] args) {
        new Products().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("Products")
                .defaultSimulation("Month", 60.0, "Month");

        // Stocks
        builder.stock(new StockDef("prod gen rate", "prod gen rate", 0.0, "prod_dev_efficiency * prod_dev_budget", "Product / Month", null, List.of()));
        builder.stock(new StockDef("Products", "Products", 10.0, "Product", null));

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 60.0, "Month");
        builder.constant("cash revenue", 70000.0, "$/ Month");
        builder.constant("frac budget r and d", 0.15, "Dimensionless");
        builder.constant("prod dev efficiency", 3.0E-5, "Product / $");
        builder.constant("prod dev time", 12.0, "Month");
        builder.constant("prod obs time", 60.0, "Months");

        // Variables
        builder.variable(new VariableDef("prod dev budget", "prod dev budget", "cash_revenue * frac_budget_r_and_d", "$/ Month"));
        builder.variable(new VariableDef("prod obsolescence rate", "prod obsolescence rate", "Products / prod_obs_time", "Product / Month"));

        // Flows
        builder.flow(new FlowDef("prod gen rate net flow", "Net flow for prod gen rate", "( prod_dev_efficiency * prod_dev_budget - prod_gen_rate ) / prod_dev_time", "Month", null, "prod gen rate"));
        builder.flow(new FlowDef("Products inflow 1", null, "prod_gen_rate", "Month", null, "Products"));
        builder.flow(new FlowDef("Products outflow 2", null, "prod_obsolescence_rate", "Month", "Products", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
