/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.samplevenapp;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: change.mdl
 * License: MIT
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: FINAL TIME</li>
 *   <li>View 'View 1' places non-existent element: Time</li>
 *   <li>View 'View 1' places non-existent element: TIME STEP</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: FINAL TIME</li>
 *   <li>View 'View 1' connector references non-existent element: Time</li>
 *   <li>View 'View 1' connector references non-existent element: TIME STEP</li>
 *   <li>View 'View 1' connector references non-existent element: TIME STEP</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class VensimChange {

    public static void main(String[] args) {
        new VensimChange().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("change")
                .defaultSimulation("Month", 100.0, "Month");

        // Stocks
        builder.stock(new StockDef("adjusted", "adjusted", 0.0, "DMnl", null));
        builder.stock(new StockDef("stock", "stock", 100.0, "$", null));

        // Constants
        builder.constant("adjust amount", 230.0, "$");
        builder.constant("init stock", 100.0, "$");
        builder.constant("norm inflow", 100.0, "$/Month");
        builder.constant("outflow time", 20.0, "Month");
        builder.constant("target stock", 50.0, "$");

        // Variables
        builder.variable(new VariableDef("adjust", "adjust", "IF(TIME >= adjust_time  and  not(adjusted),adjust_amount/TIME_STEP,0)", "$/Month"));
        builder.variable(new VariableDef("adjust time", "adjust time", "FINAL_TIME", "Month"));
        builder.variable(new VariableDef("inflow", "inflow", "norm_inflow * (1-STEP(1,10))", "$/Month"));
        builder.variable(new VariableDef("msg", "msg", "SAMPLE_IF_TRUE( not(msg), IF(not(msg)and  stock < target_stock,0,0),0)", "DMnl"));
        builder.variable(new VariableDef("outflow", "outflow", "stock/outflow_time", "$/Month"));

        // Flows
        builder.flow(new FlowDef("adjusted net flow", "Net flow for adjusted", "IF(adjust != 0,1/TIME_STEP,0)", "Month", null, "adjusted"));
        builder.flow(new FlowDef("stock inflow 1", null, "adjust", "Month", null, "stock"));
        builder.flow(new FlowDef("stock inflow 2", null, "inflow", "Month", null, "stock"));
        builder.flow(new FlowDef("stock outflow 3", null, "outflow", "Month", "stock", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
