/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.samplevenapp;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;

/**
 * Imported from: flicker.mdl
 * License: MIT
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 */
public class VensimFlicker {

    public static void main(String[] args) {
        new VensimFlicker().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("flicker")
                .defaultSimulation("Month", 1000.0, "Month", 0.0078125);

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
