/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.ecology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 0603EcOvershootCollapseBasedOnEZ416Bossel.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 6</li>
 *   <li>View 'View 1' connector references non-existent element: 6</li>
 *   <li>View 'View 1' connector references non-existent element: 3</li>
 *   <li>View 'View 1' connector references non-existent element: 19</li>
 *   <li>View 'View 1' connector references non-existent element: 16</li>
 *   <li>View 'View 1' connector references non-existent element: 19</li>
 *   <li>View 'View 1' connector references non-existent element: 30</li>
 *   <li>View 'View 1' connector references non-existent element: 30</li>
 *   <li>View 'View 1' connector references non-existent element: 27</li>
 *   <li>View 'View 1' connector references non-existent element: 35</li>
 *   <li>View 'View 1' connector references non-existent element: 32</li>
 *   <li>View 'View 1' connector references non-existent element: 35</li>
 *   <li>View 'View 1' connector references non-existent element: 51</li>
 *   <li>View 'View 1' connector references non-existent element: 51</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class EcologicalOvershoot {

    public static void main(String[] args) {
        new EcologicalOvershoot().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0603EcOvershootCollapseBasedOnEZ416Bossel")
                .defaultSimulation("Year", 500.0, "Year", 0.02);

        // Stocks
        builder.stock(new StockDef("renewable resources", "renewable resources", 7000000.0, "resource", null));
        builder.stock(new StockDef("population", "population", 100000.0, "consumer", null));

        // Constants
        builder.constant("TIME_STEP", 0.02, "Year");
        builder.constant("INITIAL_TIME", 0.0, "Year");
        builder.constant("FINAL_TIME", 500.0, "Year");
        builder.constant("rapid resource depletion time", 1.0, "Year");
        builder.constant("INITIAL RESOURCES", 7000000.0, "resource");
        builder.constant("INITIAL CONSUMERS", 100000.0, "consumer");
        builder.constant("regeneration rate", 1.2, "1/Year");
        builder.constant("normal birth rate", 0.0035, "1/Year");
        builder.constant("minimum regeneration rate", 0.01, "1/Year");
        builder.constant("carrying capacity", 7500000.0, "resource");
        builder.constant("renewable resource consumption per capita", 1.0, "resource/(consumer*Year)");
        builder.constant("normal lifetime", 25.0, "1/Year");

        // Variables
        builder.variable(new VariableDef("deaths", "deaths", "population/resource_availability_dependent_lifetime", "consumer/Year"));
        builder.variable(new VariableDef("resource availability dependent lifetime", "MAX(MIN(normal lifetime*per capita renewable resource availability,100),20)", "MAX(15,MIN(100,normal_lifetime*per_capita_renewable_resource_availability))", ""));
        builder.variable(new VariableDef("resource use", "IF THEN ELSE(renewable resources/rapid resource depletion time < renewable  resource consumption per capita*population, renewable resources/rapid  resource depletion time, renewable resource consumption per  capita*population)", "MIN(renewable_resources/rapid_resource_depletion_time, renewable_resource_consumption_per_capita *population)", "resource/Year"));
        builder.variable(new VariableDef("regeneration", "regeneration", "regeneration_rate*renewable_resources*(renewable_resources/carrying_capacity)*(1-renewable_resources /carrying_capacity)+minimum_regeneration_rate*carrying_capacity", "resource/Year"));
        builder.variable(new VariableDef("per capita renewable resource availability", "per capita renewable resource availability", "renewable_resources/population", "resource/consumer"));
        builder.variable(new VariableDef("births", "births", "normal_birth_rate*population*per_capita_renewable_resource_availability", "consumer/Year"));

        // Flows
        builder.flow(new FlowDef("renewable resources inflow 1", null, "regeneration", "Year", null, "renewable resources"));
        builder.flow(new FlowDef("renewable resources outflow 2", null, "resource_use", "Year", "renewable resources", null));
        builder.flow(new FlowDef("population inflow 1", null, "births", "Year", null, "population"));
        builder.flow(new FlowDef("population outflow 2", null, "deaths", "Year", "population", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
