/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.ecology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 0605Feral Pigs SFD EN.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class FeralPigs {

    public static void main(String[] args) {
        new FeralPigs().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0605Feral Pigs SFD EN")
                .defaultSimulation("Year", 10.0, "Year", 0.125);

        // Stocks
        builder.stock(new StockDef("feral pigs", "feral pigs", 20000.0, "pig", null));

        // Constants
        builder.constant("licences granted per year", 10.0, "license/year");
        builder.constant("litter per sow", 4.0, "litter/pig/year");
        builder.constant("piglet per litter", 8.0, "pig/litter");
        builder.constant("traps per license", 10.0, "trap/license");

        // Variables
        builder.variable(new VariableDef("births", "births", "piglets", "pig/year"));
        builder.variable(new VariableDef("catch per trap", "catch per trap", "RANDOM_UNIFORM(0.15, 0.17, 0.1)", "1/trap"));
        builder.variable(new VariableDef("feral pig traps", "feral pig traps", "traps_per_license*licences_granted_per_year", "trap/year"));
        builder.variable(new VariableDef("litter", "litter", "sows*litter_per_sow", "litter/year"));
        builder.variable(new VariableDef("piglets", "piglets", "litter*piglet_per_litter", "pig/year"));
        builder.variable(new VariableDef("pigs removed", "pigs removed", "feral_pigs*catch_per_trap*feral_pig_traps", "pig/year"));
        builder.variable(new VariableDef("sows", "sows", "feral_pigs/2", "pig"));

        // Flows
        builder.flow(new FlowDef("feral pigs inflow 1", null, "births", "Year", null, "feral pigs"));
        builder.flow(new FlowDef("feral pigs outflow 2", null, "pigs_removed", "Year", "feral pigs", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
