/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.ecology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 0602Muskrats1.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class MuskratPlague {

    public static void main(String[] args) {
        new MuskratPlague().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0602Muskrats1")
                .defaultSimulation("Year", 10.0, "Year", 0.0625);

        // Stocks
        builder.stock(new StockDef("Muskrat population", "Muskrat population", 100.0, "Muskrats", null));

        // Constants
        builder.constant("Initial number of muskrats", 100.0, "Muskrats");
        builder.constant("Number of licenses", 10.0, "licenses/Year");
        builder.constant("New muskrats rate", 20.0, "1/Year");
        builder.constant("Proportionality factor", 0.195, "1/traps");
        builder.constant("Traps per license", 10.0, "traps/licenses");

        // Variables
        builder.variable(new VariableDef("Muskrats caught", "Muskrats caught", "Muskrats_caught_per_trap*Traps_per_license* Number_of_licenses", "Muskrats/Year"));
        builder.variable(new VariableDef("Muskrats caught per trap", "Muskrats caught per trap", "Muskrat_population * Proportionality_factor", "Muskrats/traps"));
        builder.variable(new VariableDef("New Muskrats", "New Muskrats", "New_muskrats_rate*Muskrat_population", "Muskrats/Year"));

        // Flows
        builder.flow(new FlowDef("Muskrat population inflow 1", null, "New_Muskrats", "Year", null, "Muskrat population"));
        builder.flow(new FlowDef("Muskrat population outflow 2", null, "Muskrats_caught", "Year", "Muskrat population", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
