/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.ecology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 1013Mass starvation Oostvaardersplassen.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 2</li>
 *   <li>View 'View 1' connector references non-existent element: 19</li>
 *   <li>View 'View 1' connector references non-existent element: 16</li>
 *   <li>View 'View 1' connector references non-existent element: 19</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class Oostvaardersplassen {

    public static void main(String[] args) {
        new Oostvaardersplassen().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1013Mass starvation Oostvaardersplassen")
                .defaultSimulation("Year", 65.0, "Year", 0.25);

        // Stocks
        builder.stock(new StockDef("large herbivores", "large herbivores", 75.0, "", null));

        // Constants
        builder.constant("TIME_STEP", 0.25, "Year");
        builder.constant("INITIAL_TIME", 1985.0, "Year");
        builder.constant("FINAL_TIME", 2050.0, "Year");
        builder.constant("length of death season", 0.25, "");
        builder.constant("length of the birth seaseon", 0.25, "");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("percentage_birth_rate_lookup", null, new double[]{0.0, 1000.0, 2000.0, 3000.0, 4000.0, 5000.0}, new double[]{0.5, 0.42, 0.36, 0.28, 0.2, 0.15}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("percentage_death_rates_lookup", null, new double[]{0.0, 1000.0, 2000.0, 3000.0, 4000.0, 5000.0, 6000.0}, new double[]{0.05, 0.08, 0.12, 0.2, 0.3, 0.45, 0.7}, "LINEAR"));

        // Variables
        builder.variable(new VariableDef("deaths", "deaths", "death_randomizer*death_season*large_herbivores*percentage_death_rates/length_of_death_season", ""));
        builder.variable(new VariableDef("birth randomizer", "birth randomizer", "RANDOM_NORMAL(0, 2, 1, 0.5, 2)", ""));
        builder.variable(new VariableDef("birth season", "birth season", "PULSE_TRAIN(1982.5, length_of_the_birth_seaseon ,1 , 2050 )", ""));
        builder.variable(new VariableDef("births", "births", "birth_randomizer*birth_season*large_herbivores*percentage_birth_rate/length_of_the_birth_seaseon", ""));
        builder.variable(new VariableDef("death randomizer", "death randomizer", "RANDOM_UNIFORM(0.5, 3, 3)", ""));
        builder.variable(new VariableDef("death season", "death season", "PULSE_TRAIN(1982.5, length_of_death_season , 1 , 2050)", ""));
        builder.variable(new VariableDef("percentage birth rate", "percentage birth rate", "LOOKUP(percentage_birth_rate_lookup, large_herbivores)", ""));
        builder.variable(new VariableDef("percentage death rates", "percentage death rates", "LOOKUP(percentage_death_rates_lookup, large_herbivores)", ""));
        builder.variable(new VariableDef("smoothed birth info", "smoothed birth info", "SMOOTH3(births, 1 )", ""));
        builder.variable(new VariableDef("smoothed info on nr of herbivores", "smoothed info on nr of herbivores", "SMOOTH3(large_herbivores, 1 )", ""));
        builder.variable(new VariableDef("smoothed nr of deaths", "\"smoothed nr. of deaths\"", "SMOOTH3(deaths, 1)", ""));

        // Flows
        builder.flow(new FlowDef("large herbivores inflow 1", null, "births", "Year", null, "large herbivores"));
        builder.flow(new FlowDef("large herbivores outflow 2", null, "deaths", "Year", "large herbivores", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
