/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.ecology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: RABFOX.MDL
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class VensimRabfox {

    public static void main(String[] args) {
        new VensimRabfox().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("RABFOX")
                .defaultSimulation("Year", 50.0, "Year", 0.25);

        // Stocks
        builder.stock(new StockDef("Fox Population", "Fox Population", 30.0, "Fox", null));
        builder.stock(new StockDef("Rabbit Population", "Rabbit Population", 500.0, "Rabbit", null));

        // Constants
        builder.constant("average fox life", 4.0, "Year");
        builder.constant("average rabbit life", 2.0, "Year");
        builder.constant("carrying capacity", 500.0, "Rabbit");
        builder.constant("fox birth rate", 0.25, "1/Year");
        builder.constant("fox food requirements", 25.0, "Rabbit/Year/Fox");
        builder.constant("initial fox population", 30.0, "Fox");
        builder.constant("initial rabbit population", 500.0, "Rabbit");
        builder.constant("rabbit birth rate", 2.0, "1/Year");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("effect of crowding on deaths lookup", "effect of crowding on deaths lookup", new double[]{0.0, 3.0, 6.0, 8.0, 10.0}, new double[]{0.75, 2.5, 6.0, 11.0, 20.0}, "LINEAR", "Dmnl"));
        builder.lookupTable(new LookupTableDef("fox mortality lookup", "fox mortality lookup", new double[]{0.0, 0.3, 0.5, 1.0, 2.0}, new double[]{20.0, 5.0, 2.0, 1.0, 0.5}, "LINEAR", "Dmnl"));
        builder.lookupTable(new LookupTableDef("fox rabbit consumption lookup", "Relating rabbits to foxes", new double[]{0.0, 1.0, 2.0, 6.0}, new double[]{0.0, 1.0, 2.0, 2.0}, "LINEAR", "Dmnl"));

        // Variables
        builder.variable(new VariableDef("fox births", "fox births", "Fox_Population * fox_birth_rate", "Fox/Year"));
        builder.variable(new VariableDef("fox deaths", "fox deaths", "Fox_Population / average_fox_life * LOOKUP(fox_mortality_lookup, fox_food_availability)", "Fox/Year"));
        builder.variable(new VariableDef("fox food availability", "A lookup table showing the relationship between the input (crowding) along the x \t\t\t\t\t\t\t\t\t\t\t\t\t\t axis and the\n\t\t         output\n\t\t         (the effect that crowding has on the death rate) along the y-axis.", "fox_consumption_of_rabbits/(Fox_Population * fox_food_requirements )", "Dmnl"));
        builder.variable(new VariableDef("fox consumption of rabbits", "fox consumption of rabbits", "Fox_Population * fox_food_requirements * LOOKUP(fox_rabbit_consumption_lookup, rabbit_crowding)", "Rabbit/Year"));
        builder.variable(new VariableDef("rabbit births", "rabbit births", "Rabbit_Population * rabbit_birth_rate", "Rabbit/Year"));
        builder.variable(new VariableDef("rabbit crowding", "rabbit crowding", "Rabbit_Population/carrying_capacity", "Dmnl"));
        builder.variable(new VariableDef("rabbit deaths", "rabbit deaths", "MAX(Rabbit_Population / average_rabbit_life * LOOKUP(effect_of_crowding_on_deaths_lookup, rabbit_crowding), fox_consumption_of_rabbits)", "Rabbit/Year"));

        // Flows
        builder.flow(new FlowDef("Fox Population inflow 1", null, "fox_births", "Year", null, "Fox Population"));
        builder.flow(new FlowDef("Fox Population outflow 2", null, "fox_deaths", "Year", "Fox Population", null));
        builder.flow(new FlowDef("Rabbit Population inflow 1", null, "rabbit_births", "Year", null, "Rabbit Population"));
        builder.flow(new FlowDef("Rabbit Population outflow 2", null, "rabbit_deaths", "Year", "Rabbit Population", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
