/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.ecology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: YEAST4.MDL
 * Source: Vensim User Guide Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' places non-existent element: TIME STEP</li>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: TIME STEP</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 2' places non-existent element: cold is dormant</li>
 *   <li>View 'View 2' places non-existent element: drink or die</li>
 *   <li>View 'View 2' places non-existent element: eat or die</li>
 *   <li>View 'View 2' places non-existent element: hot is dead</li>
 *   <li>View 'View 2' places non-existent element: hunger from growth</li>
 *   <li>View 'View 2' places non-existent element: thirst from growth</li>
 *   <li>View 'View 2' places non-existent element: big growth</li>
 *   <li>View 'View 2' places non-existent element: INITIAL TIME</li>
 *   <li>View 'View 2' connector references non-existent element: cold is dormant</li>
 *   <li>View 'View 2' connector references non-existent element: cold is dormant</li>
 *   <li>View 'View 2' connector references non-existent element: drink or die</li>
 *   <li>View 'View 2' connector references non-existent element: eat or die</li>
 *   <li>View 'View 2' connector references non-existent element: eat or die</li>
 *   <li>View 'View 2' connector references non-existent element: hot is dead</li>
 *   <li>View 'View 2' connector references non-existent element: hot is dead</li>
 *   <li>View 'View 2' connector references non-existent element: hunger from growth</li>
 *   <li>View 'View 2' connector references non-existent element: thirst from growth</li>
 *   <li>View 'View 2' connector references non-existent element: big growth</li>
 *   <li>View 'View 2' connector references non-existent element: drink or die</li>
 *   <li>View 'View 2' connector references non-existent element: INITIAL TIME</li>
 *   <li>View 'View 2' connector references non-existent element: hunger from growth</li>
 *   <li>View 'View 2' connector references non-existent element: INITIAL TIME</li>
 *   <li>View 'View 2' connector references non-existent element: thirst from growth</li>
 * </ul>
 */
public class VensimYeast4 {

    public static void main(String[] args) {
        new VensimYeast4().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("YEAST4")
                .defaultSimulation("Minute", 300.0, "Minute", 0.5);

        // Stocks
        builder.stock(new StockDef("Water", "The amount of water in the bowl.", 100.0, "ml", null));
        builder.stock(new StockDef("Sugar", "The amount of sugar in the bowl.", 100.0, "g", null));
        builder.stock(new StockDef("Yeast Count", "The number of yeast.", 100.0, "Cell", null));

        // Constants
        builder.constant("water per division", 0.001, "ml/Cell");
        builder.constant("sugar per division", 0.001, "g/Cell");
        builder.constant("norm water", 0.001, "ml/Cell");
        builder.constant("norm sugar", 0.001, "g/Cell");
        builder.constant("norm lifetime", 250.0, "Minute");
        builder.constant("norm temperature", 80.0, "degrees farenheit");
        builder.constant("norm division rate", 0.08, "1/Minute");
        builder.constant("temperature", 85.0, "degrees farenheit");
        builder.constant("RC START TIME", 10.0, "Minute");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("division from sugar lookup", "division from sugar lookup", new double[]{0.0, 1.0}, new double[]{0.0, 1.0}, "LINEAR", "Dmnl"));
        builder.lookupTable(new LookupTableDef("life from sugar lookup", "life from sugar lookup", new double[]{0.0, 1.0}, new double[]{0.001, 1.0}, "LINEAR", "Dmnl"));
        builder.lookupTable(new LookupTableDef("division from water lookup", "division from water lookup", new double[]{0.0, 1.0}, new double[]{0.0, 1.0}, "LINEAR", "Dmnl"));
        builder.lookupTable(new LookupTableDef("life from water lookup", "life from water lookup", new double[]{0.0, 1.0}, new double[]{0.001, 1.0}, "LINEAR", "Dmnl"));
        builder.lookupTable(new LookupTableDef("division from temp lookup", "division from temp lookup", new double[]{0.0, 0.8, 1.0, 2.0}, new double[]{0.0, 0.0, 1.0, 1.0}, "LINEAR", "Dmnl"));
        builder.lookupTable(new LookupTableDef("life from temp lookup", "life from temp lookup", new double[]{0.0, 1.0, 1.25, 2.0}, new double[]{1.0, 1.0, 0.02, 0.001}, "LINEAR", "Dmnl"));

        // Variables
        builder.variable(new VariableDef("water consumption", "water consumption", "divisions * water_per_division", "ml/Minute"));
        builder.variable(new VariableDef("sugar consumption", "sugar consumption", "divisions * sugar_per_division", "g/Minute"));
        builder.variable(new VariableDef("average water", "The average amount of water.  Note use of ZIDZ to prevent problems on 0 \t\t\t\t\t\t\t\t\t\t yeast count.", "IF((Yeast_Count) == 0, 0, (Water) / (Yeast_Count))", "ml/Cell"));
        builder.variable(new VariableDef("average lifetime", "The average length of time a yeast survives.", "norm_lifetime* LOOKUP(life_from_temp_lookup, temperature/norm_temperature) * LOOKUP(life_from_water_lookup, average_water/norm_water) * LOOKUP(life_from_sugar_lookup, average_sugar/norm_sugar)", "Minute"));
        builder.variable(new VariableDef("average sugar", "The average amount of sugar.  Note the use of ZIDZ to prevent problems \t\t\t\t\t\t\t\t\t\t when Yeast Count is 0.", "IF((Yeast_Count) == 0, 0, (Sugar) / (Yeast_Count))", "g/Cell"));
        builder.variable(new VariableDef("division rate", "The rate at which yeast divide.", "norm_division_rate * LOOKUP(division_from_temp_lookup, temperature/norm_temperature) * LOOKUP(division_from_sugar_lookup, average_sugar/norm_sugar) * LOOKUP(division_from_water_lookup, average_water/norm_water)", "1/Minute"));
        builder.variable(new VariableDef("divisions", "divisions", "Yeast_Count*division_rate", "Cell/Minute"));
        builder.variable(new VariableDef("terminations", "The rate of termination of yeast.  Using a MIN to prevent silly results on extreme \t\t\t\t\t\t\t\t\t\t conditions\n\t\t         integration.", "MIN(Yeast_Count/TIME_STEP,Yeast_Count/average_lifetime)", "Cell/Minute"));

        // Flows
        builder.flow(new FlowDef("Water net flow", "Net flow for Water", "- water_consumption", "Minute", null, "Water"));
        builder.flow(new FlowDef("Sugar net flow", "Net flow for Sugar", "-sugar_consumption", "Minute", null, "Sugar"));
        builder.flow(new FlowDef("Yeast Count inflow 1", null, "divisions", "Minute", null, "Yeast Count"));
        builder.flow(new FlowDef("Yeast Count outflow 2", null, "terminations", "Minute", "Yeast Count", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim User Guide Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
