/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.sample;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: INTRO.mdl
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'Whole Model' places non-existent element: _48</li>
 *   <li>View 'Whole Model' places non-existent element: _48</li>
 *   <li>View 'Whole Model' places non-existent element: Time</li>
 *   <li>View 'Whole Model' connector references non-existent element: _48</li>
 *   <li>View 'Whole Model' connector references non-existent element: _48</li>
 *   <li>View 'Whole Model' connector references non-existent element: Time</li>
 *   <li>View 'Whole Model' connector references non-existent element: _48</li>
 *   <li>View 'Whole Model' flow route references non-existent flow: _48</li>
 *   <li>View 'Whole Model' flow route references non-existent flow: _48</li>
 *   <li>View 'Reinforcing Loop' places non-existent element: Time</li>
 *   <li>View 'Reinforcing Loop' connector references non-existent element: Time</li>
 *   <li>View 'Workforce' places non-existent element: _48</li>
 *   <li>View 'Workforce' connector references non-existent element: _48</li>
 *   <li>View 'Workforce' connector references non-existent element: _48</li>
 *   <li>View 'Workforce' flow route references non-existent flow: _48</li>
 *   <li>View 'graphics' places non-existent element: _0</li>
 *   <li>View 'graphics' places non-existent element: _48</li>
 *   <li>View 'graphics' places non-existent element: _48</li>
 *   <li>View 'graphics' places non-existent element: _48</li>
 *   <li>View 'graphics' flow route references non-existent flow: _0</li>
 *   <li>View 'graphics' flow route references non-existent flow: _48</li>
 *   <li>View 'graphics' flow route references non-existent flow: _48</li>
 *   <li>View 'graphics' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class VensimIntro {

    public static void main(String[] args) {
        new VensimIntro().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("INTRO")
                .defaultSimulation("Month", 100.0, "Month", 0.125);

        // Stocks
        builder.stock(new StockDef("Average Worker Hours", "The average number of hours worked per week", 40.0, "Hour/Month", null));
        builder.stock(new StockDef("Workforce", "The number of workers", 0.0, "target_production/normal_productivity", "Person", null, List.of()));

        // Constants
        builder.constant("delay in adding or removing overtime hours", 3.0, "Month");
        builder.constant("normal workweek", 40.0, "Hour/Month");
        builder.constant("time to hire or layoff", 6.0, "Month");
        builder.constant("normal productivity", 1.0, "Widget/Month/Person");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("effect of morale on productivity lookup", "The effect that morale has on the ability to produce\\!\\!\\!", new double[]{0.0, 1.0, 2.0, 2.63444, 3.29909, 3.97583}, new double[]{0.0, 1.0, 2.0, 2.36842, 2.52632, 2.57895}, "LINEAR", "Dmnl"));
        builder.lookupTable(new LookupTableDef("morale lookup", "Lookup relating the average level of overtime to morale.\\!\\!\\!", new double[]{0.0, 0.326284, 0.495468, 0.682779, 0.839879, 1.0, 1.14804, 1.3716, 1.66767, 2.0}, new double[]{1.5, 1.4386, 1.40351, 1.32018, 1.18421, 1.0, 0.833333, 0.640351, 0.526316, 0.5}, "LINEAR", "Dmnl"));

        // Variables
        builder.variable(new VariableDef("change in hours worked", "change in hours worked", "(required_worker_hours-Average_Worker_Hours) / delay_in_adding_or_removing_overtime_hours", "Hour/(Month*Month)"));
        builder.variable(new VariableDef("production", "Total amount produced.", "Workforce * required_worker_hours * productivity / normal_workweek", "Widget/Month"));
        builder.variable(new VariableDef("required worker hours", "The amount relative to normal that people have to work to\n\t\t         produce enough.", "IF((Workforce*productivity) == 0, 0, (target_production) / (Workforce*productivity)) * normal_workweek", "Hour/Month"));
        builder.variable(new VariableDef("net hires", "The net number of people hired (laid off if negative).", "(desired_workforce-Workforce)/time_to_hire_or_layoff", "Person/Month"));
        builder.variable(new VariableDef("desired workforce", "The desired number of workers.", "IF((productivity) == 0, 0, (target_production) / (productivity))", "Person"));
        builder.variable(new VariableDef("morale", "Morale - 1 is normal.", "LOOKUP(morale_lookup, Average_Worker_Hours/normal_workweek)", "Dmnl"));
        builder.variable(new VariableDef("productivity", "The amount each peson can produce given morale effects.", "normal_productivity*LOOKUP(effect_of_morale_on_productivity_lookup, morale)", "Widget/(Month*Person)"));
        builder.variable(new VariableDef("sales", "The total amount sold.", "IF(TIME > 20,120,100)", "Widget/Month"));
        builder.variable(new VariableDef("target production", "The target amount produced.", "sales", "Widget/Month"));

        // Flows
        builder.flow(new FlowDef("Average Worker Hours net flow", "Net flow for Average Worker Hours", "change_in_hours_worked", "Month", null, "Average Worker Hours"));
        builder.flow(new FlowDef("Workforce net flow", "Net flow for Workforce", "net_hires", "Month", null, "Workforce"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
