/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.management;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: 1016_BurnoutHomer1.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class BurnoutHomer {

    public static void main(String[] args) {
        new BurnoutHomer().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1016_BurnoutHomer1")
                .defaultSimulation("Week", 75.0, "Week", 0.015625);

        // Stocks
        builder.stock(new StockDef("cumulative accomplishments", "cumulative accomplishments", 0.0, "", null));
        builder.stock(new StockDef("energy level", "energy level", 1.0, "energyunits", null));
        builder.stock(new StockDef("expected accomplishments per week", "expected accomplishments per week", 40.0, "tasks/week", null));
        builder.stock(new StockDef("hours worked per week", "hours worked per week", 40.0, "hour/week", null));
        builder.stock(new StockDef("perceived accomplishments per week", "perceived accomplishments per week", 0.0, "accomplishments_per_week", "tasks/week", null, List.of()));

        // Constants
        builder.constant("bias for fractional change in expectations", 0.1, "1/week");
        builder.constant("energy depletion normal", 0.06, "energyunits/week");
        builder.constant("energy recovery normal", 0.3, "energyunits/week");
        builder.constant("limit on hours worked per week", 80.0, "hour/week");
        builder.constant("time to perceive accomplishments per week", 1.0, "week");
        builder.constant("time to adjust hours worked per week", 1.0, "week");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("fractional_change_in_expectations_from_perceived_adequacy_lookup", null, new double[]{0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6}, new double[]{-0.7, -0.5, -0.35, -0.2, -0.1, 0.0, 0.1, 0.25, 0.4}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("effect_of_energy_level_on_hours_worked_lookup", null, new double[]{0.0, 0.2, 0.4, 0.6, 0.8, 1.0}, new double[]{0.0, 0.4, 0.7, 0.9, 1.0, 1.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("effect_of_high_energy_on_further_recovery_lookup", null, new double[]{0.0, 0.8, 0.85, 0.9, 0.95, 1.0}, new double[]{1.0, 1.0, 0.9, 0.7, 0.4, 0.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("effect_of_hours_worked_on_energy_depletion_lookup", null, new double[]{0.0, 20.0, 40.0, 60.0, 80.0, 100.0, 120.0}, new double[]{0.3, 0.6, 1.0, 1.5, 2.0, 2.5, 3.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("effect_of_hours_worked_on_recovery_lookup", null, new double[]{0.0, 20.0, 40.0, 60.0, 80.0, 100.0, 120.0}, new double[]{1.3, 1.2, 1.0, 0.7, 0.5, 0.35, 0.25}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("effect_of_low_energy_on_further_depletion_lookup", null, new double[]{0.0, 0.05, 0.1, 0.15, 0.2, 1.0}, new double[]{0.0, 0.4, 0.7, 0.9, 1.0, 1.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("effect_of_perceived_adequacy_on_energy_depletion_lookup", null, new double[]{0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6}, new double[]{5.0, 4.0, 3.1, 2.3, 1.6, 1.0, 0.6, 0.4, 0.3}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("effect_of_perceived_adequacy_on_hours_worked_lookup", null, new double[]{0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6}, new double[]{2.3, 1.9, 1.6, 1.35, 1.15, 1.0, 0.9, 0.8, 0.75}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("accomplishments_per_hour_lookup", null, new double[]{0.0, 0.2, 0.4, 0.6, 0.8, 1.0}, new double[]{0.0, 0.2, 0.4, 0.6, 0.8, 1.0}, "LINEAR"));

        // Variables
        builder.variable(new VariableDef("perceived adequacy of accomplishment", "perceived adequacy of accomplishment", "perceived_accomplishments_per_week / expected_accomplishments_per_week", "Dmnl"));
        builder.variable(new VariableDef("fractional change in expectations from perceived adequacy", "fractional change in expectations from perceived adequacy", "LOOKUP(fractional_change_in_expectations_from_perceived_adequacy_lookup, perceived_adequacy_of_accomplishment)", "1/week"));
        builder.variable(new VariableDef("change in expected accomplishments per week", "change in expected accomplishments per week", "expected_accomplishments_per_week * fractional_change_in_expected_accomplishments_per_week", "tasks/week/week"));
        builder.variable(new VariableDef("change in hours worked per week", "change in hours worked per week", "(indicated_hours_worked_per_week - hours_worked_per_week) / time_to_adjust_hours_worked_per_week", "hour / week / week"));
        builder.variable(new VariableDef("change in perceived accomplishments per week", "change in perceived accomplishments per week", "(accomplishments_per_week - perceived_accomplishments_per_week) / time_to_perceive_accomplishments_per_week", "tasks/week/week"));
        builder.variable(new VariableDef("effect of energy level on hours worked", "effect of energy level on hours worked", "LOOKUP(effect_of_energy_level_on_hours_worked_lookup, energy_level)", "Dmnl"));
        builder.variable(new VariableDef("effect of high energy on further recovery", "effect of high energy on further recovery", "LOOKUP(effect_of_high_energy_on_further_recovery_lookup, energy_level)", "Dmnl"));
        builder.variable(new VariableDef("effect of hours worked on energy depletion", "effect of hours worked on energy depletion", "LOOKUP(effect_of_hours_worked_on_energy_depletion_lookup, hours_worked_per_week)", "Dmnl"));
        builder.variable(new VariableDef("effect of hours worked on recovery", "effect of hours worked on recovery", "LOOKUP(effect_of_hours_worked_on_recovery_lookup, hours_worked_per_week)", "Dmnl"));
        builder.variable(new VariableDef("effect of low energy on further depletion", "effect of low energy on further depletion", "LOOKUP(effect_of_low_energy_on_further_depletion_lookup, energy_level)", "Dmnl"));
        builder.variable(new VariableDef("effect of perceived adequacy on energy depletion", "effect of perceived adequacy on energy depletion", "LOOKUP(effect_of_perceived_adequacy_on_energy_depletion_lookup, perceived_adequacy_of_accomplishment)", "Dmnl"));
        builder.variable(new VariableDef("effect of perceived adequacy on hours worked", "effect of perceived adequacy on hours worked", "LOOKUP(effect_of_perceived_adequacy_on_hours_worked_lookup, perceived_adequacy_of_accomplishment)", "Dmnl"));
        builder.variable(new VariableDef("energy depletion", "energy depletion", "energy_depletion_normal * effect_of_perceived_adequacy_on_energy_depletion * effect_of_hours_worked_on_energy_depletion * effect_of_low_energy_on_further_depletion", "energyunits/week"));
        builder.variable(new VariableDef("indicated hours worked per week", "indicated hours worked per week", "MIN(limit_on_hours_worked_per_week, (hours_worked_per_week * effect_of_energy_level_on_hours_worked * effect_of_perceived_adequacy_on_hours_worked))", "hour/week"));
        builder.variable(new VariableDef("energy recovery", "energy recovery", "energy_recovery_normal * effect_of_hours_worked_on_recovery * effect_of_high_energy_on_further_recovery", "energyunits/week"));
        builder.variable(new VariableDef("fractional change in expected accomplishments per week", "fractional change in expected accomplishments per week", "bias_for_fractional_change_in_expectations + fractional_change_in_expectations_from_perceived_adequacy", "1/week"));
        builder.variable(new VariableDef("accomplishments per week", "accomplishments per week", "hours_worked_per_week * accomplishments_per_hour", "tasks/week"));
        builder.variable(new VariableDef("accomplishments per hour", "accomplishments per hour", "LOOKUP(accomplishments_per_hour_lookup, energy_level)", "tasks/hour"));

        // Flows
        builder.flow(new FlowDef("cumulative accomplishments net flow", "Net flow for cumulative accomplishments", "accomplishments_per_week", "Week", null, "cumulative accomplishments"));
        builder.flow(new FlowDef("energy level inflow 1", null, "energy_recovery", "Week", null, "energy level"));
        builder.flow(new FlowDef("energy level outflow 2", null, "energy_depletion", "Week", "energy level", null));
        builder.flow(new FlowDef("expected accomplishments per week net flow", "Net flow for expected accomplishments per week", "change_in_expected_accomplishments_per_week", "Week", null, "expected accomplishments per week"));
        builder.flow(new FlowDef("hours worked per week net flow", "Net flow for hours worked per week", "change_in_hours_worked_per_week", "Week", null, "hours worked per week"));
        builder.flow(new FlowDef("perceived accomplishments per week net flow", "Net flow for perceived accomplishments per week", "change_in_perceived_accomplishments_per_week", "Week", null, "perceived accomplishments per week"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
