/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.management;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 1401_ManagingFaculty.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 2</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 7</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 19</li>
 *   <li>View 'View 1' connector references non-existent element: 16</li>
 *   <li>View 'View 1' connector references non-existent element: 19</li>
 *   <li>View 'View 1' connector references non-existent element: 24</li>
 *   <li>View 'View 1' connector references non-existent element: 24</li>
 *   <li>View 'View 1' connector references non-existent element: 21</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class ManagingFaculty {

    public static void main(String[] args) {
        new ManagingFaculty().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1401_ManagingFaculty")
                .defaultSimulation("Month", 200.0, "Month", 0.0625);

        // Stocks
        builder.stock(new StockDef("money", "money", 500000.0, "euro", null));
        builder.stock(new StockDef("professors", "professors", 25.0, "person", null));

        // Constants
        builder.constant("TIME_STEP", 0.0625, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 200.0, "Month");
        builder.constant("budgetcoverage", 1.0, "Month");
        builder.constant("teaching fee", 150000.0, "euro/Month");
        builder.constant("average hiring time", 12.0, "Month");
        builder.constant("average professor salary", 3500.0, "euro/person/Month");
        builder.constant("earnings per published paper", 4000.0, "euro/paper");
        builder.constant("initially available money", 500000.0, "euro");
        builder.constant("number of papers per professor", 0.5, "paper/person/Month");

        // Variables
        builder.variable(new VariableDef("desired number of professors", "desired number of professors", "money / average_professor_salary /budgetcoverage", "people"));
        builder.variable(new VariableDef("earnings from papers", "earnings from papers", "earnings_per_published_paper * number_of_papers_published", "euro/Month"));
        builder.variable(new VariableDef("money spent on salaries", "money spent on salaries", "professors * average_professor_salary", "euro/Month"));
        builder.variable(new VariableDef("new professors hired", "new professors hired", "MAX((desired_number_of_professors - professors) / average_hiring_time,0 )", "person/Month"));
        builder.variable(new VariableDef("number of papers published", "number of papers published", "number_of_papers_per_professor * professors", "paper/Month"));
        builder.variable(new VariableDef("subsidy and earnings from papers", "subsidy and earnings from papers", "teaching_fee + earnings_from_papers", "euro/Month"));
        builder.variable(new VariableDef("professors leaving", "professors leaving", "professors*percentage_of_leavers", "person/Month"));
        builder.variable(new VariableDef("percentage of leavers", "percentage of leavers", "0.1/12", "1/Month"));

        // Flows
        builder.flow(new FlowDef("money inflow 1", null, "subsidy_and_earnings_from_papers", "Month", null, "money"));
        builder.flow(new FlowDef("money outflow 2", null, "money_spent_on_salaries", "Month", "money", null));
        builder.flow(new FlowDef("professors inflow 1", null, "new_professors_hired", "Month", null, "professors"));
        builder.flow(new FlowDef("professors outflow 2", null, "professors_leaving", "Month", "professors", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
