/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.management;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: 1413_ProductionManagement.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _636</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _668</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 2</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 7</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 16</li>
 *   <li>View 'View 1' connector references non-existent element: _636</li>
 *   <li>View 'View 1' connector references non-existent element: 18</li>
 *   <li>View 'View 1' connector references non-existent element: _636</li>
 *   <li>View 'View 1' connector references non-existent element: _636</li>
 *   <li>View 'View 1' connector references non-existent element: 27</li>
 *   <li>View 'View 1' connector references non-existent element: 27</li>
 *   <li>View 'View 1' connector references non-existent element: 24</li>
 *   <li>View 'View 1' connector references non-existent element: 32</li>
 *   <li>View 'View 1' connector references non-existent element: 29</li>
 *   <li>View 'View 1' connector references non-existent element: 32</li>
 *   <li>View 'View 1' connector references non-existent element: 38</li>
 *   <li>View 'View 1' connector references non-existent element: _668</li>
 *   <li>View 'View 1' connector references non-existent element: 40</li>
 *   <li>View 'View 1' connector references non-existent element: _668</li>
 *   <li>View 'View 1' connector references non-existent element: _668</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 64</li>
 *   <li>View 'View 1' connector references non-existent element: 64</li>
 *   <li>View 'View 1' connector references non-existent element: 61</li>
 *   <li>View 'View 1' connector references non-existent element: 70</li>
 *   <li>View 'View 1' connector references non-existent element: 70</li>
 *   <li>View 'View 1' connector references non-existent element: 67</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _636</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _668</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class ProductionManagement {

    public static void main(String[] args) {
        new ProductionManagement().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1413_ProductionManagement")
                .defaultSimulation("Week", 208.0, "Week", 0.0625);

        // Stocks
        builder.stock(new StockDef("cumulative unfulfilled company orders", "cumulative unfulfilled company orders", 0.0, "component", null));
        builder.stock(new StockDef("cumulative unfulfilled final customer orders", "cumulative unfulfilled final customer orders", 0.0, "item", null));
        builder.stock(new StockDef("inventory component", "inventory component", 0.0, "desired_component_inventory", "component", null, List.of()));
        builder.stock(new StockDef("inventory finished products", "inventory finished products", 0.0, "desired_inventory_final_product", "item", null, List.of()));
        builder.stock(new StockDef("production capacity assembly line", "production capacity assembly line", 0.0, "internal_order_rate_final_product", "item/week", null, List.of()));
        builder.stock(new StockDef("production capacity components line", "production capacity components line", 0.0, "number_of_components_per_finished_product*internal_order_rate_final_product", "component/week", null, List.of()));

        // Constants
        builder.constant("TIME_STEP", 0.0625, "Week");
        builder.constant("INITIAL_TIME", 0.0, "Week");
        builder.constant("FINAL_TIME", 208.0, "Week");
        builder.constant("desired component inventory coverage", 1.5, "week");
        builder.constant("assembly time", 1.0, "week");
        builder.constant("component production time", 1.0, "week");
        builder.constant("delivery period", 1.0, "week");
        builder.constant("delivery period finished products", 1.0, "week");
        builder.constant("number of components per finished product", 2.0, "component/item");
        builder.constant("desired inventory coverage finished product", 1.5, "week");
        builder.constant("adaptation time assembly line", 12.0, "week");
        builder.constant("adaptation time component production capacity", 8.0, "week");

        // Variables
        builder.variable(new VariableDef("desired component inventory", "desired component inventory", "full_capacity_internal_component_order_rate*desired_component_inventory_coverage", "component"));
        builder.variable(new VariableDef("assembly finished product", "assembly finished product", "MAX(deliveries_of_components,0)/number_of_components_per_finished_product", "item/week"));
        builder.variable(new VariableDef("capacity change assembly line", "capacity change assembly line", "(desired_inventory_final_product-inventory_finished_products)/assembly_time/adaptation_time_assembly_line", "item/week/week"));
        builder.variable(new VariableDef("capacity change component production capacity", "IF THEN ELSE( desired component inventory<inventory component, IF THEN  ELSE(-(desired component inventory-inventory component\n\t\t)/component production time/adaptation time component production capacity>production  capacity components, -production capacity components/adaptation time  component production capacity , (desired component inventory\n\t\t-inventory component)/component production time/adaptation time component production  capacity), (desired component inventory-inventory component)/component  production time/\n\t\tadaptation time component production capacity)", "(desired_component_inventory-inventory_component)/component_production_time/adaptation_time_component_production_capacity", "component/week/week"));
        builder.variable(new VariableDef("customer order rate", "10000+STEP(1000,5) - STEP(1000,10)", "10000+STEP(1000,5) - STEP(1000,10)", "item/week"));
        builder.variable(new VariableDef("deliveries of components", "deliveries of components", "MAX(MIN(full_capacity_internal_component_order_rate,inventory_component/delivery_period ),0)", "component/week"));
        builder.variable(new VariableDef("deliveries of finished product", "deliveries of finished product", "MIN(internal_order_rate_final_product,inventory_finished_products/delivery_period_finished_products )", "item/week"));
        builder.variable(new VariableDef("unfulfilled customer orders", "unfulfilled customer orders", "MAX(internal_order_rate_final_product-deliveries_of_finished_product,0)", "item/week"));
        builder.variable(new VariableDef("desired inventory final product", "desired inventory final product", "desired_inventory_coverage_finished_product*internal_order_rate_final_product", "item"));
        builder.variable(new VariableDef("full capacity internal component order rate", "internal order rate final product*number of components per finished product", "production_capacity_assembly_line*number_of_components_per_finished_product", "component/week"));
        builder.variable(new VariableDef("internal order rate final product", "SMOOTH3I(customer order rate, 26, customer order rate)", "customer_order_rate", "item/week"));
        builder.variable(new VariableDef("production component", "production component", "MAX(production_capacity_components_line,0)", "component/week"));
        builder.variable(new VariableDef("unfulfilled component orders", "unfulfilled component orders", "MAX(full_capacity_internal_component_order_rate-deliveries_of_components,0)", "component/week"));

        // Flows
        builder.flow(new FlowDef("cumulative unfulfilled company orders net flow", "Net flow for cumulative unfulfilled company orders", "unfulfilled_component_orders", "Week", null, "cumulative unfulfilled company orders"));
        builder.flow(new FlowDef("cumulative unfulfilled final customer orders net flow", "Net flow for cumulative unfulfilled final customer orders", "unfulfilled_customer_orders", "Week", null, "cumulative unfulfilled final customer orders"));
        builder.flow(new FlowDef("inventory component inflow 1", null, "production_component", "Week", null, "inventory component"));
        builder.flow(new FlowDef("inventory component outflow 2", null, "deliveries_of_components", "Week", "inventory component", null));
        builder.flow(new FlowDef("inventory finished products inflow 1", null, "assembly_finished_product", "Week", null, "inventory finished products"));
        builder.flow(new FlowDef("inventory finished products outflow 2", null, "deliveries_of_finished_product", "Week", "inventory finished products", null));
        builder.flow(new FlowDef("production capacity assembly line net flow", "Net flow for production capacity assembly line", "capacity_change_assembly_line", "Week", null, "production capacity assembly line"));
        builder.flow(new FlowDef("production capacity components line net flow", "Net flow for production capacity components line", "capacity_change_component_production_capacity", "Week", null, "production capacity components line"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
