/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.economics;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 1403_DebtCrisisBasedOnZ605.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Lookup 'CREDIT_FUNCTION_lookup': sorted non-monotonic x-values and removed 1 duplicate(s)</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: Time</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: Time</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class DebtCrisis {

    public static void main(String[] args) {
        new DebtCrisis().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1403_DebtCrisisBasedOnZ605")
                .defaultSimulation("Year", 100.0, "Year", 0.25);

        // Stocks
        builder.stock(new StockDef("production plants", "production plants", 0.0, "$", null));
        builder.stock(new StockDef("debt", "debt", 0.0, "$", null));
        builder.stock(new StockDef("profit sum", "profit sum", 0.0, "$", null));
        builder.stock(new StockDef("interest sum", "interest sum", 0.0, "$", null));

        // Constants
        builder.constant("INITIAL PRODUCTION PLANTS", 0.0, "$");
        builder.constant("INITIAL DEBT", 0.0, "$");
        builder.constant("INVESTMENT FRACTION", 0.5, "1");
        builder.constant("INVESTMENT EFFECTIVENESS", 0.5, "1");
        builder.constant("CREDIT AMOUNT", 100.0, "$/Year");
        builder.constant("DEMAND", 100.0, "Stück/Year");
        builder.constant("DEBT REPAYMENT FRACTION", 0.5, "1");
        builder.constant("SPECIFIC PRODUCTION", 1.0, "($/Year)/$");
        builder.constant("DETERIORATION RATE", 0.05, "1/Year");
        builder.constant("INTEREST RATE", 0.07, "1/Year");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("CREDIT_FUNCTION_lookup", null, new double[]{0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 200.0}, new double[]{0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("price_factor_lookup", null, new double[]{0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0}, new double[]{2.0, 2.0, 2.0, 2.0, 1.4, 1.0, 0.6, 0.1, 0.1, 0.1, 0.1}, "LINEAR"));

        // Variables
        builder.variable(new VariableDef("expansion", "expansion", "INVESTMENT_EFFECTIVENESS*investment", "$/Year"));
        builder.variable(new VariableDef("revenue", "revenue", "price_factor*production", "$/Year"));
        builder.variable(new VariableDef("profit", "profit", "(1-INVESTMENT_FRACTION)*investment_generation/INVESTMENT_FRACTION", "$/Year"));
        builder.variable(new VariableDef("profit rate", "profit rate", "profit", "$/Year"));
        builder.variable(new VariableDef("investment generation", "MAX((net revenue-repayment), 0)", "INVESTMENT_FRACTION*MAX((net_revenue-repayment), 0)", "$/Year"));
        builder.variable(new VariableDef("investment", "investment", "investment_generation+credit", "$/Year"));
        builder.variable(new VariableDef("credit", "credit", "CREDIT_AMOUNT*CREDIT_FUNCTION", "$/Year"));
        builder.variable(new VariableDef("CREDIT FUNCTION", "CREDIT FUNCTION", "LOOKUP(CREDIT_FUNCTION_lookup, TIME)", "1"));
        builder.variable(new VariableDef("net revenue", "net revenue", "revenue-interest_payment", "$/Year"));
        builder.variable(new VariableDef("price factor", "price factor", "LOOKUP(price_factor_lookup, production/DEMAND)", "1"));
        builder.variable(new VariableDef("production", "production", "SPECIFIC_PRODUCTION*production_plants", "$/Year"));
        builder.variable(new VariableDef("repayment", "repayment", "IF((net_revenue>0) and (debt>0), DEBT_REPAYMENT_FRACTION*net_revenue, 0)", "$/Year"));
        builder.variable(new VariableDef("debt decrease", "debt decrease", "repayment", "$/Year"));
        builder.variable(new VariableDef("debt increase", "debt increase", "credit+interest_debt", "$/Year"));
        builder.variable(new VariableDef("deterioration", "deterioration", "DETERIORATION_RATE*production_plants", "$/Year"));
        builder.variable(new VariableDef("interest", "interest", "interest_payment", "$/Year"));
        builder.variable(new VariableDef("interest debt", "interest debt", "MAX(-net_revenue, 0)", "$/Year"));
        builder.variable(new VariableDef("interest payment", "interest payment", "INTEREST_RATE*debt", "$/Year"));

        // Flows
        builder.flow(new FlowDef("production plants inflow 1", null, "expansion", "Year", null, "production plants"));
        builder.flow(new FlowDef("production plants outflow 2", null, "deterioration", "Year", "production plants", null));
        builder.flow(new FlowDef("debt inflow 1", null, "debt_increase", "Year", null, "debt"));
        builder.flow(new FlowDef("debt outflow 2", null, "debt_decrease", "Year", "debt", null));
        builder.flow(new FlowDef("profit sum net flow", "Net flow for profit sum", "profit_rate", "Year", null, "profit sum"));
        builder.flow(new FlowDef("interest sum net flow", "Net flow for interest sum", "interest", "Year", null, "interest sum"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
