/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.economics;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: 0611HousingStockDynamicsA.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _204</li>
 *   <li>View 'View 1' places non-existent element: _268</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 4</li>
 *   <li>View 'View 1' connector references non-existent element: _204</li>
 *   <li>View 'View 1' connector references non-existent element: _204</li>
 *   <li>View 'View 1' connector references non-existent element: _268</li>
 *   <li>View 'View 1' connector references non-existent element: _268</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 11</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _204</li>
 *   <li>View 'View 1' connector references non-existent element: _268</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _204</li>
 *   <li>View 'View 1' flow route references non-existent flow: _268</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class HousingStock {

    public static void main(String[] args) {
        new HousingStock().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0611HousingStockDynamicsA")
                .defaultSimulation("Month", 100.0, "Month", 0.5);

        // Stocks
        builder.stock(new StockDef("houses", "houses", 5000000.0, "house", null));
        builder.stock(new StockDef("houses under construction", "houses under construction", 0.0, "building * time_to_build_houses", "house", null, List.of()));
        builder.stock(new StockDef("planned houses", "planned houses", 0.0, "planning * average_time_from_planning_to_building", "house", null, List.of()));

        // Constants
        builder.constant("TIME_STEP", 0.5, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");
        builder.constant("average house lifetime", 1200.0, "Month");
        builder.constant("time to build houses", 6.0, "Month");
        builder.constant("average time from planning to building", 3.0, "Month");
        builder.constant("average time to respond to housing gap", 8.0, "Month");

        // Variables
        builder.variable(new VariableDef("replacement houses", "replacement houses", "demolishing", "house/Month"));
        builder.variable(new VariableDef("planning", "planning", "replacement_houses + (houses_gap / average_time_to_respond_to_housing_gap)", "house/Month"));
        builder.variable(new VariableDef("building", "building", "planned_houses / average_time_from_planning_to_building", "house/Month"));
        builder.variable(new VariableDef("completing", "completing", "houses_under_construction / time_to_build_houses", "house/Month"));
        builder.variable(new VariableDef("demolishing", "demolishing", "houses / average_house_lifetime", "house/Month"));
        builder.variable(new VariableDef("houses gap", "houses gap", "( desired_number_of_houses - houses)", "house"));
        builder.variable(new VariableDef("desired number of houses", "desired number of houses", "5e+006+STEP(50000,20)", "house"));

        // Flows
        builder.flow(new FlowDef("houses inflow 1", null, "completing", "Month", null, "houses"));
        builder.flow(new FlowDef("houses outflow 2", null, "demolishing", "Month", "houses", null));
        builder.flow(new FlowDef("houses under construction inflow 1", null, "building", "Month", null, "houses under construction"));
        builder.flow(new FlowDef("houses under construction outflow 2", null, "completing", "Month", "houses under construction", null));
        builder.flow(new FlowDef("planned houses inflow 1", null, "planning", "Month", null, "planned houses"));
        builder.flow(new FlowDef("planned houses outflow 2", null, "building", "Month", "planned houses", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
