/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.economics;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: MARKET.mdl
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 */
public class Market {

    public static void main(String[] args) {
        new Market().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("MARKET")
                .defaultSimulation("Month", 60.0, "Month");

        // Stocks
        builder.stock(new StockDef("Adv Budget Effective", "Adv Budget Effective", 0.0, "adv_budget", "$/ Month", null, List.of()));
        builder.stock(new StockDef("Cum Retained Cash", "Cum Retained Cash", 0.0, "$", null));
        builder.stock(new StockDef("Int Dir Salespeople", "Int Dir Salespeople", 0.0, "target_int_dir_sales", "People", null, List.of()));
        builder.stock(new StockDef("Pot Orders In Negotiation", "Pot Orders In Negotiation", 25.0, "Orders", null));
        builder.stock(new StockDef("Potential Orders", "Potential Orders", 2400.0, "Orders", null));
        builder.stock(new StockDef("Prod Gen Rate", "Prod Gen Rate", 0.0, "PROD_DEV_EFFICIENCY * prod_dev_budget", "Product / Month", null, List.of()));
        builder.stock(new StockDef("Products", "Products", 10.0, "Product", null));
        builder.stock(new StockDef("Receivables", "Receivables", 0.0, "accrued_revenue * TIME_TO_CLEAR_RECEIVABLES", "$", null, List.of()));

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 60.0, "Month");
        builder.constant("ADV IMPACT DELAY", 12.0, "Months");
        builder.constant("DEMOS PER PERSON MONTH", 12.0, "Orders / Month / Person");
        builder.constant("DURATION OF NEGOTIATION", 1.0, "Month");
        builder.constant("EXT SALES REP FEE", 400.0, "$/ Person / Month");
        builder.constant("FRAC BUDGET MFG", 0.47, "Dimensionless");
        builder.constant("FRAC BUDGET R AND D", 0.15, "Dimensionless");
        builder.constant("INT DIR SALES COST", 2400.0, "$/ Person / Month");
        builder.constant("LIFETIME OF MAILING LIST", 60.0, "Months");
        builder.constant("NORMAL LEAD GEN EFFIC", 7.0, "Orders / Products / Month");
        builder.constant("NORMAL SHARE OF SALES", 0.8, "Dimensionless");
        builder.constant("PERCENT BUDGET ADV", 4.0, "Dimensionless");
        builder.constant("PERCENT BUDGET EXT SALES REPS", 8.0, "Dimensionless");
        builder.constant("PERCENT BUDGET INT DIR SALES", 6.0, "Dimensionless");
        builder.constant("POTENTIAL ORDERS I", 2400.0, "Orders");
        builder.constant("PRICE", 7000.0, "$/ Orders");
        builder.constant("PROD DEV EFFICIENCY", 3.0E-5, "Product / $");
        builder.constant("PROD DEVT TIME", 12.0, "Month");
        builder.constant("PROD OBS TIME", 60.0, "Months");
        builder.constant("THIDS", 10.0, "Months");
        builder.constant("TIME TO CLEAR RECEIVABLES", 6.0, "Months");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("TABLE FOR EFF OF LEADS", "TABLE FOR EFF OF LEADS", new double[]{0.0, 100.0, 200.0, 300.0, 400.0, 500.0}, new double[]{0.0, 0.32, 0.6, 0.8, 0.9, 1.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("TABLE FOR EFFECT OF ADV", "TABLE FOR EFFECT OF ADV", new double[]{0.0, 40.0, 80.0, 120.0, 160.0, 200.0, 240.0, 280.0, 320.0, 360.0, 400.0}, new double[]{0.01, 0.2, 0.5, 0.7, 0.8, 1.0, 1.03, 1.06, 1.08, 1.09, 1.1}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("TABLE FOR FRAC BUYING", "TABLE FOR FRAC BUYING", new double[]{0.0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03}, new double[]{1.0, 0.75, 0.55, 0.43, 0.38, 0.35, 0.34}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("TABLE FOR SALES REP EFFECT", "TABLE FOR SALES REP EFFECT", new double[]{0.0017, 0.0027, 0.0037, 0.0047, 0.0057, 0.0067, 0.0077, 0.0087, 0.0097, 0.0107}, new double[]{0.4, 0.55, 0.7, 0.85, 1.0, 1.1, 1.2, 1.3, 1.4, 1.4}, "LINEAR"));

        // Variables
        builder.variable(new VariableDef("accrued revenue", "accrued revenue", "unit_sales * PRICE", "$/ Month"));
        builder.variable(new VariableDef("adv budget", "adv budget", "FRAC_BUDGET_ADV * cash_revenue", "$/ Month"));
        builder.variable(new VariableDef("cash revenue", "cash revenue", "Receivables / TIME_TO_CLEAR_RECEIVABLES", "$/ Month"));
        builder.variable(new VariableDef("eff of lead avail on demos", "eff of lead avail on demos", "LOOKUP(TABLE_FOR_EFF_OF_LEADS, Potential_Orders / Int_Dir_Salespeople)", "Dimensionless"));
        builder.variable(new VariableDef("effect of advertising", "effect of advertising", "LOOKUP(TABLE_FOR_EFFECT_OF_ADV, Adv_Budget_Effective / Products)", "Dimensionless"));
        builder.variable(new VariableDef("external sales reps", "external sales reps", "cash_revenue * FRAC_BUDGET_EXT_SALES_REPS / EXT_SALES_REP_FEE", "People"));
        builder.variable(new VariableDef("FRAC BUDGET ADV", "FRAC BUDGET ADV", "INITIAL(PERCENT_BUDGET_ADV/100)", "Dimensionless"));
        builder.variable(new VariableDef("FRAC BUDGET EXT SALES REPS", "FRAC BUDGET EXT SALES REPS", "INITIAL(PERCENT_BUDGET_EXT_SALES_REPS/100)", "Dimensionless"));
        builder.variable(new VariableDef("FRAC BUDGET INT DIR SALES", "FRAC BUDGET INT DIR SALES", "INITIAL(PERCENT_BUDGET_INT_DIR_SALES/100)", "Dimensionless"));
        builder.variable(new VariableDef("frac cash retained", "frac cash retained", "( 1 - FRAC_BUDGET_MFG - FRAC_BUDGET_R_AND_D - FRAC_BUDGET_ADV - FRAC_BUDGET_EXT_SALES_REPS - FRAC_BUDGET_INT_DIR_SALES )", "Fraction"));
        builder.variable(new VariableDef("fraction custs buying", "fraction custs buying", "LOOKUP(TABLE_FOR_FRAC_BUYING, Pot_Orders_In_Negotiation / Potential_Orders)", "Dimensionless"));
        builder.variable(new VariableDef("pot order creation", "pot order creation", "NORMAL_LEAD_GEN_EFFIC * Products * effect_of_advertising", "Orders / Month"));
        builder.variable(new VariableDef("pot orders lost to comp", "pot orders lost to comp", "Pot_Orders_In_Negotiation * fraction_custs_buying * ( 1 - NORMAL_SHARE_OF_SALES ) / DURATION_OF_NEGOTIATION", "Orders / Month"));
        builder.variable(new VariableDef("pot orders not buying", "pot orders not buying", "Pot_Orders_In_Negotiation * ( 1 - fraction_custs_buying ) / DURATION_OF_NEGOTIATION", "Orders / Month"));
        builder.variable(new VariableDef("pot ords mov to negot", "pot ords mov to negot", "Int_Dir_Salespeople * DEMOS_PER_PERSON_MONTH * eff_of_lead_avail_on_demos * sales_rep_effect_mult", "Orders / Month"));
        builder.variable(new VariableDef("pot ords obs rate", "pot ords obs rate", "Potential_Orders / LIFETIME_OF_MAILING_LIST", "Orders / Month"));
        builder.variable(new VariableDef("prod dev budget", "prod dev budget", "cash_revenue * FRAC_BUDGET_R_AND_D", "$/ Month"));
        builder.variable(new VariableDef("prod obsolescence rate", "prod obsolescence rate", "Products / PROD_OBS_TIME", "Product / Month"));
        builder.variable(new VariableDef("retained cash flow", "retained cash flow", "cash_revenue * frac_cash_retained", "$/ Month"));
        builder.variable(new VariableDef("sales rep effect mult", "sales rep effect mult", "LOOKUP(TABLE_FOR_SALES_REP_EFFECT, external_sales_reps / Potential_Orders)", "Dimensionless"));
        builder.variable(new VariableDef("target int dir sales", "target int dir sales", "cash_revenue * FRAC_BUDGET_INT_DIR_SALES / INT_DIR_SALES_COST", "People"));
        builder.variable(new VariableDef("unit sales", "unit sales", "Pot_Orders_In_Negotiation * NORMAL_SHARE_OF_SALES * fraction_custs_buying / DURATION_OF_NEGOTIATION", "Orders / Month"));

        // Flows
        builder.flow(new FlowDef("Adv Budget Effective net flow", "Net flow for Adv Budget Effective", "( adv_budget - Adv_Budget_Effective ) / ADV_IMPACT_DELAY", "Month", null, "Adv Budget Effective"));
        builder.flow(new FlowDef("Cum Retained Cash net flow", "Net flow for Cum Retained Cash", "retained_cash_flow", "Month", null, "Cum Retained Cash"));
        builder.flow(new FlowDef("Int Dir Salespeople net flow", "Net flow for Int Dir Salespeople", "( target_int_dir_sales - Int_Dir_Salespeople ) / THIDS", "Month", null, "Int Dir Salespeople"));
        builder.flow(new FlowDef("Pot Orders In Negotiation inflow 1", null, "pot_ords_mov_to_negot", "Month", null, "Pot Orders In Negotiation"));
        builder.flow(new FlowDef("Pot Orders In Negotiation outflow 2", null, "unit_sales", "Month", "Pot Orders In Negotiation", null));
        builder.flow(new FlowDef("Pot Orders In Negotiation outflow 3", null, "pot_orders_lost_to_comp", "Month", "Pot Orders In Negotiation", null));
        builder.flow(new FlowDef("Pot Orders In Negotiation outflow 4", null, "pot_orders_not_buying", "Month", "Pot Orders In Negotiation", null));
        builder.flow(new FlowDef("Potential Orders inflow 1", null, "pot_order_creation", "Month", null, "Potential Orders"));
        builder.flow(new FlowDef("Potential Orders outflow 2", null, "pot_ords_obs_rate", "Month", "Potential Orders", null));
        builder.flow(new FlowDef("Potential Orders outflow 3", null, "pot_ords_mov_to_negot", "Month", "Potential Orders", null));
        builder.flow(new FlowDef("Potential Orders inflow 4", null, "pot_orders_not_buying", "Month", null, "Potential Orders"));
        builder.flow(new FlowDef("Potential Orders inflow 5", null, "unit_sales", "Month", null, "Potential Orders"));
        builder.flow(new FlowDef("Prod Gen Rate net flow", "Net flow for Prod Gen Rate", "( PROD_DEV_EFFICIENCY * prod_dev_budget - Prod_Gen_Rate ) / PROD_DEVT_TIME", "Month", null, "Prod Gen Rate"));
        builder.flow(new FlowDef("Products inflow 1", null, "Prod_Gen_Rate", "Month", null, "Products"));
        builder.flow(new FlowDef("Products outflow 2", null, "prod_obsolescence_rate", "Month", "Products", null));
        builder.flow(new FlowDef("Receivables inflow 1", null, "accrued_revenue", "Month", null, "Receivables"));
        builder.flow(new FlowDef("Receivables outflow 2", null, "cash_revenue", "Month", "Receivables", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
