/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.economics;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 1812_OrchestratedBankRun.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _620</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 3</li>
 *   <li>View 'View 1' connector references non-existent element: 12</li>
 *   <li>View 'View 1' connector references non-existent element: 9</li>
 *   <li>View 'View 1' connector references non-existent element: 12</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 39</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 43</li>
 *   <li>View 'View 1' connector references non-existent element: 43</li>
 *   <li>View 'View 1' connector references non-existent element: _620</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 56</li>
 *   <li>View 'View 1' connector references non-existent element: 53</li>
 *   <li>View 'View 1' connector references non-existent element: 56</li>
 *   <li>View 'View 1' connector references non-existent element: _620</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 81</li>
 *   <li>View 'View 1' connector references non-existent element: 81</li>
 *   <li>View 'View 1' connector references non-existent element: 78</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 89</li>
 *   <li>View 'View 1' connector references non-existent element: 89</li>
 *   <li>View 'View 1' connector references non-existent element: 86</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _620</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class OrchestratedBankRun {

    public static void main(String[] args) {
        new OrchestratedBankRun().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1812_OrchestratedBankRun")
                .defaultSimulation("Day", 100.0, "Day", 0.0625);

        // Stocks
        builder.stock(new StockDef("fixed deposits and loans", "fixed deposits and loans", 1.0E9, "EURO", null));
        builder.stock(new StockDef("intervention cost", "intervention cost", 0.0, "", null));
        builder.stock(new StockDef("liquid assets", "liquid assets", 1.15E9, "EURO", null));
        builder.stock(new StockDef("fixed assets", "fixed assets", 4.6E9, "EURO", null));
        builder.stock(new StockDef("liquid deposits and loans", "liquid deposits and loans", 4.5E9, "EURO", null));

        // Constants
        builder.constant("TIME_STEP", 0.0625, "Day");
        builder.constant("INITIAL_TIME", 0.0, "Day");
        builder.constant("FINAL_TIME", 100.0, "Day");
        builder.constant("initial credibility DSB", 0.9, "Dmnl");
        builder.constant("concerted percentage running", 0.05, "Dmnl");
        builder.constant("new fixed loan", 0.0, "EURO/Day");
        builder.constant("loss of credibility DSB", 0.8, "Dmnl");
        builder.constant("new liquid equity", 0.0, "EURO/Day");
        builder.constant("new fixed loan as fraction of liq lost", 0.0, "Dmnl");
        builder.constant("organised run", 1.0, "Dmnl");
        builder.constant("anger", 0.5, "Dmnl");
        builder.constant("liquidation time", 1.0, "Day");
        builder.constant("liquid asset liability target", 0.2, "Dmnl");
        builder.constant("expected hindrance possible bank failure", 0.5, "Dmnl");
        builder.constant("withdrawal time", 1.0, "Day");
        builder.constant("initial number of shares", 1.0E8, "share");
        builder.constant("liquidation premium", 0.15, "Dmnl");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("liquid_fraction_running_lookup", null, new double[]{0.0, 0.25, 0.5, 0.75, 1.0}, new double[]{0.0, 0.0, 0.01, 0.1, 0.5}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("perceived_likelihood_solvency_failure_lookup", null, new double[]{0.0, 0.8, 0.9, 1.0, 1.1, 1.2, 2.0}, new double[]{1.0, 1.0, 0.9, 0.5, 0.1, 0.0, 0.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("perceived_likelihood_liquidity_failure_lookup", null, new double[]{-1.0, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0}, new double[]{1.0, 1.0, 0.8, 0.4, 0.1, 0.01, 0.0, 0.0}, "LINEAR"));

        // Variables
        builder.variable(new VariableDef("concerted liquid fraction running", "concerted liquid fraction running", "organised_run*(STEP(concerted_percentage_running,2)-STEP(concerted_percentage_running ,4))", "Dmnl"));
        builder.variable(new VariableDef("credibility denials", "credibility denials", "initial_credibility_DSB-STEP(loss_of_credibility_DSB,1)*organised_run", "Dmnl"));
        builder.variable(new VariableDef("new fixed deposits and loans", "new fixed deposits and loans", "liquid_deposits_and_loans_lost*new_fixed_loan_as_fraction_of_liq_lost+new_fixed_loan", "EURO/Week"));
        builder.variable(new VariableDef("new liquid assets", "new liquid assets", "new_fixed_deposits_and_loans+new_liquid_equity", "EURO/Day"));
        builder.variable(new VariableDef("total asset total liability ratio", "total asset total liability ratio", "(fixed_assets+liquid_assets)/(liquid_deposits_and_loans+fixed_deposits_and_loans)", "Dmnl"));
        builder.variable(new VariableDef("perceived likelihood bank failure risk", "perceived likelihood bank failure risk", "MAX(perceived_likelihood_liquidity_failure,perceived_likelihood_solvency_failure)*(1 -credibility_denials)", "Dmnl"));
        builder.variable(new VariableDef("liquid fraction running", "liquid fraction running", "LOOKUP(liquid_fraction_running_lookup, perceived_likelihood_bank_failure_risk)", "Dmnl"));
        builder.variable(new VariableDef("liquidation losses", "liquidation losses", "liquidation/(1-liquidation_premium)*liquidation_premium", "EURO/Day"));
        builder.variable(new VariableDef("liquidation", "liquidation", "MAX(0,(liquid_asset_liability_target*liquid_deposits_and_loans-liquid_assets)/liquidation_time *(1-liquidation_premium))", "EURO/Day"));
        builder.variable(new VariableDef("liquid deposits and loans lost", "MIN((liquid fraction running+concerted liquid fraction running)*hindrance  bank failures*liquid deposits and loans/opnametijd,liquid deposits and  loans/opnametijd)", "MIN((liquid_fraction_running*(1+expected_hindrance_possible_bank_failure)*(1+anger)+ concerted_liquid_fraction_running)*liquid_deposits_and_loans /withdrawal_time ,liquid_deposits_and_loans/withdrawal_time)", "EURO/Day"));
        builder.variable(new VariableDef("DNB bank failure declaration", "DNB bank failure declaration", "IF(liquid_asset_liability_ratio < 0.01  or  total_asset_total_liability_ratio < 0.9, 1, 0)", ""));
        builder.variable(new VariableDef("perceived likelihood solvency failure", "solvency = total assets/total deposits and loans", "LOOKUP(perceived_likelihood_solvency_failure_lookup, total_asset_total_liability_ratio)", "Dmnl"));
        builder.variable(new VariableDef("liquid asset liability ratio", "liquid asset liability ratio", "liquid_assets/liquid_deposits_and_loans", "Dmnl"));
        builder.variable(new VariableDef("perceived likelihood liquidity failure", "perceived likelihood liquidity failure", "LOOKUP(perceived_likelihood_liquidity_failure_lookup, liquid_asset_liability_ratio)", "Dmnl"));
        builder.variable(new VariableDef("liquid assets lost", "liquid assets lost", "liquid_deposits_and_loans_lost", "EURO/Day"));

        // Flows
        builder.flow(new FlowDef("fixed deposits and loans net flow", "Net flow for fixed deposits and loans", "new_fixed_deposits_and_loans", "Day", null, "fixed deposits and loans"));
        builder.flow(new FlowDef("intervention cost net flow", "Net flow for intervention cost", "new_liquid_assets", "Day", null, "intervention cost"));
        builder.flow(new FlowDef("liquid assets inflow 1", null, "liquidation", "Day", null, "liquid assets"));
        builder.flow(new FlowDef("liquid assets inflow 2", null, "new_liquid_assets", "Day", null, "liquid assets"));
        builder.flow(new FlowDef("liquid assets outflow 3", null, "liquid_assets_lost", "Day", "liquid assets", null));
        builder.flow(new FlowDef("fixed assets outflow 1", null, "liquidation", "Day", "fixed assets", null));
        builder.flow(new FlowDef("fixed assets outflow 2", null, "liquidation_losses", "Day", "fixed assets", null));
        builder.flow(new FlowDef("liquid deposits and loans net flow", "Net flow for liquid deposits and loans", "-liquid_deposits_and_loans_lost", "Day", null, "liquid deposits and loans"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
