/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.economics;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: 1807_RealEstateBoomAndBust_EN.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _444</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _188</li>
 *   <li>View 'View 1' places non-existent element: Time</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 16</li>
 *   <li>View 'View 1' connector references non-existent element: 16</li>
 *   <li>View 'View 1' connector references non-existent element: 13</li>
 *   <li>View 'View 1' connector references non-existent element: 29</li>
 *   <li>View 'View 1' connector references non-existent element: 29</li>
 *   <li>View 'View 1' connector references non-existent element: 26</li>
 *   <li>View 'View 1' connector references non-existent element: 34</li>
 *   <li>View 'View 1' connector references non-existent element: 31</li>
 *   <li>View 'View 1' connector references non-existent element: 34</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _444</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 83</li>
 *   <li>View 'View 1' connector references non-existent element: 80</li>
 *   <li>View 'View 1' connector references non-existent element: 83</li>
 *   <li>View 'View 1' connector references non-existent element: 95</li>
 *   <li>View 'View 1' connector references non-existent element: 95</li>
 *   <li>View 'View 1' connector references non-existent element: _188</li>
 *   <li>View 'View 1' connector references non-existent element: _188</li>
 *   <li>View 'View 1' connector references non-existent element: Time</li>
 *   <li>View 'View 1' flow route references non-existent flow: _444</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _188</li>
 * </ul>
 */
public class RealEstateBoom {

    public static void main(String[] args) {
        new RealEstateBoom().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1807_RealEstateBoomAndBust_EN")
                .defaultSimulation("Month", 240.0, "Month", 0.0625);

        // Stocks
        builder.stock(new StockDef("REU under construction", "REU under construction", 0.0, "immigrants/workers_per_REU_under_construction", "real estate unit", null, List.of()));
        builder.stock(new StockDef("immigrants", "immigrants", 2000000.0, "person", null));
        builder.stock(new StockDef("locals", "locals", 220000.0, "person", null));
        builder.stock(new StockDef("REU supply", "REU supply", 1800000.0, "real estate unit", null));

        // Constants
        builder.constant("TIME_STEP", 0.0625, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 240.0, "Month");
        builder.constant("subsidy", 960.0, "dollar/real estate unit");
        builder.constant("avg REU approval time", 1.0, "Month");
        builder.constant("avg emigration time", 1.0, "Month");
        builder.constant("avg immigration time", 1.0, "Month");
        builder.constant("avg lifetime REU", 500.0, "Month");
        builder.constant("Al Maktoum exogenous investment rate", 0.01, "Dmnl");
        builder.constant("immigration multiplication factor", 1.0, "real estate unit/person");
        builder.constant("immigrant integration rate", 0.001, "1/Month");
        builder.constant("normal salary immigrants", 1000.0, "dollar/person/Month");
        builder.constant("REU construction time", 3.0, "Month");
        builder.constant("workers per REU under construction", 25.0, "person/real estate unit");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("REU shortage price effect", "REU shortage price effect", new double[]{0.0, 10.0, 50.0, 100.0}, new double[]{0.6, 4.0, 7.5, 10.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("REU_demand_per_person_lookup", null, new double[]{0.0, 240.0}, new double[]{1.0, 2.0}, "LINEAR"));

        // Variables
        builder.variable(new VariableDef("relative attractiveness to immigrate", "relative attractiveness to immigrate", "(avg_salary_immigrants/normal_salary_immigrants)/(REU_price/subsidy)", "Dmnl"));
        builder.variable(new VariableDef("workforce emigration", "+ MAX(exogenous emigration/avg emigration time,0)", "MAX((immigrants-labour_demand)/avg_emigration_time,0)", "person/Month"));
        builder.variable(new VariableDef("REU price", "REU price", "normal_cost_REU*LOOKUP(REU_shortage_price_effect, REU_shortage)", "dollar/real estate unit"));
        builder.variable(new VariableDef("labour shortage", "labour shortage", "labour_demand/immigrants", "Dmnl"));
        builder.variable(new VariableDef("avg salary immigrants", "avg salary immigrants", "normal_salary_immigrants*labour_shortage", "dollar/person/Month"));
        builder.variable(new VariableDef("expected new REU due to immigration", "expected new REU due to immigration", "(immigrants - immigrants_previous_period)*immigration_multiplication_factor", "real estate unit"));
        builder.variable(new VariableDef("expected REU shortage", "expected REU shortage", "REU_demand-REU_supply-REU_under_construction + expected_new_REU_due_to_immigration", "real estate unit"));
        builder.variable(new VariableDef("immigrants previous period", "immigrants previous period", "DELAY_FIXED(immigrants, 1, immigrants)", "person"));
        builder.variable(new VariableDef("workforce immigration", "+MIN((labour demand-immigrants)/avg emigration time,0)   relative  attractiveness to immigrate*immigrants/avg immigration time", "MAX(relative_attractiveness_to_immigrate*immigrants/avg_immigration_time,0)", "person/Month"));
        builder.variable(new VariableDef("immigrant integration", "immigrant integration", "immigrants*immigrant_integration_rate", "person/Month"));
        builder.variable(new VariableDef("labour demand", "number of workers per real estate unit under construction*real estate units under  construction*normal reu construction time\n\t\t/real estate unit construction time", "workers_per_REU_under_construction*REU_under_construction", "person"));
        builder.variable(new VariableDef("new REU plans approved", "new REU plans approved", "MAX(expected_REU_shortage/avg_REU_approval_time,0) + Al_Maktoum_exogenous_investment_rate *REU_supply/avg_REU_approval_time", "real estate unit/Month"));
        builder.variable(new VariableDef("normal cost REU", "normal cost REU", "50000 + avg_salary_immigrants*REU_construction_time*workers_per_REU_under_construction", "dollar/real estate unit"));
        builder.variable(new VariableDef("REU shortage", "REU shortage", "REU_demand/REU_supply", "Dmnl"));
        builder.variable(new VariableDef("REU commissioning", "MIN(real estate units under construction/real estate unit construction  time,MAX(0,buffer))", "MIN(immigrants/workers_per_REU_under_construction,REU_under_construction)/REU_construction_time", "real estate unit/Month"));
        builder.variable(new VariableDef("REU demand", "REU demand", "(immigrants+locals)*REU_demand_per_person", "real estate unit"));
        builder.variable(new VariableDef("REU demand per person", "REU demand per person", "LOOKUP(REU_demand_per_person_lookup, TIME)", "real estate unit/person"));
        builder.variable(new VariableDef("REU demolition", "REU demolition", "REU_supply/avg_lifetime_REU", "real estate unit/Month"));

        // Flows
        builder.flow(new FlowDef("REU under construction inflow 1", null, "new_REU_plans_approved", "Month", null, "REU under construction"));
        builder.flow(new FlowDef("REU under construction outflow 2", null, "REU_commissioning", "Month", "REU under construction", null));
        builder.flow(new FlowDef("immigrants inflow 1", null, "workforce_immigration", "Month", null, "immigrants"));
        builder.flow(new FlowDef("immigrants outflow 2", null, "workforce_emigration", "Month", "immigrants", null));
        builder.flow(new FlowDef("immigrants outflow 3", null, "immigrant_integration", "Month", "immigrants", null));
        builder.flow(new FlowDef("locals net flow", "Net flow for locals", "immigrant_integration", "Month", null, "locals"));
        builder.flow(new FlowDef("REU supply inflow 1", null, "REU_commissioning", "Month", null, "REU supply"));
        builder.flow(new FlowDef("REU supply outflow 2", null, "REU_demolition", "Month", "REU supply", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
