/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.economics;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: COMPETE1MODEL.MDL
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class VensimCompete1model {

    public static void main(String[] args) {
        new VensimCompete1model().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("COMPETE1MODEL")
                .defaultSimulation("Month", 60.0, "Month", 0.25);

        // Stocks
        builder.stock(new StockDef("Average Markup", "Average Markup", 1.5, "Dmnl", null));
        builder.stock(new StockDef("Price", "Price", 1.0, "$/Pair", null));
        builder.stock(new StockDef("Stock of Goods", "Stock of Goods", 0.0, "target_stock_of_goods", "Pair", null, List.of()));

        // Constants
        builder.constant("average life of goods", 8.0, "Month");
        builder.constant("fixed cost", 500000.0, "$/Month");
        builder.constant("initial price", 1.0, "$/Pair");
        builder.constant("marginal cost", 0.5, "$/Pair");
        builder.constant("normal target", 2.4E7, "Pair");
        builder.constant("reference price", 1.0, "$/Pair");
        builder.constant("target markup", 1.5, "Dmnl");
        builder.constant("time to adjust goods", 5.0, "Month");
        builder.constant("time for average markup", 4.0, "Month");
        builder.constant("time to adjust price", 3.0, "Month");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("effect price target lookup", "effect price target lookup", new double[]{0.2, 0.5, 1.0, 2.0, 4.0}, new double[]{5.0, 2.0, 1.0, 0.5, 0.02}, "LINEAR", "Dmnl"));

        // Variables
        builder.variable(new VariableDef("cost", "cost", "fixed_cost + sales * marginal_cost", "$/Month"));
        builder.variable(new VariableDef("discards", "discards", "Stock_of_Goods/average_life_of_goods", "Pair/Month"));
        builder.variable(new VariableDef("effect price target", "effect price target", "LOOKUP(effect_price_target_lookup, Price/reference_price)", "Dmnl"));
        builder.variable(new VariableDef("markup", "markup", "revenue/cost", "Dmnl"));
        builder.variable(new VariableDef("price change", "price change", "(target_price - Price)/time_to_adjust_price", "$/Pair/Month"));
        builder.variable(new VariableDef("purchases", "purchases", "MAX(0, discards + (target_stock_of_goods - Stock_of_Goods)/time_to_adjust_goods)", "Pair/Month"));
        builder.variable(new VariableDef("revenue", "revenue", "sales*Price", "$/Month"));
        builder.variable(new VariableDef("sales", "sales", "purchases", "Pair/Month"));
        builder.variable(new VariableDef("target price", "target price", "Price * target_markup/Average_Markup", "$/Pair"));
        builder.variable(new VariableDef("target stock of goods", "target stock of goods", "normal_target * effect_price_target", "Pair"));

        // Flows
        builder.flow(new FlowDef("Average Markup net flow", "Net flow for Average Markup", "(markup-Average_Markup)/time_for_average_markup", "Month", null, "Average Markup"));
        builder.flow(new FlowDef("Price net flow", "Net flow for Price", "price_change", "Month", null, "Price"));
        builder.flow(new FlowDef("Stock of Goods inflow 1", null, "purchases", "Month", null, "Stock of Goods"));
        builder.flow(new FlowDef("Stock of Goods outflow 2", null, "discards", "Month", "Stock of Goods", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
