/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.epidemiology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: 0608PneumonicPlagueChinaA.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _412</li>
 *   <li>View 'View 1' places non-existent element: _140</li>
 *   <li>View 'View 1' places non-existent element: _348</li>
 *   <li>View 'View 1' connector references non-existent element: _412</li>
 *   <li>View 'View 1' connector references non-existent element: _140</li>
 *   <li>View 'View 1' connector references non-existent element: _412</li>
 *   <li>View 'View 1' flow route references non-existent flow: _412</li>
 *   <li>View 'View 1' flow route references non-existent flow: _140</li>
 *   <li>View 'View 1' flow route references non-existent flow: _348</li>
 * </ul>
 */
public class PneumonicPlague {

    public static void main(String[] args) {
        new PneumonicPlague().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0608PneumonicPlagueChinaA")
                .defaultSimulation("Week", 6.0, "Week", 0.0625);

        // Stocks
        builder.stock(new StockDef("susceptible population", "susceptible population", 0.0, "initial_total_population-infected_population", "persons", null, List.of()));
        builder.stock(new StockDef("infected population", "infected population", 1.0, "persons", null));
        builder.stock(new StockDef("recovering population", "recovering population", 0.0, "persons", null));
        builder.stock(new StockDef("deceased population", "deceased population", 0.0, "persons", null));

        // Constants
        builder.constant("fatality ratio", 0.9, "Dmnl");
        builder.constant("initial total population", 10000.0, "persons");
        builder.constant("contact rate", 20.0, "persons/persons/Week");
        builder.constant("recovery time", 0.33, "Week");
        builder.constant("infection ratio", 0.75, "persons/persons");

        // Variables
        builder.variable(new VariableDef("infection", "infection", "contact_rate*infection_ratio*susceptible_population*infected_fraction", "persons/Week"));
        builder.variable(new VariableDef("infected fraction", "infected fraction", "infected_population/total_population", "Dmnl"));
        builder.variable(new VariableDef("total population", "total population", "infected_population+recovering_population+susceptible_population", "persons"));
        builder.variable(new VariableDef("recovery", "recovery", "(1-fatality_ratio)*infected_population/recovery_time", "persons/Week"));
        builder.variable(new VariableDef("deaths", "deaths", "infected_population*fatality_ratio/recovery_time", "persons/Week"));

        // Flows
        builder.flow(new FlowDef("susceptible population net flow", "Net flow for susceptible population", "-infection", "Week", null, "susceptible population"));
        builder.flow(new FlowDef("infected population inflow 1", null, "infection", "Week", null, "infected population"));
        builder.flow(new FlowDef("infected population outflow 2", null, "recovery", "Week", "infected population", null));
        builder.flow(new FlowDef("infected population outflow 3", null, "deaths", "Week", "infected population", null));
        builder.flow(new FlowDef("recovering population net flow", "Net flow for recovering population", "recovery", "Week", null, "recovering population"));
        builder.flow(new FlowDef("deceased population net flow", "Net flow for deceased population", "deaths", "Week", null, "deceased population"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
