/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.urban;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: WORLDAPP.mdl
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Lookup 'quality crowding mult tab': sorted non-monotonic x-values</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'Population &amp; Food' places non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' places non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: 6</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: 4</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' connector references non-existent element: _0</li>
 *   <li>View 'Population &amp; Food' flow route references non-existent flow: _0</li>
 *   <li>View 'Population &amp; Food' flow route references non-existent flow: _0</li>
 *   <li>View 'Capital &amp; Quality Life' places non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' places non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' places non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: 24</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: 2</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: _0</li>
 *   <li>View 'Capital &amp; Quality Life' connector references non-existent element: 7</li>
 *   <li>View 'Capital &amp; Quality Life' flow route references non-existent flow: _0</li>
 *   <li>View 'Capital &amp; Quality Life' flow route references non-existent flow: _0</li>
 *   <li>View 'Capital &amp; Quality Life' flow route references non-existent flow: _0</li>
 *   <li>View 'Pollution &amp; Resource' places non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' places non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' places non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: 16</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: 17</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: 4</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' connector references non-existent element: _0</li>
 *   <li>View 'Pollution &amp; Resource' flow route references non-existent flow: _0</li>
 *   <li>View 'Pollution &amp; Resource' flow route references non-existent flow: _0</li>
 *   <li>View 'Pollution &amp; Resource' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class WorldApp {

    public static void main(String[] args) {
        new WorldApp().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("WORLDAPP")
                .defaultSimulation("Year", 200.0, "Year", 0.25);

        defineStocks(builder);
        defineConstants(builder);
        defineLookupTables(builder);
        defineVariables(builder);
        defineFlows(builder);

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }

    private void defineStocks(ModelDefinitionBuilder builder) {
        builder.stock(new StockDef("Capital Agriculture Fraction", "The fraction of capital in agriculture.", 0.2, "Dimensionless", null));
        builder.stock(new StockDef("Capital", "The capital stock.", 4.0E8, "Capital units", null));
        builder.stock(new StockDef("Natural Resources", "The amount of natural resources remaining.", 9.0E11, "Resource units", null));
        builder.stock(new StockDef("Pollution", "The amount of non-incorporated pollution.", 2.0E8, "Pollution units", null));
        builder.stock(new StockDef("Population", "World population.", 1.65E9, "People", null));
    }

    private void defineConstants(ModelDefinitionBuilder builder) {
        builder.constant("TIME_STEP", 0.25, "Year");
        builder.constant("INITIAL_TIME", 1900.0, "Year");
        builder.constant("FINAL_TIME", 2100.0, "Year");
        builder.constant("capital investment rate normal c", 0.05, "Capital units / Person / Year");
        builder.constant("natural resource utilization normal c", 1.0, "Resource units / Person / Year");
        builder.constant("birth rate normal", 0.04, "1 / Year");
        builder.constant("capital agriculture fraction adjustment time", 15.0, "Year");
        builder.constant("capital agriculture fraction initial", 0.2, "Dimensionless");
        builder.constant("capital agriculture fraction normal", 0.3, "Dimensionless");
        builder.constant("capital depreciation normal", 0.025, "1 / Year");
        builder.constant("capital initial", 4.0E8, "Capital units");
        builder.constant("death rate normal", 0.028, "1 / Year");
        builder.constant("effective capital ratio normal", 1.0, "Capital units / Person");
        builder.constant("food coefficient", 1.0, "Dimensionless");
        builder.constant("food per capita normal", 1.0, "Food units / Person / Year");
        builder.constant("land area", 1.35E8, "Kilometer * Kilometer");
        builder.constant("natural resources initial", 9.0E11, "Resource units");
        builder.constant("pollution initial", 2.0E8, "Pollution units");
        builder.constant("pollution per capita normal", 1.0, "Pollution units / Person / Year");
        builder.constant("pollution standard", 3.6E9, "Pollution units");
        builder.constant("population density normal", 26.5, "Person / ( Kilometer * Kilometer )");
        builder.constant("population initial", 1.65E9, "People");
        builder.constant("quality of life normal", 1.0, "Satisfaction units");
    }

    private void defineLookupTables(ModelDefinitionBuilder builder) {
        builder.lookupTable(new LookupTableDef("births crowding mult tab", "The table for the effect of crowding on the number of\n\t\t         births.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}, new double[]{1.05, 1.0, 0.9, 0.7, 0.6, 0.55}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("births food mult tab", "The table for the effect of food on the number of births.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0}, new double[]{0.0, 1.0, 1.6, 1.9, 2.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("births material mult tab", "Table for the effect of the material standard of living on\n\t\t         births.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}, new double[]{1.2, 1.0, 0.85, 0.75, 0.7, 0.7}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("births pollution mult tab", "The table for the effect of pollution on the number of\n\t\t         births.", new double[]{0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0}, new double[]{1.02, 0.9, 0.7, 0.4, 0.25, 0.15, 0.1}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("capital agriculture fraction indicated tab", "The fraction of capital that should be agricultural as\n\t\t         indicated by\n\t\t         the availability of food table.", new double[]{0.0, 0.5, 1.0, 1.5, 2.0}, new double[]{1.0, 0.6, 0.3, 0.15, 0.1}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("capital investment mult tab", "Multiplier for the effect of the material standard of\n\t\t         living on\n\t\t         capital investment table.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}, new double[]{0.1, 1.0, 1.8, 2.4, 2.8, 3.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("capital investment quality ratio tab", "Capital investment from quality table.", new double[]{0.0, 0.5, 1.0, 1.5, 2.0}, new double[]{0.7, 0.8, 1.0, 1.5, 2.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("deaths crowding mult tab", "The table for the effect of crowding on the number of\n\t\t         deaths.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}, new double[]{0.9, 1.0, 1.2, 1.5, 1.9, 3.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("deaths food mult tab", "The table for the effect of food on the number of deaths.", new double[]{0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0}, new double[]{30.0, 3.0, 2.0, 1.4, 1.0, 0.7, 0.6, 0.5, 0.5}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("deaths material mult tab", "Table for the effect of the material standard of living on\n\t\t         deaths.", new double[]{0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0}, new double[]{3.0, 1.8, 1.0, 0.8, 0.7, 0.6, 0.53, 0.5, 0.5, 0.5, 0.5}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("deaths pollution mult tab", "The table for the effect of pollution on the number of\n\t\t         deaths.", new double[]{0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0}, new double[]{0.92, 1.3, 2.0, 3.2, 4.8, 6.8, 9.2}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("food crowding mult tab", "The table for the effect of crowding on the production of\n\t\t         food.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}, new double[]{2.4, 1.0, 0.6, 0.4, 0.3, 0.2}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("food per capita potential tab", "The potential amount of food that can be grown based on\n\t\t         capital\n\t\t         investment table.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0}, new double[]{0.5, 1.0, 1.4, 1.7, 1.9, 2.05, 2.2}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("food pollution mult tab", "The effect of pollution on the ability to grow food table.", new double[]{0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0}, new double[]{1.02, 0.9, 0.65, 0.35, 0.2, 0.1, 0.05}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("natural resource extraction mult tab", "Table for the multiplier on effective capital investment\n\t\t         from\n\t\t         remaining natural resources.", new double[]{0.0, 0.25, 0.5, 0.75, 1.0}, new double[]{0.0, 0.15, 0.5, 0.85, 1.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("natural resource material mult tab", "Table for the effect of the material well being on natural\n\t\t         resoure\n\t\t         use.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0}, new double[]{0.0, 1.0, 1.8, 2.4, 2.9, 3.3, 3.6, 3.8, 3.9, 3.95, 4.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("pollution absorption time tab", "The time it takes to incorporate pollution back into the\n\t\t         environment\n\t\t         table.", new double[]{0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0}, new double[]{0.6, 2.5, 5.0, 8.0, 11.5, 15.5, 20.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("pollution capital mult tab", "The effect of capital on pollution generation table.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}, new double[]{0.05, 1.0, 3.0, 5.4, 7.4, 8.0}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("quality crowding mult tab", "The table for the effect of crowding on the quality of\n\t\t         life.", new double[]{0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 5.5}, new double[]{2.0, 1.3, 1.0, 0.75, 0.55, 0.45, 0.38, 0.3, 0.25, 0.2, 0.22}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("quality food mult tab", "The table for the effect of food on the quality of life.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0}, new double[]{0.0, 1.0, 1.8, 2.4, 2.7}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("quality material mult tab", "Table for the effect of the material standard of living on\n\t\t         quality of\n\t\t         life.", new double[]{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}, new double[]{0.2, 1.0, 1.7, 2.3, 2.7, 2.9}, "LINEAR"));
        builder.lookupTable(new LookupTableDef("quality pollution mult tab", "The table for the effect of pollution on the quality of\n\t\t         life.", new double[]{0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0}, new double[]{1.04, 0.85, 0.5, 0.3, 0.15, 0.05, 0.02}, "LINEAR"));
    }

    private void defineVariables(ModelDefinitionBuilder builder) {
        builder.variable(new VariableDef("natural resource utilization normal", "The normal rate of natural resources.", "natural_resource_utilization_normal_c", "Resource units / Person / Year"));
        builder.variable(new VariableDef("capital investment rate normal", "The normal per capita rate of capital investment.", "capital_investment_rate_normal_c", "Capital units / Person / Year"));
        builder.variable(new VariableDef("capital depreciation", "The rate at which the capital stock depreciates.", "Capital * capital_depreciation_normal", "Capital units / Year"));
        builder.variable(new VariableDef("food ratio", "The ration of food available to required food.", "food_per_capita_potential * food_crowding_multiplier * food_pollution_multiplier * food_coefficient / food_per_capita_normal", "Dimensionless"));
        builder.variable(new VariableDef("births", "The total number of births.", "Population * birth_rate_normal * births_material_multiplier * births_crowding_multiplier * births_food_multiplier * births_pollution_multiplier", "People / Year"));
        builder.variable(new VariableDef("pollution generation", "The rate at which non-ncorporate poltion changes.", "Population * pollution_per_capita_normal * pollution_capital_multiplier", "Pollution units / Year"));
        builder.variable(new VariableDef("natural resource utilization", "The rate of natural resource utilization.", "Population * natural_resource_utilization_normal * nat_res_matl_multiplier", "Resource units / Year"));
        builder.variable(new VariableDef("deaths", "The worldwide number of deaths occurring.", "Population * death_rate_normal * deaths_material_multiplier * deaths_pollution_multiplier * deaths_food_multiplier * deaths_crowding_multiplier", "People / Year"));
        builder.variable(new VariableDef("capital investment", "The gross amount of investment in capital.", "Population * capital_investment_multiplier * capital_investment_rate_normal", "Capital units / Year"));
        builder.variable(new VariableDef("births crowding multiplier", "The effect of crowding on the number of births.", "LOOKUP(births_crowding_mult_tab, crowding)", "Dimensionless"));
        builder.variable(new VariableDef("births food multiplier", "The effect of food on the number of births.", "LOOKUP(births_food_mult_tab, food_ratio)", "Dimensionless"));
        builder.variable(new VariableDef("births material multiplier", "The effect of the material standard of living on births.", "LOOKUP(births_material_mult_tab, material_standard_of_living)", "Dimensionless"));
        builder.variable(new VariableDef("births pollution multiplier", "The effect of pollution on the number of births.", "LOOKUP(births_pollution_mult_tab, pollution_ratio)", "Dimensionless"));
        builder.variable(new VariableDef("capital agriculture fraction indicated", "The fraction of capital that should be agricultural as\n\t\t         indicated by\n\t\t         the availability of food.", "LOOKUP(capital_agriculture_fraction_indicated_tab, food_ratio)", "Dimensionless"));
        builder.variable(new VariableDef("capital investment from quality ratio", "Capital investment from quality.", "LOOKUP(capital_investment_quality_ratio_tab, quality_material_multiplier / quality_food_multiplier)", "Dimensionless"));
        builder.variable(new VariableDef("capital investment multiplier", "Multiplier for the effect of the material standard of\n\t\t         living on\n\t\t         capital investment.", "LOOKUP(capital_investment_mult_tab, material_standard_of_living)", "Dimensionless"));
        builder.variable(new VariableDef("capital ratio", "The capital investment ratio (per capita investment).", "Capital / Population", "Capital units / Person"));
        builder.variable(new VariableDef("capital ratio agriculture", "The capital investment ratio in agriculure.", "capital_ratio * Capital_Agriculture_Fraction / capital_agriculture_fraction_normal", "Capital units / Person"));
        builder.variable(new VariableDef("crowding", "The ratio oioulation to normally supportable population\n\t\t         used as a\n\t\t         measure of crowding.", "Population / ( land_area * population_density_normal )", "Dimensionless"));
        builder.variable(new VariableDef("deaths crowding multiplier", "The effect of crowding on the number of deaths.", "LOOKUP(deaths_crowding_mult_tab, crowding)", "Dimensionless"));
        builder.variable(new VariableDef("deaths food multiplier", "The effect of food on the number of deaths.", "LOOKUP(deaths_food_mult_tab, food_ratio)", "Dimensionless"));
        builder.variable(new VariableDef("deaths material multiplier", "The effect of the material standard of living on deaths.", "LOOKUP(deaths_material_mult_tab, material_standard_of_living)", "Dimensionless"));
        builder.variable(new VariableDef("deaths pollution multiplier", "The effect of pollution on the number of deaths.", "LOOKUP(deaths_pollution_mult_tab, pollution_ratio)", "Dimensionless"));
        builder.variable(new VariableDef("effective capital ratio", "The effective ratio between capital and investment.", "capital_ratio * natural_resource_extraction_multiplier * ( 1 - Capital_Agriculture_Fraction ) / ( 1 - capital_agriculture_fraction_normal )", "Capital units / Person"));
        builder.variable(new VariableDef("food crowding multiplier", "The effect of crowding on the production of food.", "LOOKUP(food_crowding_mult_tab, crowding)", "Dimensionless"));
        builder.variable(new VariableDef("food per capita potential", "The potential amount of food that can be grown based on\n\t\t         capital\n\t\t         investment.", "LOOKUP(food_per_capita_potential_tab, capital_ratio_agriculture)", "Food units / Person / Year"));
        builder.variable(new VariableDef("food pollution multiplier", "The effect of pollution on the ability to grow food.", "LOOKUP(food_pollution_mult_tab, pollution_ratio)", "Dimensionless"));
        builder.variable(new VariableDef("material standard of living", "The relative material standard of living.", "effective_capital_ratio / effective_capital_ratio_normal", "Dimensionless"));
        builder.variable(new VariableDef("natural resource fraction remaining", "The fraction of natural resource still remaining.", "Natural_Resources / natural_resources_initial", "Dimensionless"));
        builder.variable(new VariableDef("nat res matl multiplier", "The effect of the material well being on natural resource\n\t\t         use.", "LOOKUP(natural_resource_material_mult_tab, material_standard_of_living)", "Dimensionless"));
        builder.variable(new VariableDef("natural resource extraction multiplier", "The multiplier on effective capital investment from\n\t\t         remaining natural\n\t\t         resources.", "LOOKUP(natural_resource_extraction_mult_tab, natural_resource_fraction_remaining)", "Dimensionless"));
        builder.variable(new VariableDef("pollution absorption", "The rate at which pollution is reincorporated into the\n\t\t         ecology.", "Pollution / pollution_absorption_time", "Pollution units / Year"));
        builder.variable(new VariableDef("pollution absorption time", "The time it takes to incorporate pollution back into the\n\t\t         environment.", "LOOKUP(pollution_absorption_time_tab, pollution_ratio)", "Year"));
        builder.variable(new VariableDef("pollution capital multiplier", "The effect of capital on pollution generation.", "LOOKUP(pollution_capital_mult_tab, capital_ratio)", "Dimensionless"));
        builder.variable(new VariableDef("pollution ratio", "The ration of pollution to standard.", "Pollution / pollution_standard", "Dimensionless"));
        builder.variable(new VariableDef("quality crowding multiplier", "The effect of crowding on the quality of life.", "LOOKUP(quality_crowding_mult_tab, crowding)", "Dimensionless"));
        builder.variable(new VariableDef("quality food multiplier", "The effect of food on the quality of life.", "LOOKUP(quality_food_mult_tab, food_ratio)", "Dimensionless"));
        builder.variable(new VariableDef("quality material multiplier", "The effect of the material standard of living on the\n\t\t         quality of life.", "LOOKUP(quality_material_mult_tab, material_standard_of_living)", "Dimensionless"));
        builder.variable(new VariableDef("quality of life", "The quality of life.", "quality_of_life_normal * quality_material_multiplier * quality_crowding_multiplier * quality_food_multiplier * quality_pollution_multiplier", "Satisfaction units"));
        builder.variable(new VariableDef("quality pollution multiplier", "The effect of pollution on the quality of life.", "LOOKUP(quality_pollution_mult_tab, pollution_ratio)", "Dimensionless"));
    }

    private void defineFlows(ModelDefinitionBuilder builder) {
        builder.flow(new FlowDef("Capital Agriculture Fraction net flow", "Net flow for Capital Agriculture Fraction", "( capital_agriculture_fraction_indicated * capital_investment_from_quality_ratio - Capital_Agriculture_Fraction ) / capital_agriculture_fraction_adjustment_time", "Year", null, "Capital Agriculture Fraction"));
        builder.flow(new FlowDef("Capital inflow 1", null, "capital_investment", "Year", null, "Capital"));
        builder.flow(new FlowDef("Capital outflow 2", null, "capital_depreciation", "Year", "Capital", null));
        builder.flow(new FlowDef("Natural Resources net flow", "Net flow for Natural Resources", "- natural_resource_utilization", "Year", null, "Natural Resources"));
        builder.flow(new FlowDef("Pollution inflow 1", null, "pollution_generation", "Year", null, "Pollution"));
        builder.flow(new FlowDef("Pollution outflow 2", null, "pollution_absorption", "Year", "Pollution", null));
        builder.flow(new FlowDef("Population inflow 1", null, "births", "Year", null, "Population"));
        builder.flow(new FlowDef("Population outflow 2", null, "deaths", "Year", "Population", null));
    }
}
