/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.userguidechap17complete;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: PROJ2.MDL
 * Source: Vensim User Guide Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: Work To Do</li>
 *   <li>View 'View 1' places non-existent element: task size</li>
 *   <li>View 'View 1' places non-existent element: task is active</li>
 *   <li>View 'View 1' places non-existent element: Work Done</li>
 *   <li>View 'View 1' places non-existent element: _172</li>
 *   <li>View 'View 1' places non-existent element: work accomplishment</li>
 *   <li>View 'View 1' places non-existent element: max work accomplishment</li>
 *   <li>View 'View 1' connector references non-existent element: _172</li>
 *   <li>View 'View 1' connector references non-existent element: Work Done</li>
 *   <li>View 'View 1' connector references non-existent element: _172</li>
 *   <li>View 'View 1' connector references non-existent element: Work To Do</li>
 *   <li>View 'View 1' connector references non-existent element: max work accomplishment</li>
 *   <li>View 'View 1' connector references non-existent element: work accomplishment</li>
 *   <li>View 'View 1' connector references non-existent element: Work Done</li>
 *   <li>View 'View 1' connector references non-existent element: task is active</li>
 *   <li>View 'View 1' connector references non-existent element: task size</li>
 *   <li>View 'View 1' connector references non-existent element: Work To Do</li>
 *   <li>View 'View 1' connector references non-existent element: task is active</li>
 *   <li>View 'View 1' connector references non-existent element: _172</li>
 *   <li>View 'View 1' connector references non-existent element: task size</li>
 *   <li>View 'View 1' connector references non-existent element: task is active</li>
 *   <li>View 'View 1' flow route references non-existent flow: _172</li>
 * </ul>
 */
public class VensimProj2 {

    public static void main(String[] args) {
        new VensimProj2().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("PROJ2")
                .defaultSimulation("Month", 100.0, "Month", 0.125);

        // Stocks
        builder.stock(new StockDef("Work Done design", "Work Done[task]", 0.0, "Drawing", null));
        builder.stock(new StockDef("Work Done prototype", "Work Done[task]", 0.0, "Drawing", null));
        builder.stock(new StockDef("Work Done build", "Work Done[task]", 0.0, "Drawing", null));
        builder.stock(new StockDef("Work To Do design", "Work To Do[task]", 180.0, "Drawing", null));
        builder.stock(new StockDef("Work To Do prototype", "Work To Do[task]", 250.0, "Drawing", null));
        builder.stock(new StockDef("Work To Do build", "Work To Do[task]", 500.0, "Drawing", null));

        // Constants
        builder.constant("max work accomplishment design", 8.0, "Drawing/Month");
        builder.constant("max work accomplishment prototype", 10.0, "Drawing/Month");
        builder.constant("max work accomplishment build", 15.0, "Drawing/Month");
        builder.constant("task size design", 180.0, "Drawing");
        builder.constant("task size prototype", 250.0, "Drawing");
        builder.constant("task size build", 500.0, "Drawing");

        // Variables
        builder.variable(new VariableDef("total work done", "total work done", "(Work_Done_design + Work_Done_prototype + Work_Done_build)", "Drawing"));
        builder.variable(new VariableDef("work accomplishment design", "work accomplishment[task]", "max_work_accomplishment_design * task_is_active_design", "Drawing/Month"));
        builder.variable(new VariableDef("work accomplishment prototype", "work accomplishment[task]", "max_work_accomplishment_prototype * task_is_active_prototype", "Drawing/Month"));
        builder.variable(new VariableDef("work accomplishment build", "work accomplishment[task]", "max_work_accomplishment_build * task_is_active_build", "Drawing/Month"));
        builder.variable(new VariableDef("task is active design", "task is active[task]", "IF( Work_Done_design < task_size_design, 1, 0)", "Dmnl"));
        builder.variable(new VariableDef("task is active prototype", "task is active[task]", "IF( Work_Done_prototype < task_size_prototype, 1, 0)", "Dmnl"));
        builder.variable(new VariableDef("task is active build", "task is active[task]", "IF( Work_Done_build < task_size_build, 1, 0)", "Dmnl"));

        // Flows
        builder.flow(new FlowDef("Work Done design net flow", "Net flow for Work Done design", "work_accomplishment_design", "Month", null, "Work Done design"));
        builder.flow(new FlowDef("Work Done prototype net flow", "Net flow for Work Done prototype", "work_accomplishment_prototype", "Month", null, "Work Done prototype"));
        builder.flow(new FlowDef("Work Done build net flow", "Net flow for Work Done build", "work_accomplishment_build", "Month", null, "Work Done build"));
        builder.flow(new FlowDef("Work To Do design net flow", "Net flow for Work To Do design", "- work_accomplishment_design", "Month", null, "Work To Do design"));
        builder.flow(new FlowDef("Work To Do prototype net flow", "Net flow for Work To Do prototype", "- work_accomplishment_prototype", "Month", null, "Work To Do prototype"));
        builder.flow(new FlowDef("Work To Do build net flow", "Net flow for Work To Do build", "- work_accomplishment_build", "Month", null, "Work To Do build"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim User Guide Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
