/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.causalloop;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;

/**
 * Imported from: 0210ConflictInMiddleEast.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: trust Isi in Paln</li>
 *   <li>View 'View 1' places non-existent element: trust Paln in Isi</li>
 *   <li>View 'View 1' places non-existent element: successful suicide attacks</li>
 *   <li>View 'View 1' places non-existent element: living conditions Palestinians</li>
 *   <li>View 'View 1' places non-existent element: restrictions on Palestinians</li>
 *   <li>View 'View 1' places non-existent element: reprisal Isi on Paln</li>
 *   <li>View 'View 1' places non-existent element: security by shielding wall</li>
 *   <li>View 'View 1' places non-existent element: willingness suicide attacks</li>
 *   <li>View 'View 1' places non-existent element: progress peace process</li>
 *   <li>View 'View 1' places non-existent element: preparedness to dialogue</li>
 *   <li>View 'View 1' places non-existent element: autonomy Palestinians</li>
 *   <li>View 'View 1' places non-existent element: chance of success of peace process</li>
 *   <li>View 'View 1' places non-existent element: degree of equality in negotiations</li>
 *   <li>View 'View 1' connector references non-existent element: trust Isi in Paln</li>
 *   <li>View 'View 1' connector references non-existent element: restrictions on Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: restrictions on Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: living conditions Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: successful suicide attacks</li>
 *   <li>View 'View 1' connector references non-existent element: trust Isi in Paln</li>
 *   <li>View 'View 1' connector references non-existent element: successful suicide attacks</li>
 *   <li>View 'View 1' connector references non-existent element: reprisal Isi on Paln</li>
 *   <li>View 'View 1' connector references non-existent element: reprisal Isi on Paln</li>
 *   <li>View 'View 1' connector references non-existent element: living conditions Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: trust Isi in Paln</li>
 *   <li>View 'View 1' connector references non-existent element: security by shielding wall</li>
 *   <li>View 'View 1' connector references non-existent element: security by shielding wall</li>
 *   <li>View 'View 1' connector references non-existent element: successful suicide attacks</li>
 *   <li>View 'View 1' connector references non-existent element: security by shielding wall</li>
 *   <li>View 'View 1' connector references non-existent element: living conditions Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: living conditions Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: willingness suicide attacks</li>
 *   <li>View 'View 1' connector references non-existent element: willingness suicide attacks</li>
 *   <li>View 'View 1' connector references non-existent element: successful suicide attacks</li>
 *   <li>View 'View 1' connector references non-existent element: living conditions Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: preparedness to dialogue</li>
 *   <li>View 'View 1' connector references non-existent element: trust Paln in Isi</li>
 *   <li>View 'View 1' connector references non-existent element: preparedness to dialogue</li>
 *   <li>View 'View 1' connector references non-existent element: trust Isi in Paln</li>
 *   <li>View 'View 1' connector references non-existent element: preparedness to dialogue</li>
 *   <li>View 'View 1' connector references non-existent element: preparedness to dialogue</li>
 *   <li>View 'View 1' connector references non-existent element: progress peace process</li>
 *   <li>View 'View 1' connector references non-existent element: reprisal Isi on Paln</li>
 *   <li>View 'View 1' connector references non-existent element: trust Paln in Isi</li>
 *   <li>View 'View 1' connector references non-existent element: living conditions Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: degree of equality in negotiations</li>
 *   <li>View 'View 1' connector references non-existent element: degree of equality in negotiations</li>
 *   <li>View 'View 1' connector references non-existent element: chance of success of peace process</li>
 *   <li>View 'View 1' connector references non-existent element: chance of success of peace process</li>
 *   <li>View 'View 1' connector references non-existent element: progress peace process</li>
 *   <li>View 'View 1' connector references non-existent element: progress peace process</li>
 *   <li>View 'View 1' connector references non-existent element: autonomy Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: autonomy Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: living conditions Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: autonomy Palestinians</li>
 *   <li>View 'View 1' connector references non-existent element: successful suicide attacks</li>
 *   <li>View 'View 1' connector references non-existent element: progress peace process</li>
 *   <li>View 'View 1' connector references non-existent element: trust Paln in Isi</li>
 *   <li>View 'View 1' connector references non-existent element: progress peace process</li>
 *   <li>View 'View 1' connector references non-existent element: trust Isi in Paln</li>
 * </ul>
 */
public class ConflictMiddleEast {

    public static void main(String[] args) {
        new ConflictMiddleEast().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0210ConflictInMiddleEast")
                .defaultSimulation("Year", 120.0, "Year");

        // Constants
        builder.constant("TIME_STEP", 1.0, "Year");
        builder.constant("INITIAL_TIME", 1980.0, "Year");
        builder.constant("FINAL_TIME", 2100.0, "Year");

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
