/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.causalloop;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;

/**
 * Imported from: CUSTOMER.MDL
 * Source: Vensim User's Guide
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: Customers</li>
 *   <li>View 'View 1' places non-existent element: Potential Customers</li>
 *   <li>View 'View 1' places non-existent element: _316</li>
 *   <li>View 'View 1' places non-existent element: new customers</li>
 *   <li>View 'View 1' places non-existent element: _236</li>
 *   <li>View 'View 1' places non-existent element: exiting customers</li>
 *   <li>View 'View 1' places non-existent element: time to become customer</li>
 *   <li>View 'View 1' places non-existent element: product life</li>
 *   <li>View 'View 1' places non-existent element: Awareness</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: gaining awareness</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: forgetting</li>
 *   <li>View 'View 1' places non-existent element: advertising effectiveness</li>
 *   <li>View 'View 1' places non-existent element: customer referral</li>
 *   <li>View 'View 1' places non-existent element: time to forget</li>
 *   <li>View 'View 1' places non-existent element: effect of awareness on new customers</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: Customers</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: Potential Customers</li>
 *   <li>View 'View 1' connector references non-existent element: 9</li>
 *   <li>View 'View 1' connector references non-existent element: Potential Customers</li>
 *   <li>View 'View 1' connector references non-existent element: 9</li>
 *   <li>View 'View 1' connector references non-existent element: Customers</li>
 *   <li>View 'View 1' connector references non-existent element: Potential Customers</li>
 *   <li>View 'View 1' connector references non-existent element: _316</li>
 *   <li>View 'View 1' connector references non-existent element: time to become customer</li>
 *   <li>View 'View 1' connector references non-existent element: new customers</li>
 *   <li>View 'View 1' connector references non-existent element: Customers</li>
 *   <li>View 'View 1' connector references non-existent element: _236</li>
 *   <li>View 'View 1' connector references non-existent element: product life</li>
 *   <li>View 'View 1' connector references non-existent element: exiting customers</li>
 *   <li>View 'View 1' connector references non-existent element: 21</li>
 *   <li>View 'View 1' connector references non-existent element: Awareness</li>
 *   <li>View 'View 1' connector references non-existent element: 21</li>
 *   <li>View 'View 1' connector references non-existent element: 18</li>
 *   <li>View 'View 1' connector references non-existent element: 26</li>
 *   <li>View 'View 1' connector references non-existent element: 23</li>
 *   <li>View 'View 1' connector references non-existent element: 26</li>
 *   <li>View 'View 1' connector references non-existent element: Awareness</li>
 *   <li>View 'View 1' connector references non-existent element: advertising effectiveness</li>
 *   <li>View 'View 1' connector references non-existent element: gaining awareness</li>
 *   <li>View 'View 1' connector references non-existent element: customer referral</li>
 *   <li>View 'View 1' connector references non-existent element: gaining awareness</li>
 *   <li>View 'View 1' connector references non-existent element: Awareness</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: Awareness</li>
 *   <li>View 'View 1' connector references non-existent element: effect of awareness on new customers</li>
 *   <li>View 'View 1' connector references non-existent element: effect of awareness on new customers</li>
 *   <li>View 'View 1' connector references non-existent element: _316</li>
 *   <li>View 'View 1' connector references non-existent element: Customers</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: time to forget</li>
 *   <li>View 'View 1' connector references non-existent element: forgetting</li>
 *   <li>View 'View 1' flow route references non-existent flow: _316</li>
 *   <li>View 'View 1' flow route references non-existent flow: _236</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class Customer {

    public static void main(String[] args) {
        new Customer().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("CUSTOMER")
                .defaultSimulation("Month", 100.0, "Month");

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim User's Guide")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
