/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.causalloop;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;

/**
 * Imported from: 0212EntrepreneursAndTransitionsEnV3simple.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: entrepreneurial motivation</li>
 *   <li>View 'View 1' places non-existent element: willingness to act</li>
 *   <li>View 'View 1' places non-existent element: willingness to invest</li>
 *   <li>View 'View 1' places non-existent element: favourability external factors</li>
 *   <li>View 'View 1' places non-existent element: perceived risk</li>
 *   <li>View 'View 1' places non-existent element: perceived certainty</li>
 *   <li>View 'View 1' places non-existent element: intrinsic entrepreneurial motivation</li>
 *   <li>View 'View 1' places non-existent element: success of actions</li>
 *   <li>View 'View 1' places non-existent element: investments</li>
 *   <li>View 'View 1' places non-existent element: perceived opportunity potential success</li>
 *   <li>View 'View 1' places non-existent element: success of investment</li>
 *   <li>View 'View 1' places non-existent element: real external delays</li>
 *   <li>View 'View 1' places non-existent element: resources for actions</li>
 *   <li>View 'View 1' places non-existent element: resources for investments</li>
 *   <li>View 'View 1' places non-existent element: real external delays</li>
 *   <li>View 'View 1' places non-existent element: stage of development</li>
 *   <li>View 'View 1' connector references non-existent element: entrepreneurial motivation</li>
 *   <li>View 'View 1' connector references non-existent element: willingness to act</li>
 *   <li>View 'View 1' connector references non-existent element: entrepreneurial motivation</li>
 *   <li>View 'View 1' connector references non-existent element: willingness to invest</li>
 *   <li>View 'View 1' connector references non-existent element: willingness to act</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: intrinsic entrepreneurial motivation</li>
 *   <li>View 'View 1' connector references non-existent element: entrepreneurial motivation</li>
 *   <li>View 'View 1' connector references non-existent element: investments</li>
 *   <li>View 'View 1' connector references non-existent element: perceived opportunity potential success</li>
 *   <li>View 'View 1' connector references non-existent element: success of investment</li>
 *   <li>View 'View 1' connector references non-existent element: perceived opportunity potential success</li>
 *   <li>View 'View 1' connector references non-existent element: resources for investments</li>
 *   <li>View 'View 1' connector references non-existent element: investments</li>
 *   <li>View 'View 1' connector references non-existent element: perceived opportunity potential success</li>
 *   <li>View 'View 1' connector references non-existent element: entrepreneurial motivation</li>
 *   <li>View 'View 1' connector references non-existent element: perceived certainty</li>
 *   <li>View 'View 1' connector references non-existent element: perceived risk</li>
 *   <li>View 'View 1' connector references non-existent element: real external delays</li>
 *   <li>View 'View 1' connector references non-existent element: entrepreneurial motivation</li>
 *   <li>View 'View 1' connector references non-existent element: 27</li>
 *   <li>View 'View 1' connector references non-existent element: perceived certainty</li>
 *   <li>View 'View 1' connector references non-existent element: resources for actions</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: perceived opportunity potential success</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: perceived certainty</li>
 *   <li>View 'View 1' connector references non-existent element: success of actions</li>
 *   <li>View 'View 1' connector references non-existent element: perceived opportunity potential success</li>
 *   <li>View 'View 1' connector references non-existent element: investments</li>
 *   <li>View 'View 1' connector references non-existent element: perceived certainty</li>
 *   <li>View 'View 1' connector references non-existent element: real external delays</li>
 *   <li>View 'View 1' connector references non-existent element: perceived certainty</li>
 *   <li>View 'View 1' connector references non-existent element: stage of development</li>
 *   <li>View 'View 1' connector references non-existent element: willingness to invest</li>
 *   <li>View 'View 1' connector references non-existent element: stage of development</li>
 *   <li>View 'View 1' connector references non-existent element: willingness to act</li>
 *   <li>View 'View 1' connector references non-existent element: willingness to invest</li>
 *   <li>View 'View 1' connector references non-existent element: investments</li>
 *   <li>View 'View 1' connector references non-existent element: perceived certainty</li>
 *   <li>View 'View 1' connector references non-existent element: perceived opportunity potential success</li>
 *   <li>View 'View 1' connector references non-existent element: perceived risk</li>
 *   <li>View 'View 1' connector references non-existent element: willingness to act</li>
 *   <li>View 'View 1' connector references non-existent element: perceived risk</li>
 *   <li>View 'View 1' connector references non-existent element: willingness to invest</li>
 *   <li>View 'View 1' connector references non-existent element: perceived certainty</li>
 *   <li>View 'View 1' connector references non-existent element: favourability external factors</li>
 *   <li>View 'View 1' connector references non-existent element: perceived certainty</li>
 *   <li>View 'View 1' connector references non-existent element: perceived risk</li>
 *   <li>View 'View 1' connector references non-existent element: stage of development</li>
 *   <li>View 'View 1' connector references non-existent element: 27</li>
 *   <li>View 'View 1' connector references non-existent element: 54</li>
 * </ul>
 */
public class EntrepreneursTransitions {

    public static void main(String[] args) {
        new EntrepreneursTransitions().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0212EntrepreneursAndTransitionsEnV3simple")
                .defaultSimulation("Year", 20.0, "Year", 0.0625);

        // Constants
        builder.constant("TIME_STEP", 0.0625, "Year");
        builder.constant("INITIAL_TIME", 2000.0, "Year");
        builder.constant("FINAL_TIME", 2020.0, "Year");

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
