/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.causalloop;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;

/**
 * Imported from: 0202Managing a Fitness Club CLD EN.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: number of members</li>
 *   <li>View 'View 1' places non-existent element: number of fitness devices</li>
 *   <li>View 'View 1' places non-existent element: average effective waiting time per device</li>
 *   <li>View 'View 1' places non-existent element: implicite maximum acceptable waiting time per device</li>
 *   <li>View 'View 1' places non-existent element: fraction of effective waiting time over desired waiting time</li>
 *   <li>View 'View 1' places non-existent element: nonrecurrent enrolment cost</li>
 *   <li>View 'View 1' places non-existent element: monthly membership contribution</li>
 *   <li>View 'View 1' places non-existent element: desired number of members</li>
 *   <li>View 'View 1' places non-existent element: fraction of number of members over desired number of members</li>
 *   <li>View 'View 1' places non-existent element: positive mouth to mouth publicity</li>
 *   <li>View 'View 1' places non-existent element: new members</li>
 *   <li>View 'View 1' places non-existent element: satisfaction</li>
 *   <li>View 'View 1' places non-existent element: dissatisfied cancellations</li>
 *   <li>View 'View 1' places non-existent element: desired waiting time</li>
 *   <li>View 'View 1' places non-existent element: more members less m2m publicity loop</li>
 *   <li>View 'View 1' places non-existent element: more members more m2m publicity loop</li>
 *   <li>View 'View 1' places non-existent element: more members more leavers loop</li>
 *   <li>View 'View 1' places non-existent element: more members higher nonrecurrent enrolment costs</li>
 *   <li>View 'View 1' connector references non-existent element: number of members</li>
 *   <li>View 'View 1' connector references non-existent element: average effective waiting time per device</li>
 *   <li>View 'View 1' connector references non-existent element: number of fitness devices</li>
 *   <li>View 'View 1' connector references non-existent element: average effective waiting time per device</li>
 *   <li>View 'View 1' connector references non-existent element: number of members</li>
 *   <li>View 'View 1' connector references non-existent element: fraction of number of members over desired number of members</li>
 *   <li>View 'View 1' connector references non-existent element: desired number of members</li>
 *   <li>View 'View 1' connector references non-existent element: fraction of number of members over desired number of members</li>
 *   <li>View 'View 1' connector references non-existent element: number of members</li>
 *   <li>View 'View 1' connector references non-existent element: positive mouth to mouth publicity</li>
 *   <li>View 'View 1' connector references non-existent element: positive mouth to mouth publicity</li>
 *   <li>View 'View 1' connector references non-existent element: new members</li>
 *   <li>View 'View 1' connector references non-existent element: fraction of number of members over desired number of members</li>
 *   <li>View 'View 1' connector references non-existent element: nonrecurrent enrolment cost</li>
 *   <li>View 'View 1' connector references non-existent element: nonrecurrent enrolment cost</li>
 *   <li>View 'View 1' connector references non-existent element: new members</li>
 *   <li>View 'View 1' connector references non-existent element: monthly membership contribution</li>
 *   <li>View 'View 1' connector references non-existent element: new members</li>
 *   <li>View 'View 1' connector references non-existent element: implicite maximum acceptable waiting time per device</li>
 *   <li>View 'View 1' connector references non-existent element: 34</li>
 *   <li>View 'View 1' connector references non-existent element: average effective waiting time per device</li>
 *   <li>View 'View 1' connector references non-existent element: fraction of effective waiting time over desired waiting time</li>
 *   <li>View 'View 1' connector references non-existent element: fraction of effective waiting time over desired waiting time</li>
 *   <li>View 'View 1' connector references non-existent element: satisfaction</li>
 *   <li>View 'View 1' connector references non-existent element: satisfaction</li>
 *   <li>View 'View 1' connector references non-existent element: positive mouth to mouth publicity</li>
 *   <li>View 'View 1' connector references non-existent element: satisfaction</li>
 *   <li>View 'View 1' connector references non-existent element: dissatisfied cancellations</li>
 *   <li>View 'View 1' connector references non-existent element: dissatisfied cancellations</li>
 *   <li>View 'View 1' connector references non-existent element: number of members</li>
 *   <li>View 'View 1' connector references non-existent element: new members</li>
 *   <li>View 'View 1' connector references non-existent element: number of members</li>
 *   <li>View 'View 1' connector references non-existent element: desired waiting time</li>
 *   <li>View 'View 1' connector references non-existent element: fraction of effective waiting time over desired waiting time</li>
 * </ul>
 */
public class ManagingFitnessClubCld {

    public static void main(String[] args) {
        new ManagingFitnessClubCld().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0202Managing a Fitness Club CLD EN")
                .defaultSimulation("Month", 100.0, "Month");

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
