/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.causalloop;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;

/**
 * Imported from: price1.mdl
 * Source: Vensim User's Guide
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: reference demand</li>
 *   <li>View 'View 1' places non-existent element: effect price demand</li>
 *   <li>View 'View 1' places non-existent element: price</li>
 *   <li>View 'View 1' places non-existent element: demand</li>
 *   <li>View 'View 1' places non-existent element: target price</li>
 *   <li>View 'View 1' places non-existent element: time to adjust price up</li>
 *   <li>View 'View 1' places non-existent element: target revenue</li>
 *   <li>View 'View 1' places non-existent element: demand elasticity</li>
 *   <li>View 'View 1' places non-existent element: initial price</li>
 *   <li>View 'View 1' places non-existent element: expected demand</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: change in price</li>
 *   <li>View 'View 1' places non-existent element: time to form expectations</li>
 *   <li>View 'View 1' places non-existent element: reference price</li>
 *   <li>View 'View 1' places non-existent element: time to adjust price down</li>
 *   <li>View 'View 1' connector references non-existent element: reference demand</li>
 *   <li>View 'View 1' connector references non-existent element: demand</li>
 *   <li>View 'View 1' connector references non-existent element: effect price demand</li>
 *   <li>View 'View 1' connector references non-existent element: demand</li>
 *   <li>View 'View 1' connector references non-existent element: price</li>
 *   <li>View 'View 1' connector references non-existent element: effect price demand</li>
 *   <li>View 'View 1' connector references non-existent element: demand elasticity</li>
 *   <li>View 'View 1' connector references non-existent element: effect price demand</li>
 *   <li>View 'View 1' connector references non-existent element: time to adjust price up</li>
 *   <li>View 'View 1' connector references non-existent element: 22</li>
 *   <li>View 'View 1' connector references non-existent element: 17</li>
 *   <li>View 'View 1' connector references non-existent element: target price</li>
 *   <li>View 'View 1' connector references non-existent element: target revenue</li>
 *   <li>View 'View 1' connector references non-existent element: target price</li>
 *   <li>View 'View 1' connector references non-existent element: 21</li>
 *   <li>View 'View 1' connector references non-existent element: price</li>
 *   <li>View 'View 1' connector references non-existent element: 21</li>
 *   <li>View 'View 1' connector references non-existent element: 18</li>
 *   <li>View 'View 1' connector references non-existent element: demand</li>
 *   <li>View 'View 1' connector references non-existent element: expected demand</li>
 *   <li>View 'View 1' connector references non-existent element: time to form expectations</li>
 *   <li>View 'View 1' connector references non-existent element: expected demand</li>
 *   <li>View 'View 1' connector references non-existent element: price</li>
 *   <li>View 'View 1' connector references non-existent element: change in price</li>
 *   <li>View 'View 1' connector references non-existent element: target price</li>
 *   <li>View 'View 1' connector references non-existent element: change in price</li>
 *   <li>View 'View 1' connector references non-existent element: reference price</li>
 *   <li>View 'View 1' connector references non-existent element: effect price demand</li>
 *   <li>View 'View 1' connector references non-existent element: time to adjust price down</li>
 *   <li>View 'View 1' connector references non-existent element: change in price</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class Price1 {

    public static void main(String[] args) {
        new Price1().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("price1")
                .defaultSimulation("Month", 100.0, "Month");

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim User's Guide")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
