/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.causalloop;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;

/**
 * Imported from: PROJECT.MDL
 * Source: Vensim User's Guide
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: work done</li>
 *   <li>View 'View 1' places non-existent element: overtime hours required</li>
 *   <li>View 'View 1' places non-existent element: quality of work</li>
 *   <li>View 'View 1' places non-existent element: fatigue</li>
 *   <li>View 'View 1' places non-existent element: required workforce</li>
 *   <li>View 'View 1' places non-existent element: actual workforce</li>
 *   <li>View 'View 1' places non-existent element: productivity</li>
 *   <li>View 'View 1' connector references non-existent element: quality of work</li>
 *   <li>View 'View 1' connector references non-existent element: work done</li>
 *   <li>View 'View 1' connector references non-existent element: overtime hours required</li>
 *   <li>View 'View 1' connector references non-existent element: overtime hours required</li>
 *   <li>View 'View 1' connector references non-existent element: work done</li>
 *   <li>View 'View 1' connector references non-existent element: overtime hours required</li>
 *   <li>View 'View 1' connector references non-existent element: fatigue</li>
 *   <li>View 'View 1' connector references non-existent element: fatigue</li>
 *   <li>View 'View 1' connector references non-existent element: quality of work</li>
 *   <li>View 'View 1' connector references non-existent element: productivity</li>
 *   <li>View 'View 1' connector references non-existent element: work done</li>
 *   <li>View 'View 1' connector references non-existent element: actual workforce</li>
 *   <li>View 'View 1' connector references non-existent element: work done</li>
 *   <li>View 'View 1' connector references non-existent element: required workforce</li>
 *   <li>View 'View 1' connector references non-existent element: actual workforce</li>
 *   <li>View 'View 1' connector references non-existent element: required workforce</li>
 * </ul>
 */
public class Project {

    public static void main(String[] args) {
        new Project().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("PROJECT")
                .defaultSimulation("Month", 100.0, "Month");

        // Constants
        builder.constant("TIME_STEP", 1.0, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 100.0, "Month");

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim User's Guide")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
