/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.policy;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: CFC.MDL
 * Source: Vensim User's Guide
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Data variable 'atmospheric CFC 11 releases' imported as constant 0 (external data source not supported)</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _140</li>
 *   <li>View 'View 1' places non-existent element: _220</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 2</li>
 *   <li>View 'View 1' connector references non-existent element: _140</li>
 *   <li>View 'View 1' connector references non-existent element: _140</li>
 *   <li>View 'View 1' connector references non-existent element: _220</li>
 *   <li>View 'View 1' connector references non-existent element: 4</li>
 *   <li>View 'View 1' connector references non-existent element: _220</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _140</li>
 *   <li>View 'View 1' flow route references non-existent flow: _220</li>
 * </ul>
 */
public class CFC {

    public static void main(String[] args) {
        new CFC().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("CFC")
                .defaultSimulation("Year", 200.0, "Year", 2.0);

        // Stocks
        builder.stock(new StockDef("CFC 11 in Troposphere", "CFC 11 in Troposphere", 0.0, "Mkg", null));
        builder.stock(new StockDef("CFC 11 in Stratosphere", "CFC 11 in Stratosphere", 0.0, "Mkg", null));

        // Constants
        builder.constant("TIME_STEP", 2.0, "Year");
        builder.constant("INITIAL_TIME", 1930.0, "Year");
        builder.constant("FINAL_TIME", 2130.0, "Year");
        builder.constant("atmospheric CFC 11 releases", 0.0, "Mkg/Year");
        builder.constant("lifetime of CFC 11 in stratosphere", 55.0, "Year");
        builder.constant("time to rise to stratosphere", 5.0, "Year");

        // Variables
        builder.variable(new VariableDef("CFC 11 destroyed", "CFC 11 destroyed", "CFC_11_in_Stratosphere / lifetime_of_CFC_11_in_stratosphere", "Mkg/Year"));
        builder.variable(new VariableDef("migration to stratosphere", "migration to stratosphere", "CFC_11_in_Troposphere / time_to_rise_to_stratosphere", "Mkg/Year"));

        // Flows
        builder.flow(new FlowDef("CFC 11 in Troposphere inflow 1", null, "atmospheric_CFC_11_releases", "Year", null, "CFC 11 in Troposphere"));
        builder.flow(new FlowDef("CFC 11 in Troposphere outflow 2", null, "migration_to_stratosphere", "Year", "CFC 11 in Troposphere", null));
        builder.flow(new FlowDef("CFC 11 in Stratosphere inflow 1", null, "migration_to_stratosphere", "Year", null, "CFC 11 in Stratosphere"));
        builder.flow(new FlowDef("CFC 11 in Stratosphere outflow 2", null, "CFC_11_destroyed", "Year", "CFC 11 in Stratosphere", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim User's Guide")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
