/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.policy;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 0601Cocaine_model.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Error processing '"."': Auxiliary name must not be blank</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class CocaineFlow {

    public static void main(String[] args) {
        new CocaineFlow().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0601Cocaine_model")
                .defaultSimulation("Month", 24.0, "Month", 0.0625);

        // Stocks
        builder.stock(new StockDef("Cocaine", "Cocaine", 20000.0, "kg", null));

        // Constants
        builder.constant("confiscation rate", 0.1, "1/Month");
        builder.constant("imports", 4000.0, "kg/Month");
        builder.constant("use", 3000.0, "kg/Month");

        // Variables
        builder.variable(new VariableDef("confiscation", "confiscation", "Cocaine*confiscation_rate", "kg/Month"));

        // Flows
        builder.flow(new FlowDef("Cocaine inflow 1", null, "imports", "Month", null, "Cocaine"));
        builder.flow(new FlowDef("Cocaine outflow 2", null, "confiscation", "Month", "Cocaine", null));
        builder.flow(new FlowDef("Cocaine outflow 3", null, "use", "Month", "Cocaine", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
