/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.userguidechap18calibrat;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: ELECTRIC.MDL
 * License: MIT
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _140</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _140</li>
 *   <li>View 'View 1' connector references non-existent element: _140</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _140</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class VensimElectric {

    public static void main(String[] args) {
        new VensimElectric().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("ELECTRIC")
                .defaultSimulation("Year", 70.0, "Year", 0.125);

        // Stocks
        builder.stock(new StockDef("Electric Households", "Electric Households", 0.0, "initial_fraction_electric * Total_US_Households", "Household", null, List.of()));
        builder.stock(new StockDef("Non Electric Households", "Non Electric Households", 0.0, "(1 - initial_fraction_electric) * Total_US_Households", "Household", null, List.of()));
        builder.stock(new StockDef("Total US Households", "Total US Households", 2.0E7, "Household", null));

        // Constants
        builder.constant("average household size", 4.0, "Person/Household");
        builder.constant("contact rate", 20.0, "Contact/Household/Year");
        builder.constant("conversion fraction", 0.01, "Household/Contact");
        builder.constant("household addition rate", 0.02, "1/Year");
        builder.constant("initial households", 2.0E7, "Household");
        builder.constant("initial fraction electric", 0.05, "Dmnl");

        // Variables
        builder.variable(new VariableDef("conversions", "conversions", "electric_to_non_electric_contacts * conversion_fraction", "Household/Year"));
        builder.variable(new VariableDef("electric to non electric contacts", "electric to non electric contacts", "non_electric_contacts * fraction_electric", "Contact/Year"));
        builder.variable(new VariableDef("fraction electric", "fraction electric", "Electric_Households/Total_US_Households", "Dmnl"));
        builder.variable(new VariableDef("net household additions", "net household additions", "Total_US_Households * household_addition_rate", "Household/Year"));
        builder.variable(new VariableDef("non electric contacts", "non electric contacts", "Non_Electric_Households * contact_rate", "Contact/Year"));
        builder.variable(new VariableDef("percent of US dwellings with electric power", "percent of US dwellings with electric power", "fraction_electric * 100", "Dmnl"));
        builder.variable(new VariableDef("US population", "US population", "Total_US_Households * average_household_size", "Person"));

        // Flows
        builder.flow(new FlowDef("Electric Households inflow 1", null, "conversions", "Year", null, "Electric Households"));
        builder.flow(new FlowDef("Electric Households inflow 2", null, "fraction_electric * net_household_additions", "Year", null, "Electric Households"));
        builder.flow(new FlowDef("Non Electric Households outflow 1", null, "conversions", "Year", "Non Electric Households", null));
        builder.flow(new FlowDef("Non Electric Households inflow 2", null, "(1 - fraction_electric) * net_household_additions", "Year", null, "Non Electric Households"));
        builder.flow(new FlowDef("Total US Households net flow", "Net flow for Total US Households", "net_household_additions", "Year", null, "Total US Households"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
