/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.userguidechap14;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: YEAST1.MDL
 * Source: Vensim User Guide Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' places non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' connector references non-existent element: _48</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View '1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 2' places non-existent element: cold is dormant</li>
 *   <li>View 'View 2' places non-existent element: drink or die</li>
 *   <li>View 'View 2' places non-existent element: eat or die</li>
 *   <li>View 'View 2' places non-existent element: hot is dead</li>
 *   <li>View 'View 2' places non-existent element: hunger from growth</li>
 *   <li>View 'View 2' places non-existent element: thirst from growth</li>
 *   <li>View 'View 2' places non-existent element: big growth</li>
 *   <li>View 'View 2' places non-existent element: INITIAL TIME</li>
 *   <li>View 'View 2' connector references non-existent element: cold is dormant</li>
 *   <li>View 'View 2' connector references non-existent element: cold is dormant</li>
 *   <li>View 'View 2' connector references non-existent element: drink or die</li>
 *   <li>View 'View 2' connector references non-existent element: eat or die</li>
 *   <li>View 'View 2' connector references non-existent element: eat or die</li>
 *   <li>View 'View 2' connector references non-existent element: hot is dead</li>
 *   <li>View 'View 2' connector references non-existent element: hot is dead</li>
 *   <li>View 'View 2' connector references non-existent element: hunger from growth</li>
 *   <li>View 'View 2' connector references non-existent element: thirst from growth</li>
 *   <li>View 'View 2' connector references non-existent element: big growth</li>
 *   <li>View 'View 2' connector references non-existent element: drink or die</li>
 *   <li>View 'View 2' connector references non-existent element: INITIAL TIME</li>
 *   <li>View 'View 2' connector references non-existent element: hunger from growth</li>
 *   <li>View 'View 2' connector references non-existent element: INITIAL TIME</li>
 *   <li>View 'View 2' connector references non-existent element: thirst from growth</li>
 * </ul>
 */
public class VensimYeast1 {

    public static void main(String[] args) {
        new VensimYeast1().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("YEAST1")
                .defaultSimulation("Minute", 300.0, "Minute");

        // Stocks
        builder.stock(new StockDef("Yeast Count", "The number of yeast.", 100.0, "Cell", null));

        // Constants
        builder.constant("Water", 100.0, "ml");
        builder.constant("average lifetime", 250.0, "Minute");
        builder.constant("division rate", 0.08, "1/Minute");
        builder.constant("Sugar", 100.0, "g");
        builder.constant("temperature", 85.0, "degrees farenheit");
        builder.constant("RC START TIME", 10.0, "Minute");

        // Variables
        builder.variable(new VariableDef("divisions", "divisions", "Yeast_Count*division_rate", "Cell/Minute"));
        builder.variable(new VariableDef("terminations", "The rate of termination of yeast.", "Yeast_Count/average_lifetime", "Cell/Minute"));

        // Flows
        builder.flow(new FlowDef("Yeast Count inflow 1", null, "divisions", "Minute", null, "Yeast Count"));
        builder.flow(new FlowDef("Yeast Count outflow 2", null, "terminations", "Minute", "Yeast Count", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim User Guide Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
