/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.userguidechap07complete;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;

/**
 * Imported from: price1.mdl
 * Source: Vensim User Guide Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: reference demand</li>
 *   <li>View 'View 1' places non-existent element: effect price demand</li>
 *   <li>View 'View 1' places non-existent element: price</li>
 *   <li>View 'View 1' places non-existent element: demand</li>
 *   <li>View 'View 1' places non-existent element: target price</li>
 *   <li>View 'View 1' places non-existent element: time to adjust price up</li>
 *   <li>View 'View 1' places non-existent element: target revenue</li>
 *   <li>View 'View 1' places non-existent element: demand elasticity</li>
 *   <li>View 'View 1' places non-existent element: initial price</li>
 *   <li>View 'View 1' places non-existent element: expected demand</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: change in price</li>
 *   <li>View 'View 1' places non-existent element: time to form expectations</li>
 *   <li>View 'View 1' places non-existent element: reference price</li>
 *   <li>View 'View 1' places non-existent element: time to adjust price down</li>
 *   <li>View 'View 1' connector references non-existent element: reference demand</li>
 *   <li>View 'View 1' connector references non-existent element: demand</li>
 *   <li>View 'View 1' connector references non-existent element: effect price demand</li>
 *   <li>View 'View 1' connector references non-existent element: demand</li>
 *   <li>View 'View 1' connector references non-existent element: price</li>
 *   <li>View 'View 1' connector references non-existent element: effect price demand</li>
 *   <li>View 'View 1' connector references non-existent element: demand elasticity</li>
 *   <li>View 'View 1' connector references non-existent element: effect price demand</li>
 *   <li>View 'View 1' connector references non-existent element: target revenue</li>
 *   <li>View 'View 1' connector references non-existent element: target price</li>
 *   <li>View 'View 1' connector references non-existent element: demand</li>
 *   <li>View 'View 1' connector references non-existent element: expected demand</li>
 *   <li>View 'View 1' connector references non-existent element: time to form expectations</li>
 *   <li>View 'View 1' connector references non-existent element: expected demand</li>
 *   <li>View 'View 1' connector references non-existent element: price</li>
 *   <li>View 'View 1' connector references non-existent element: change in price</li>
 *   <li>View 'View 1' connector references non-existent element: target price</li>
 *   <li>View 'View 1' connector references non-existent element: change in price</li>
 *   <li>View 'View 1' connector references non-existent element: reference price</li>
 *   <li>View 'View 1' connector references non-existent element: effect price demand</li>
 *   <li>View 'View 1' connector references non-existent element: time to adjust price down</li>
 *   <li>View 'View 1' connector references non-existent element: change in price</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class VensimPrice1 {

    public static void main(String[] args) {
        new VensimPrice1().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("price1")
                .defaultSimulation("Month", 100.0, "Month");

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim User Guide Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
