/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.samplefinance;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: FINANCE.mdl
 * Source: Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.
 * License: MIT
 * Author: Ventana Systems, Inc.
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '2' places non-existent element: _0</li>
 *   <li>View '2' places non-existent element: _0</li>
 *   <li>View '2' places non-existent element: _0</li>
 *   <li>View '2' places non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' connector references non-existent element: _0</li>
 *   <li>View '2' flow route references non-existent flow: _0</li>
 *   <li>View '2' flow route references non-existent flow: _0</li>
 *   <li>View '2' flow route references non-existent flow: _0</li>
 *   <li>View '2' flow route references non-existent flow: _0</li>
 *   <li>View '3' places non-existent element: _0</li>
 *   <li>View '3' places non-existent element: _0</li>
 *   <li>View '3' places non-existent element: _0</li>
 *   <li>View '3' places non-existent element: _0</li>
 *   <li>View '3' places non-existent element: _0</li>
 *   <li>View '3' places non-existent element: _0</li>
 *   <li>View '3' places non-existent element: _0</li>
 *   <li>View '3' places non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' connector references non-existent element: _0</li>
 *   <li>View '3' flow route references non-existent flow: _0</li>
 *   <li>View '3' flow route references non-existent flow: _0</li>
 *   <li>View '3' flow route references non-existent flow: _0</li>
 *   <li>View '3' flow route references non-existent flow: _0</li>
 *   <li>View '3' flow route references non-existent flow: _0</li>
 *   <li>View '3' flow route references non-existent flow: _0</li>
 *   <li>View '3' flow route references non-existent flow: _0</li>
 *   <li>View '3' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class VensimFinance {

    public static void main(String[] args) {
        new VensimFinance().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("FINANCE")
                .defaultSimulation("Year", 5.0, "Year", 0.0625);

        // Stocks
        builder.stock(new StockDef("Accounts Receivable", "Accounts Receivable", 0.0, "billings / (1/average_payable_delay + fractional_loss_rate)", "$", null, List.of()));
        builder.stock(new StockDef("Awaiting Billing", "Awaiting Billing", 0.0, "price * production * billing_processing_time", "$", null, List.of()));
        builder.stock(new StockDef("Book Value", "Book Value", 0.0, "$", null));
        builder.stock(new StockDef("Debt", "Debt", 0.0, "$", null));
        builder.stock(new StockDef("Potential Customers", "Potential Customers", 1.0E7, "Person", null));
        builder.stock(new StockDef("Customers", "Customers", 100000.0, "Person", null));
        builder.stock(new StockDef("New Backlog", "New Backlog", 0.0, "new_orders*normal_delivery_delay", "Gadget", null, List.of()));
        builder.stock(new StockDef("Product In Use", "Product In Use", 0.0, "Customers*product_per_customer", "Gadget", null, List.of()));
        builder.stock(new StockDef("Replacement Backlog", "Replacement Backlog", 0.0, "replacement_orders*normal_delivery_delay", "Gadget", null, List.of()));
        builder.stock(new StockDef("Average Orders", "Average Orders", 0.0, "orders_received", "Gadget/Year", null, List.of()));
        builder.stock(new StockDef("Backlog", "Backlog", 0.0, "desired_backlog", "Gadget", null, List.of()));
        builder.stock(new StockDef("Capacity", "Capacity", 0.0, "desired_capacity", "Gadget/Year", null, List.of()));
        builder.stock(new StockDef("Waiting Customers", "Waiting Customers", 0.0, "New_Backlog/product_per_customer", "Person", null, List.of()));

        // Constants
        builder.constant("average payable delay", 0.09, "Year");
        builder.constant("billing processing time", 0.04, "Year");
        builder.constant("capacity cost", 0.5, "$*Year/Gadget");
        builder.constant("CAPACITY COST MAX", 0.6, "Gadget/Year");
        builder.constant("CAPACITY COST MIN", 0.4, "Gadget/Year");
        builder.constant("debt financing fraction", 0.6, "Dmnl");
        builder.constant("debt retirement time", 3.0, "Year");
        builder.constant("discount rate", 0.12, "1/Year");
        builder.constant("fractional loss rate", 0.06, "1/Year");
        builder.constant("initial potential customers", 1.0E7, "Person");
        builder.constant("variable production cost", 0.6, "$/Widget");
        builder.constant("interest rate", 0.12, "1/Year");
        builder.constant("price", 1.0, "$/Widget");
        builder.constant("PRICE MAX", 1.2, "$/Widget");
        builder.constant("PRICE MIN", 0.9, "$/Widget");
        builder.constant("SALES FRACTION MAX", 0.006, "Dmnl");
        builder.constant("SALES FRACTION MIN", 0.004, "Dmnl");
        builder.constant("tax depreciation time", 2.0, "Year");
        builder.constant("tax rate", 0.4, "Dmnl");
        builder.constant("VARIABLE PRODUCTION COST MIN", 0.5, "$/Widget");
        builder.constant("VARIABLE PRODUCTION COST MAX", 0.7, "$/Widget");
        builder.constant("average life of product", 2.0, "Year");
        builder.constant("contact rate", 500.0, "1/Year");
        builder.constant("initial customers", 100000.0, "Person");
        builder.constant("normal delivery delay", 0.125, "Year");
        builder.constant("product per customer", 1.0, "Gadget/Person");
        builder.constant("sales fraction", 0.005, "Dmnl");
        builder.constant("capacity life", 2.0, "Year");
        builder.constant("target delivery delay", 0.125, "Year");
        builder.constant("time to average orders", 0.25, "Year");
        builder.constant("time to adjust capacity", 1.0, "Year");
        builder.constant("time to correct backlog", 0.5, "Year");

        // Variables
        builder.variable(new VariableDef("billings", "billings", "Awaiting_Billing/billing_processing_time", "$/Year"));
        builder.variable(new VariableDef("borrowing", "borrowing", "new_investment * debt_financing_fraction", "$/Year"));
        builder.variable(new VariableDef("cash receipts", "cash receipts", "Accounts_Receivable/average_payable_delay", "$/Year"));
        builder.variable(new VariableDef("direct costs", "direct costs", "production * variable_production_cost", "$/Year"));
        builder.variable(new VariableDef("gross income", "gross income", "billings", "$/Year"));
        builder.variable(new VariableDef("interest payments", "interest payments", "Debt * interest_rate", "$/Year"));
        builder.variable(new VariableDef("losses", "losses", "Accounts_Receivable * fractional_loss_rate", "$/Year"));
        builder.variable(new VariableDef("net cash flow", "net cash flow", "cash_receipts + borrowing - new_investment - direct_costs - interest_payments - principal_repayment - taxes", "$/Year"));
        builder.variable(new VariableDef("net income", "net income", "taxable_income - taxes", "$/Year"));
        builder.variable(new VariableDef("new investment", "new investment", "investment * capacity_cost", "$/Year"));
        builder.variable(new VariableDef("npv cash flow", "npv cash flow", "NPV(net_cash_flow,discount_rate,0,1)", "$"));
        builder.variable(new VariableDef("npv income", "npv income", "NPV(net_income,discount_rate,0,1)", "$"));
        builder.variable(new VariableDef("principal repayment", "principal repayment", "Debt/debt_retirement_time", "$/Year"));
        builder.variable(new VariableDef("taxes", "taxes", "taxable_income * tax_rate", "$/Year"));
        builder.variable(new VariableDef("tax depreciation", "tax depreciation", "Book_Value/tax_depreciation_time", "$/Year"));
        builder.variable(new VariableDef("taxable income", "taxable income", "gross_income - direct_costs - losses - interest_payments - tax_depreciation", "$/Year"));
        builder.variable(new VariableDef("committals", "committals", "customer_with_non_customer_contacts * sales_fraction", "Person/Year"));
        builder.variable(new VariableDef("completions", "completions", "new_shipments/product_per_customer", "Person/Year"));
        builder.variable(new VariableDef("customer prevalence", "customer prevalence", "Customers/total_market", "Dmnl"));
        builder.variable(new VariableDef("customer with non customer contacts", "customer with non customer contacts", "non_customer_contacts * customer_prevalence", "Person/Year"));
        builder.variable(new VariableDef("new orders", "new orders", "committals * product_per_customer", "Gadget/Year"));
        builder.variable(new VariableDef("new shipments", "new shipments", "total_shipments * New_Backlog/ total_backlog", "Gadget/Year"));
        builder.variable(new VariableDef("non customer contacts", "non customer contacts", "Potential_Customers * contact_rate", "Person/Year"));
        builder.variable(new VariableDef("replacement orders", "replacement orders", "Product_In_Use/average_life_of_product", "Gadget/Year"));
        builder.variable(new VariableDef("replacement shipments", "replacement shipments", "total_shipments *Replacement_Backlog/ total_backlog", "Gadget/Year"));
        builder.variable(new VariableDef("total backlog", "total backlog", "New_Backlog + Replacement_Backlog", "Gadget"));
        builder.variable(new VariableDef("total market", "total market", "Potential_Customers +Waiting_Customers + Customers", "Person"));
        builder.variable(new VariableDef("total shipments", "total shipments", "production", "Gadget/Year"));
        builder.variable(new VariableDef("orders received", "orders received", "total_orders", "Gadget/Year"));
        builder.variable(new VariableDef("backlog correction", "backlog correction", "(Backlog-desired_backlog)/time_to_correct_backlog", "Gadget/Year"));
        builder.variable(new VariableDef("capacity adjustment", "capacity adjustment", "(desired_capacity - Capacity)/time_to_adjust_capacity", "Gadget/Year/Year"));
        builder.variable(new VariableDef("delivery delay", "delivery delay", "Backlog/production", "Year"));
        builder.variable(new VariableDef("desired backlog", "desired backlog", "Average_Orders* target_delivery_delay", "Gadget"));
        builder.variable(new VariableDef("desired capacity", "desired capacity", "desired_production", "Gadget/Year"));
        builder.variable(new VariableDef("desired production", "desired production", "Average_Orders + backlog_correction", "Gadget/Year"));
        builder.variable(new VariableDef("investment", "investment", "capacity_adjustment + replacement_investment", "Gadget/Year/Year"));
        builder.variable(new VariableDef("potential production", "potential production", "Capacity", "Gadget/Year"));
        builder.variable(new VariableDef("production", "production", "MIN(desired_production,potential_production)", "Gadget/Year"));
        builder.variable(new VariableDef("reductions", "reductions", "Capacity/capacity_life", "Gadget/(Year*Year)"));
        builder.variable(new VariableDef("replacement investment", "replacement investment", "reductions", "Gadget/Year/Year"));
        builder.variable(new VariableDef("total orders", "total orders", "new_orders + replacement_orders", "Gadget/Year"));

        // Flows
        builder.flow(new FlowDef("Accounts Receivable inflow 1", null, "billings", "Year", null, "Accounts Receivable"));
        builder.flow(new FlowDef("Accounts Receivable outflow 2", null, "cash_receipts", "Year", "Accounts Receivable", null));
        builder.flow(new FlowDef("Accounts Receivable outflow 3", null, "losses", "Year", "Accounts Receivable", null));
        builder.flow(new FlowDef("Awaiting Billing inflow 1", null, "price * production", "Year", null, "Awaiting Billing"));
        builder.flow(new FlowDef("Awaiting Billing outflow 2", null, "billings", "Year", "Awaiting Billing", null));
        builder.flow(new FlowDef("Book Value inflow 1", null, "new_investment", "Year", null, "Book Value"));
        builder.flow(new FlowDef("Book Value outflow 2", null, "tax_depreciation", "Year", "Book Value", null));
        builder.flow(new FlowDef("Debt inflow 1", null, "borrowing", "Year", null, "Debt"));
        builder.flow(new FlowDef("Debt outflow 2", null, "principal_repayment", "Year", "Debt", null));
        builder.flow(new FlowDef("Potential Customers net flow", "Net flow for Potential Customers", "-committals", "Year", null, "Potential Customers"));
        builder.flow(new FlowDef("Customers net flow", "Net flow for Customers", "completions", "Year", null, "Customers"));
        builder.flow(new FlowDef("New Backlog inflow 1", null, "new_orders", "Year", null, "New Backlog"));
        builder.flow(new FlowDef("New Backlog outflow 2", null, "new_shipments", "Year", "New Backlog", null));
        builder.flow(new FlowDef("Product In Use inflow 1", null, "new_shipments", "Year", null, "Product In Use"));
        builder.flow(new FlowDef("Product In Use inflow 2", null, "replacement_shipments", "Year", null, "Product In Use"));
        builder.flow(new FlowDef("Product In Use outflow 3", null, "replacement_orders", "Year", "Product In Use", null));
        builder.flow(new FlowDef("Replacement Backlog inflow 1", null, "replacement_orders", "Year", null, "Replacement Backlog"));
        builder.flow(new FlowDef("Replacement Backlog outflow 2", null, "replacement_shipments", "Year", "Replacement Backlog", null));
        builder.flow(new FlowDef("Average Orders net flow", "Net flow for Average Orders", "(orders_received-Average_Orders)/time_to_average_orders", "Year", null, "Average Orders"));
        builder.flow(new FlowDef("Backlog inflow 1", null, "orders_received", "Year", null, "Backlog"));
        builder.flow(new FlowDef("Backlog outflow 2", null, "production", "Year", "Backlog", null));
        builder.flow(new FlowDef("Capacity inflow 1", null, "investment", "Year", null, "Capacity"));
        builder.flow(new FlowDef("Capacity outflow 2", null, "reductions", "Year", "Capacity", null));
        builder.flow(new FlowDef("Waiting Customers inflow 1", null, "committals", "Year", null, "Waiting Customers"));
        builder.flow(new FlowDef("Waiting Customers outflow 2", null, "completions", "Year", "Waiting Customers", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems, Inc.")
                .source("Vensim Sample Models, bundled with Vensim (https://vensim.com). See LICENSING.md for project license details.")
                .license("MIT")
                .url("https://www.vensim.com/documentation/sample_models.html")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
