/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.technology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: EIT.MDL
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' places non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: 1</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' connector references non-existent element: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 *   <li>View 'View 1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class Eit {

    public static void main(String[] args) {
        new Eit().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("EIT")
                .defaultSimulation("Year", 2000.0, "Year", 10.0);

        // Stocks
        builder.stock(new StockDef("Trees", "Trees", 30000.0, "trees", null));
        builder.stock(new StockDef("Population", "Population", 10.0, "people", null));

        // Constants
        builder.constant("TIME_STEP", 10.0, "Year");
        builder.constant("INITIAL_TIME", -500.0, "Year");
        builder.constant("FINAL_TIME", 1500.0, "Year");
        builder.constant("initial trees", 30000.0, "trees");
        builder.constant("per capita tree consumption", 0.01, "trees / people / Year");
        builder.constant("net birth rate", 0.0035, "fraction / Year");
        builder.constant("initial population", 10.0, "people");

        // Variables
        builder.variable(new VariableDef("tree harvesting", "tree harvesting", "MIN ( Population * per_capita_tree_consumption , Trees / TIME_STEP )", "trees / Year"));
        builder.variable(new VariableDef("net births per year", "net births per year", "net_birth_rate * Population", "people / Year"));

        // Flows
        builder.flow(new FlowDef("Trees net flow", "Net flow for Trees", "-tree_harvesting", "Year", null, "Trees"));
        builder.flow(new FlowDef("Population net flow", "Net flow for Population", "net_births_per_year", "Year", null, "Population"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
