/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.technology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 0610Diffusion and Adoption of Micro-CHP.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _268</li>
 *   <li>View 'View 1' connector references non-existent element: _268</li>
 *   <li>View 'View 1' connector references non-existent element: _268</li>
 *   <li>View 'View 1' connector references non-existent element: _268</li>
 *   <li>View 'View 1' connector references non-existent element: _268</li>
 *   <li>View 'View 1' flow route references non-existent flow: _268</li>
 * </ul>
 */
public class MicroChpDiffusion {

    public static void main(String[] args) {
        new MicroChpDiffusion().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("0610Diffusion and Adoption of Micro-CHP")
                .defaultSimulation("Month", 100.0, "Month", 0.125);

        // Stocks
        builder.stock(new StockDef("clients", "clients", 100.0, "person", null));
        builder.stock(new StockDef("potential clients", "potential clients", 1.6E7, "persoon", null));

        // Constants
        builder.constant("convincing degree", 0.01, "person/contact");
        builder.constant("social contacts per person per month", 50.0, "contact/person/Month");

        // Variables
        builder.variable(new VariableDef("_99 per cent", "\"99 per cent\"", "0.99*total_market", "person"));
        builder.variable(new VariableDef("new clients", "new clients", "contacts_of_potential_clients_with_clients*convincing_degree", "person/Month"));
        builder.variable(new VariableDef("contacts of potential clients with clients", "contacts of potential clients with clients", "contacts_with_clients*potential_client_concentration", "contact/Month"));
        builder.variable(new VariableDef("contacts with clients", "contacts with clients", "clients*social_contacts_per_person_per_month", "contact/Month"));
        builder.variable(new VariableDef("potential client concentration", "potential client concentration", "potential_clients/total_market", "dmnl"));
        builder.variable(new VariableDef("total market", "total market", "clients+potential_clients", "person"));

        // Flows
        builder.flow(new FlowDef("clients net flow", "Net flow for clients", "new_clients", "Month", null, "clients"));
        builder.flow(new FlowDef("potential clients net flow", "Net flow for potential clients", "- new_clients", "Month", null, "potential clients"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
