/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.technology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 1012_ShaleGASwoUnits.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Duplicate normalized name 'average_time_to_turn_SD_Workshoppers_into_System_Dynamicist' (from '"average time to turn SD Workshoppers into System Dynamicist."') — skipped</li>
 *   <li>Duplicate normalized name 'new_SD_workshoppers' (from '"new SD workshoppers."') — skipped</li>
 *   <li>Duplicate normalized name 'System_Dynamicists' (from '"System Dynamicists."') — skipped</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 2</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 7</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 2' places non-existent element: _48</li>
 *   <li>View 'View 2' places non-existent element: _48</li>
 *   <li>View 'View 2' connector references non-existent element: 6</li>
 *   <li>View 'View 2' connector references non-existent element: 6</li>
 *   <li>View 'View 2' connector references non-existent element: 3</li>
 *   <li>View 'View 2' connector references non-existent element: _48</li>
 *   <li>View 'View 2' connector references non-existent element: _48</li>
 *   <li>View 'View 2' connector references non-existent element: 14</li>
 *   <li>View 'View 2' connector references non-existent element: 11</li>
 *   <li>View 'View 2' connector references non-existent element: 14</li>
 *   <li>View 'View 2' connector references non-existent element: _48</li>
 *   <li>View 'View 2' flow route references non-existent flow: _48</li>
 *   <li>View 'View 2' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class ShaleGas {

    public static void main(String[] args) {
        new ShaleGas().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1012_ShaleGASwoUnits")
                .defaultSimulation("Year", 100.0, "Year", 0.0625);

        // Stocks
        builder.stock(new StockDef("annual gas demand", "annual gas demand", 2.0, "whateverunitsofreserve/Year", null));
        builder.stock(new StockDef("gas resource base", "gas resource base", 120.0, "whateverunitsofreserve", null));
        builder.stock(new StockDef("SD Workshoppers", "SD Workshoppers", 0.0, "", null));

        // Constants
        builder.constant("TIME_STEP", 0.0625, "Year");
        builder.constant("INITIAL_TIME", 0.0, "Year");
        builder.constant("FINAL_TIME", 100.0, "Year");
        builder.constant("average time to turn SD Workshoppers into System Dynamicist", 1.0, "");
        builder.constant("initial gas resource base", 120.0, "whateverunitsofreserve");
        builder.constant("new gas demand growth rate", 0.02, "whateverunitsofreserve/Year/Year");
        builder.constant("new SD workshoppers", 0.0, "");

        // Variables
        builder.variable(new VariableDef("depletion gas resource base", "depletion gas resource base", "MIN(annual_gas_demand,gas_resource_base)", "whateverunitsofreserve/Year"));
        builder.variable(new VariableDef("new gas demand", "new gas demand", "annual_gas_demand*new_gas_demand_growth_rate", "whateverunitsofreserve/Year/Year"));
        builder.variable(new VariableDef("System Dynamicists", "System Dynamicists", "SD_Workshoppers/average_time_to_turn_SD_Workshoppers_into_System_Dynamicist", ""));

        // Flows
        builder.flow(new FlowDef("annual gas demand net flow", "Net flow for annual gas demand", "new_gas_demand", "Year", null, "annual gas demand"));
        builder.flow(new FlowDef("gas resource base net flow", "Net flow for gas resource base", "-depletion_gas_resource_base", "Year", null, "gas resource base"));
        builder.flow(new FlowDef("SD Workshoppers inflow 1", null, "new_SD_workshoppers", "Year", null, "SD Workshoppers"));
        builder.flow(new FlowDef("SD Workshoppers outflow 2", null, "System_Dynamicists", "Year", "SD Workshoppers", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
