/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.technology;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.LookupTableDef;
import systems.courant.sd.model.def.StockDef;

import java.util.List;

/**
 * Imported from: STOCK.MDL
 * Source: Vensim User's Guide
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Import warnings:
 * <ul>
 *   <li>Variable 'orders' has no equation; imported as constant 0</li>
 * </ul>
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'Orders and Inventory' places non-existent element: _48</li>
 *   <li>View 'Orders and Inventory' places non-existent element: _48</li>
 *   <li>View 'Orders and Inventory' places non-existent element: _492</li>
 *   <li>View 'Orders and Inventory' places non-existent element: _204</li>
 *   <li>View 'Orders and Inventory' places non-existent element: Time</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _492</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _492</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 2</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _492</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 8</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _492</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 5</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _48</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 37</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 37</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 37</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 37</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 36</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 36</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 3</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: _204</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 60</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 56</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 60</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: Time</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 60</li>
 *   <li>View 'Orders and Inventory' connector references non-existent element: 60</li>
 *   <li>View 'Orders and Inventory' flow route references non-existent flow: _48</li>
 *   <li>View 'Orders and Inventory' flow route references non-existent flow: _48</li>
 *   <li>View 'Orders and Inventory' flow route references non-existent flow: _492</li>
 *   <li>View 'Orders and Inventory' flow route references non-existent flow: _204</li>
 *   <li>View 'Costs and Profits' places non-existent element: _668</li>
 *   <li>View 'Costs and Profits' connector references non-existent element: _668</li>
 *   <li>View 'Costs and Profits' connector references non-existent element: _668</li>
 *   <li>View 'Costs and Profits' connector references non-existent element: _668</li>
 *   <li>View 'Costs and Profits' connector references non-existent element: 4</li>
 *   <li>View 'Costs and Profits' flow route references non-existent flow: _668</li>
 * </ul>
 */
public class Stock {

    public static void main(String[] args) {
        new Stock().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("STOCK")
                .defaultSimulation("Day", 60.0, "Day");

        // Stocks
        builder.stock(new StockDef("Cumulative Profit", "Cumulative Profit", 0.0, "dollars", null));
        builder.stock(new StockDef("forecast orders", "forecast orders", 0.0, "orders", "unit/day", null, List.of()));
        builder.stock(new StockDef("Store Inventory", "Store Inventory", 0.0, "orders*(leadtime)", "unit", null, List.of()));
        builder.stock(new StockDef("Qty On Order", "Qty On Order", 0.0, "unit", null));

        // Constants
        builder.constant("TIME_STEP", 1.0, "Day");
        builder.constant("INITIAL_TIME", 0.0, "Day");
        builder.constant("FINAL_TIME", 60.0, "Day");
        builder.constant("distr orders other", 0.0, "unit/day");
        builder.constant("ORDER RULE SWITCH", 2.0, "Dmnl");
        builder.constant("max inventory value", 100.0, "unit");
        builder.constant("min inventory value", 20.0, "unit");
        builder.constant("UNIT ORDER", 1.0, "unit/day");
        builder.constant("DAYS PER YEAR", 365.0, "day/Year");
        builder.constant("WEIGHT TO CURRENT", 0.2, "1/day");
        builder.constant("REPLENISH PERIOD", 10.0, "day");
        builder.constant("orders", 0.0, "");
        builder.constant("PCT MARGIN", 10.0, "Dmnl");
        builder.constant("leadtime", 5.0, "day");
        builder.constant("ITEM PRICE", 200.0, "dollars/unit");
        builder.constant("PROCESSING COST", 2.0, "dollars/day");
        builder.constant("INTEREST", 0.25, "1/Year");

        // Lookup tables
        builder.lookupTable(new LookupTableDef("TRANSPORT RATE", "TRANSPORT RATE", new double[]{0.0, 5.0, 15.0, 30.0, 50.0, 100.0, 150.0, 200.0, 700.0}, new double[]{10.0, 30.0, 75.0, 100.0, 125.0, 165.0, 180.0, 185.0, 235.0}, "LINEAR"));

        // Variables
        builder.variable(new VariableDef("distr orders", "distr orders", "IF(ORDER_RULE_SWITCH==1, distr_orders_periodic, IF(ORDER_RULE_SWITCH==2, distr_orders_minimum, distr_orders_other))", "unit/day"));
        builder.variable(new VariableDef("distr orders minimum", "distr orders minimum", "IF( Store_Inventory+Qty_On_Order<min_inventory_value, (max_inventory_value-Qty_On_Order-Store_Inventory)/TIME_STEP,0)", "unit/day"));
        builder.variable(new VariableDef("Order Cost", "Order Cost", "IF( distr_orders>0, PROCESSING_COST+transport_cost, 0)", "dollars/day"));
        builder.variable(new VariableDef("transport cost", "transport cost", "LOOKUP(TRANSPORT_RATE, distr_orders/UNIT_ORDER)", "dollars/day"));
        builder.variable(new VariableDef("receipts", "receipts", "DELAY_FIXED(distr_orders, leadtime, 0)", "unit/day"));
        builder.variable(new VariableDef("distr orders periodic", "distr orders periodic", "IF(order_placement_day!=0, ( forecast_orders*(leadtime+REPLENISH_PERIOD)- Store_Inventory-Qty_On_Order)/order_placement_day ,0)", "unit/day"));
        builder.variable(new VariableDef("total cost", "total cost", "Cost_Of_Goods + Holding_Cost + Order_Cost", "dollars/day"));
        builder.variable(new VariableDef("profit", "profit", "Sales_Revenue -  total_cost", "dollars/day"));
        builder.variable(new VariableDef("order placement day", "order placement day", "IF(MODULO(TIME,REPLENISH_PERIOD)==0,1,0)", "day"));
        builder.variable(new VariableDef("Cost Of Goods", "Cost Of Goods", "item_cost*units_sold", "dollars/day"));
        builder.variable(new VariableDef("item cost", "item cost", "(1-PCT_MARGIN/100)*ITEM_PRICE", "dollars/unit"));
        builder.variable(new VariableDef("Holding Cost", "Holding Cost", "Store_Inventory*item_cost*INTEREST/DAYS_PER_YEAR", "dollars/day"));
        builder.variable(new VariableDef("Sales Revenue", "Sales Revenue", "units_sold*ITEM_PRICE", "dollars/day"));
        builder.variable(new VariableDef("units sold", "units sold", "IF(Store_Inventory-orders>0,orders,Store_Inventory)", "unit/day"));

        // Flows
        builder.flow(new FlowDef("Cumulative Profit net flow", "Net flow for Cumulative Profit", "profit", "Day", null, "Cumulative Profit"));
        builder.flow(new FlowDef("forecast orders net flow", "Net flow for forecast orders", "(orders-forecast_orders)* WEIGHT_TO_CURRENT", "Day", null, "forecast orders"));
        builder.flow(new FlowDef("Store Inventory inflow 1", null, "receipts", "Day", null, "Store Inventory"));
        builder.flow(new FlowDef("Store Inventory outflow 2", null, "units_sold", "Day", "Store Inventory", null));
        builder.flow(new FlowDef("Qty On Order inflow 1", null, "distr_orders", "Day", null, "Qty On Order"));
        builder.flow(new FlowDef("Qty On Order outflow 2", null, "receipts", "Day", "Qty On Order", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim User's Guide")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
