/*
 * Copyright (c) original author(s). See model metadata for attribution.
 * Licensed under CC-BY-NC-SA-4.0. See THIRD-PARTY-LICENSES for details.
 */
package systems.courant.sd.demo.social;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: 1407_ToleranceHateAggressionEZ509versionEP.mdl
 * Source: Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5
 * License: CC-BY-NC-SA-4.0
 * Author: Dr. Erik Pruyt
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' places non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: 8</li>
 *   <li>View 'View 1' connector references non-existent element: 8</li>
 *   <li>View 'View 1' connector references non-existent element: 5</li>
 *   <li>View 'View 1' connector references non-existent element: 13</li>
 *   <li>View 'View 1' connector references non-existent element: 10</li>
 *   <li>View 'View 1' connector references non-existent element: 13</li>
 *   <li>View 'View 1' connector references non-existent element: 18</li>
 *   <li>View 'View 1' connector references non-existent element: 18</li>
 *   <li>View 'View 1' connector references non-existent element: 15</li>
 *   <li>View 'View 1' connector references non-existent element: 23</li>
 *   <li>View 'View 1' connector references non-existent element: 20</li>
 *   <li>View 'View 1' connector references non-existent element: 23</li>
 *   <li>View 'View 1' connector references non-existent element: 28</li>
 *   <li>View 'View 1' connector references non-existent element: 28</li>
 *   <li>View 'View 1' connector references non-existent element: 25</li>
 *   <li>View 'View 1' connector references non-existent element: 33</li>
 *   <li>View 'View 1' connector references non-existent element: 30</li>
 *   <li>View 'View 1' connector references non-existent element: 33</li>
 *   <li>View 'View 1' connector references non-existent element: 38</li>
 *   <li>View 'View 1' connector references non-existent element: 35</li>
 *   <li>View 'View 1' connector references non-existent element: 38</li>
 *   <li>View 'View 1' connector references non-existent element: 43</li>
 *   <li>View 'View 1' connector references non-existent element: 43</li>
 *   <li>View 'View 1' connector references non-existent element: 40</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' connector references non-existent element: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 *   <li>View 'View 1' flow route references non-existent flow: _48</li>
 * </ul>
 */
public class ToleranceHateAggression {

    public static void main(String[] args) {
        new ToleranceHateAggression().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("1407_ToleranceHateAggressionEZ509versionEP")
                .defaultSimulation("Month", 50.0, "Month", 0.0625);

        // Stocks
        builder.stock(new StockDef("unfamiliarity", "unfamiliarity", 0.1, "1", null));
        builder.stock(new StockDef("hate", "hate", 0.1, "1", null));
        builder.stock(new StockDef("restraint threshold", "restraint threshold", 0.5, "1", null));
        builder.stock(new StockDef("tolerance", "tolerance", 0.5, "1", null));

        // Constants
        builder.constant("TIME_STEP", 0.0625, "Month");
        builder.constant("INITIAL_TIME", 0.0, "Month");
        builder.constant("FINAL_TIME", 50.0, "Month");
        builder.constant("EDUCATION ACTIVITY", 0.5, "1/Month");
        builder.constant("ENCOUNTER INTERVAL", 2.0, "Month");
        builder.constant("ENCOUNTER INTENSITY", 5.0, "1");
        builder.constant("DEGREE OF UNFAMILIARITY", 0.5, "1");
        builder.constant("VIOLENCE IN MEDIA", 0.4, "1");
        builder.constant("ETHICAL SCRUPLES", 0.1, "1");
        builder.constant("MAX UNFAMILIARITY", 1.0, "1");
        builder.constant("MAX HATE", 1.0, "1");
        builder.constant("MAX TOLERANCE", 1.0, "1");
        builder.constant("PROBLEM BEGINNING", 5.0, "Month");
        builder.constant("PROBLEM STRENGTH", 4.0, "1");
        builder.constant("GOVT RESOLVE", 1.0, "1");
        builder.constant("adaptation TIME", 5.0, "Month");

        // Variables
        builder.variable(new VariableDef("unfamiliar experience", "unfamiliar experience", "intolerance*DEGREE_OF_UNFAMILIARITY*encounters*ENCOUNTER_INTENSITY*unfamiliarity*(1- unfamiliarity/MAX_UNFAMILIARITY) * (1+violence)", "1/Month"));
        builder.variable(new VariableDef("hate increase", "hate increase", "unfamiliarity*intolerance*social_problems*hate*(1-hate/MAX_HATE)/adaptation_TIME * ( 1+violence)", "1/Month"));
        builder.variable(new VariableDef("tolerance erosion", "tolerance erosion", "tolerance*hate/adaptation_TIME * (1+violence)", "1/Month"));
        builder.variable(new VariableDef("increase in tolerance through educational effort", "increase in tolerance through educational effort", "SMOOTH(education_effort*tolerance*(1-tolerance/MAX_TOLERANCE),1)", "1/Month"));
        builder.variable(new VariableDef("restraint loss", "restraint loss", "hate*social_problems*VIOLENCE_IN_MEDIA*restraint_threshold/adaptation_TIME", "1/Month"));
        builder.variable(new VariableDef("restraint buildup", "restraint buildup", "max_restraint*restraint_threshold*(1-restraint_threshold/max_restraint)/adaptation_TIME", "1/Month"));
        builder.variable(new VariableDef("education effort", "education effort", "0+EDUCATION_ACTIVITY*STEP(1, 15)", "1/Month"));
        builder.variable(new VariableDef("encounters", "encounters", "PULSE_TRAIN(5,1, ENCOUNTER_INTERVAL,50)", "1/Month"));
        builder.variable(new VariableDef("violence", "violence", "hate*violent_action", "1"));
        builder.variable(new VariableDef("violent action", "violent action", "IF(hate-restraint_threshold>0, 1, 0)", "1"));
        builder.variable(new VariableDef("accustoming", "accustoming", "unfamiliarity*tolerance/adaptation_TIME", "1/Month"));
        builder.variable(new VariableDef("hate decrease", "hate decrease", "hate*tolerance/adaptation_TIME", "1/Month"));
        builder.variable(new VariableDef("intolerance", "intolerance", "MAX_TOLERANCE-tolerance", "1"));
        builder.variable(new VariableDef("max restraint", "max restraint", "govt_authority*(1-VIOLENCE_IN_MEDIA)+ETHICAL_SCRUPLES", "1"));
        builder.variable(new VariableDef("social problems", "social problems", "STEP(PROBLEM_STRENGTH, PROBLEM_BEGINNING)", "1"));
        builder.variable(new VariableDef("govt authority", "govt authority", "0+GOVT_RESOLVE*STEP(1, 10)", "1"));

        // Flows
        builder.flow(new FlowDef("unfamiliarity inflow 1", null, "unfamiliar_experience", "Month", null, "unfamiliarity"));
        builder.flow(new FlowDef("unfamiliarity outflow 2", null, "accustoming", "Month", "unfamiliarity", null));
        builder.flow(new FlowDef("hate inflow 1", null, "hate_increase", "Month", null, "hate"));
        builder.flow(new FlowDef("hate outflow 2", null, "hate_decrease", "Month", "hate", null));
        builder.flow(new FlowDef("restraint threshold inflow 1", null, "restraint_buildup", "Month", null, "restraint threshold"));
        builder.flow(new FlowDef("restraint threshold outflow 2", null, "restraint_loss", "Month", "restraint threshold", null));
        builder.flow(new FlowDef("tolerance inflow 1", null, "increase_in_tolerance_through_educational_effort", "Month", null, "tolerance"));
        builder.flow(new FlowDef("tolerance outflow 2", null, "tolerance_erosion", "Month", "tolerance", null));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Dr. Erik Pruyt")
                .source("Pruyt, E., 2013. Small System Dynamics Models for Big Issues: Triple Jump towards Real-World Complexity. TU Delft Library. ISBN 978-94-6186-195-5")
                .license("CC-BY-NC-SA-4.0")
                .url("https://simulation.tudelft.nl/SD/")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
