/*
 * Copyright (c) 2026 Courant Systems
 * Licensed under CC-BY-SA-4.0. See LICENSE in this module for details.
 */
package systems.courant.sd.demo.social;

import systems.courant.sd.Simulation;
import systems.courant.sd.model.ModelMetadata;
import systems.courant.sd.model.compile.CompiledModel;
import systems.courant.sd.model.compile.ModelCompiler;
import systems.courant.sd.model.def.ModelDefinitionBuilder;
import systems.courant.sd.model.def.VariableDef;
import systems.courant.sd.model.def.FlowDef;
import systems.courant.sd.model.def.StockDef;

/**
 * Imported from: TUBS.MDL
 * Source: Vensim Sample Models
 * License: MIT
 * Author: Ventana Systems
 *
 * <p>Auto-generated by courant-tools ImportPipeline.
 *
 * <p>Validation errors (model may need manual fixes):
 * <ul>
 *   <li>View '1' places non-existent element: Water</li>
 *   <li>View '1' places non-existent element: Time</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: inflow</li>
 *   <li>View '1' places non-existent element: _0</li>
 *   <li>View '1' places non-existent element: outflow</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: Water</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: 2</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: 4</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: Water</li>
 *   <li>View '1' connector references non-existent element: Water</li>
 *   <li>View '1' connector references non-existent element: outflow</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: _0</li>
 *   <li>View '1' connector references non-existent element: Time</li>
 *   <li>View '1' connector references non-existent element: inflow</li>
 *   <li>View '1' connector references non-existent element: outflow</li>
 *   <li>View '1' connector references non-existent element: inflow</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 *   <li>View '1' flow route references non-existent flow: _0</li>
 * </ul>
 */
public class Tubs {

    public static void main(String[] args) {
        new Tubs().run();
    }

    public void run() {
        var builder = new ModelDefinitionBuilder()
                .name("TUBS")
                .defaultSimulation("Minute", 100.0, "Minute");

        // Stocks
        builder.stock(new StockDef("Water T1", "The amount of water in each tub.", 0.0, "Gallon", null));
        builder.stock(new StockDef("Water T2", "The amount of water in each tub.", 0.0, "Gallon", null));
        builder.stock(new StockDef("Water T3", "The amount of water in each tub.", 0.0, "Gallon", null));
        builder.stock(new StockDef("Water T4", "The amount of water in each tub.", 0.0, "Gallon", null));
        builder.stock(new StockDef("Water T5", "The amount of water in each tub.", 0.0, "Gallon", null));

        // Constants
        builder.constant("TIME_STEP", 1.0, "Minute");
        builder.constant("INITIAL_TIME", 0.0, "Minute");
        builder.constant("FINAL_TIME", 100.0, "Minute");

        // Variables
        builder.variable(new VariableDef("inflow T1", "inflow[T1]", "IF(TIME > 10,1,0)", ""));
        builder.variable(new VariableDef("inflow T2", "The inflow into each tub.", "outflow_T1", "Gallon/Minute"));
        builder.variable(new VariableDef("inflow T3", "The inflow into each tub.", "outflow_T2", "Gallon/Minute"));
        builder.variable(new VariableDef("inflow T4", "The inflow into each tub.", "outflow_T3", "Gallon/Minute"));
        builder.variable(new VariableDef("inflow T5", "The inflow into each tub.", "outflow_T4", "Gallon/Minute"));
        builder.variable(new VariableDef("outflow T1", "The amount of water flowing out of the tub.", "IF(Water_T1 > 10,inflow_T1,0)", "Gallon/Minute"));
        builder.variable(new VariableDef("outflow T2", "The amount of water flowing out of the tub.", "IF(Water_T2 > 10,inflow_T2,0)", "Gallon/Minute"));
        builder.variable(new VariableDef("outflow T3", "The amount of water flowing out of the tub.", "IF(Water_T3 > 10,inflow_T3,0)", "Gallon/Minute"));
        builder.variable(new VariableDef("outflow T4", "The amount of water flowing out of the tub.", "IF(Water_T4 > 10,inflow_T4,0)", "Gallon/Minute"));
        builder.variable(new VariableDef("outflow T5", "The amount of water flowing out of the tub.", "IF(Water_T5 > 10,inflow_T5,0)", "Gallon/Minute"));

        // Flows
        builder.flow(new FlowDef("Water T1 net flow", "Net flow for Water T1", "inflow_T1-outflow_T1", "Minute", null, "Water T1"));
        builder.flow(new FlowDef("Water T2 net flow", "Net flow for Water T2", "inflow_T2-outflow_T2", "Minute", null, "Water T2"));
        builder.flow(new FlowDef("Water T3 net flow", "Net flow for Water T3", "inflow_T3-outflow_T3", "Minute", null, "Water T3"));
        builder.flow(new FlowDef("Water T4 net flow", "Net flow for Water T4", "inflow_T4-outflow_T4", "Minute", null, "Water T4"));
        builder.flow(new FlowDef("Water T5 net flow", "Net flow for Water T5", "inflow_T5-outflow_T5", "Minute", null, "Water T5"));

        var definition = builder.build();
        var compiled = new ModelCompiler().compile(definition);

        compiled.getModel().setMetadata(ModelMetadata.builder()
                .author("Ventana Systems")
                .source("Vensim Sample Models")
                .license("MIT")
                .build());

        Simulation sim = compiled.createSimulation();
        sim.execute();
    }
}
